// src/components/ui/Select.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { mdiCheck, mdiChevronDown } from "@mdi/js";
import { cn } from "@/lib/cn";
import { Icon } from "@/components/ui/Icon";
import { useAnimatedPresence } from "@/lib/useAnimatedPresence";

function hasOwn(obj: unknown, key: string) {
  return !!obj && typeof obj === "object" && Object.prototype.hasOwnProperty.call(obj, key);
}

type SelectProps<T> = {
  value?: any;
  options?: T[];
  placeholder?: string;
  labelKey?: string;
  valueKey?: string;
  className?: string;
  menuClassName?: string;
  optionClassName?: string;
  disabled?: boolean;
  align?: "left" | "right";
  returnObject?: boolean;
  matchTriggerWidth?: boolean;
  fluid?: boolean;
  searchable?: boolean;
  searchPlaceholder?: string;
  searchFilterFn?: ((option: T, query: string) => boolean) | null;
  onChange?: (value: any, option: T) => void;
  onOpenChange?: (value: boolean) => void;
  renderTrigger?: (ctx: { selectedOption: T | null; open: boolean; selectedLabel: string }) => React.ReactNode;
  renderOption?: (ctx: { option: T; selected: boolean; label: string }) => React.ReactNode;
};

export function Select<T>({
  value,
  options = [],
  placeholder = "Select an option",
  labelKey = "label",
  valueKey = "value",
  className = "",
  menuClassName = "",
  optionClassName = "",
  disabled = false,
  align = "left",
  returnObject = false,
  matchTriggerWidth = true,
  fluid = true,
  searchable = false,
  searchPlaceholder = "Search...",
  searchFilterFn = null,
  onChange,
  onOpenChange,
  renderTrigger,
  renderOption,
}: SelectProps<T>) {
  const root = useRef<HTMLDivElement>(null);
  const trigger = useRef<HTMLButtonElement>(null);
  const searchInput = useRef<HTMLInputElement>(null);
  const [open, setOpen] = useState(false);
  const [menuWidth, setMenuWidth] = useState(0);
  const [rect, setRect] = useState<DOMRect | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [hoveredIndex, setHoveredIndex] = useState(-1);
  const [focusedIndex, setFocusedIndex] = useState(-1);
  const [mounted, setMounted] = useState(false);
  const menuPresence = useAnimatedPresence(open, 220);

  function getOptionValue(option: any) {
    if (hasOwn(option, valueKey)) return option[valueKey];
    if (hasOwn(option, "value")) return option.value;
    return option;
  }

  function getOptionLabel(option: any) {
    if (hasOwn(option, labelKey)) return `${option[labelKey]}`;
    if (hasOwn(option, "text")) return `${option.text}`;
    if (hasOwn(option, "label")) return `${option.label}`;
    if (hasOwn(option, "name")) return `${option.name}`;
    return `${option ?? ""}`;
  }

  function isSelected(option: any) {
    const currentValue = returnObject ? getOptionValue(value) : value;
    return getOptionValue(option) === currentValue;
  }

  const normalizedOptions = useMemo(() =>
    (options || []).map((option, index) => ({
      raw: option,
      label: getOptionLabel(option),
      key: hasOwn(option, valueKey) ? `${getOptionValue(option)}` : `${index}-${getOptionLabel(option)}`,
    })),
  [options, labelKey, valueKey]);

  const selectedOption = useMemo(() => normalizedOptions.find((option) => isSelected(option.raw))?.raw || null,
  [normalizedOptions, value, returnObject, valueKey]);

  const visibleOptions = useMemo(() => {
    const query = searchQuery.trim().toLowerCase();
    if (!query) return normalizedOptions;
    if (searchFilterFn) return normalizedOptions.filter((option) => searchFilterFn(option.raw, query));
    return normalizedOptions.filter((option) => option.label.toLowerCase().includes(query));
  }, [normalizedOptions, searchQuery, searchFilterFn]);

  const selectedLabel = selectedOption ? getOptionLabel(selectedOption) : placeholder;
  const selectedVisibleIndex = visibleOptions.findIndex((option) => isSelected(option.raw));
  const edgeTopActive = visibleOptions.length > 0 && (hoveredIndex === 0 || focusedIndex === 0 || selectedVisibleIndex === 0);
  const edgeBottomActive = (() => {
    const lastIndex = visibleOptions.length - 1;
    return lastIndex >= 0 && (hoveredIndex === lastIndex || focusedIndex === lastIndex || selectedVisibleIndex === lastIndex);
  })();
  const scrollEdgeStyle = {
    "--edge-top": edgeTopActive ? "var(--color-base)" : "var(--colorbg)",
    "--edge-bottom": edgeBottomActive ? "var(--color-base)" : "var(--colorbg)",
  } as React.CSSProperties;

  function syncMenuGeometry() {
    const nextRect = trigger.current?.getBoundingClientRect() || null;
    setRect(nextRect);
    setMenuWidth(trigger.current?.offsetWidth || 0);
  }

  function setOpenValue(nextOpen: boolean) {
    if (nextOpen) syncMenuGeometry();
    setOpen(nextOpen);
    if (nextOpen) {
      requestAnimationFrame(() => {
        if (searchable && searchInput.current) searchInput.current.focus();
        else root.current?.focus();
      });
    } else {
      setSearchQuery("");
      setHoveredIndex(-1);
      setFocusedIndex(-1);
    }
    onOpenChange?.(nextOpen);
  }

  function toggleMenu() {
    if (disabled) return;
    setOpenValue(!open);
  }

  function closeMenu() {
    if (!open) return;
    setOpenValue(false);
  }

  function isOptionActive(option: T, index: number) {
    return hoveredIndex === index || focusedIndex === index || isSelected(option);
  }

  function getOptionClass(option: T, index: number) {
    const lastIndex = visibleOptions.length - 1;
    const active = isOptionActive(option, index);
    const nextActive = active && index < lastIndex && isOptionActive(visibleOptions[index + 1].raw, index + 1);
    return cn(
      "ui-select-option flex w-full cursor-pointer items-center justify-between bg-transparent text-left text-[0.8rem] text-[color:var(--color-foreground)] transition-colors",
      isSelected(option) && "ui-select-option-selected",
      active && "ui-select-option-active",
      nextActive && "ui-select-option-active-join-next",
      active && index === 0 && "ui-select-option-active-first",
      active && index === lastIndex && "ui-select-option-active-last",
      optionClassName,
    );
  }

  function selectOption(option: T) {
    onChange?.(returnObject ? option : getOptionValue(option), option);
    closeMenu();
  }

  useEffect(() => setMounted(true), []);

  useEffect(() => {
    function handleOutsideClick(event: MouseEvent) {
      const target = event.target as Node;
      if (root.current?.contains(target)) return;
      if ((target as HTMLElement)?.closest?.(".ui-select-menu")) return;
      closeMenu();
    }

    function handleDocumentKeydown(event: KeyboardEvent) {
      if (!open || event.key !== "Escape") return;
      event.stopPropagation();
      closeMenu();
    }

    function handleWindowScroll(event: Event) {
      if (!open) return;
      const target = event.target;
      if (target instanceof Node && target !== document) {
        if (root.current?.contains(target) || target.contains(root.current)) return;
        if (target instanceof Element && target.closest?.(".ui-select-menu")) return;
      }
      closeMenu();
      const activeElement = document.activeElement;
      if (activeElement instanceof HTMLElement && root.current?.contains(activeElement)) activeElement.blur();
    }

    document.addEventListener("mousedown", handleOutsideClick);
    document.addEventListener("keydown", handleDocumentKeydown);
    window.addEventListener("resize", syncMenuGeometry, { passive: true });
    window.addEventListener("scroll", handleWindowScroll, true);
    return () => {
      document.removeEventListener("mousedown", handleOutsideClick);
      document.removeEventListener("keydown", handleDocumentKeydown);
      window.removeEventListener("resize", syncMenuGeometry);
      window.removeEventListener("scroll", handleWindowScroll, true);
    };
  }, [open]);

  const menuStyle = (() => {
    if (!menuPresence.present || !rect) return undefined;
    const style: React.CSSProperties = { top: rect.bottom + 6 };
    if (align === "right") style.right = window.innerWidth - rect.right;
    else style.left = rect.left;
    if (matchTriggerWidth && menuWidth) style.minWidth = menuWidth;
    return style;
  })();

  const menu = menuPresence.present && mounted && menuStyle ? createPortal(
    <div
      data-state={menuPresence.state}
      className={cn(
        "glass-panel rounded-[calc(var(--radius)+6px)] ui-select-menu fixed z-[360] min-w-[max-content] overflow-hidden border bg-[color:var(--color-card)] p-0",
        menuPresence.state === "closed" && "pointer-events-none",
        searchable && "ui-select-menu-searchable",
        menuClassName,
      )}
      role="listbox"
      style={menuStyle}
      onAnimationEnd={menuPresence.onAnimationEnd}
      onMouseDown={(event) => event.stopPropagation()}
      onClick={(event) => event.stopPropagation()}
    >
      {searchable ? (
        <div className="ui-select-search-wrap">
          <input ref={searchInput} type="text" className="ui-select-search-input" value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} placeholder={searchPlaceholder} />
        </div>
      ) : null}
      <div className="ui-select-menu-scroll" style={scrollEdgeStyle}>
        <div className="scroll-area-viewport h-full w-full scroll-area-viewport-native overflow-y-auto overflow-x-hidden">
          <div className="min-h-full min-w-full scroll-area-content-native">
            {visibleOptions.map((option, index) => (
              <button
                key={option.key || index}
                type="button"
                role="option"
                aria-selected={isSelected(option.raw)}
                className={getOptionClass(option.raw, index)}
                onMouseEnter={() => setHoveredIndex(index)}
                onMouseLeave={() => setHoveredIndex(-1)}
                onFocus={() => setFocusedIndex(index)}
                onBlur={() => setFocusedIndex(-1)}
                onClick={() => selectOption(option.raw)}
              >
                {renderOption ? renderOption({ option: option.raw, selected: isSelected(option.raw), label: option.label }) : (
                  <>
                    <span className="truncate">{option.label}</span>
                    {isSelected(option.raw) ? <Icon icon={mdiCheck} size="sm" className="ml-3 shrink-0 text-[color:var(--color-foreground)]" /> : null}
                  </>
                )}
              </button>
            ))}
            {visibleOptions.length === 0 ? <div className="ui-select-empty">No options found</div> : null}
          </div>
        </div>
      </div>
    </div>,
    document.body,
  ) : null;

  return (
    <div
      ref={root}
      className={cn(fluid ? "relative w-full" : "relative inline-block", "outline-none")}
      tabIndex={-1}
      onClick={(event) => event.stopPropagation()}
      onKeyDown={(event) => { if (event.key === "Escape") { event.stopPropagation(); closeMenu(); } }}
    >
      <button
        ref={trigger}
        type="button"
        disabled={disabled}
        aria-expanded={open ? "true" : "false"}
        aria-haspopup="listbox"
        className={cn("ui-select-trigger flex h-11 items-center justify-between rounded-xl border border-[color:var(--color-border)] bg-[color:var(--color-card)] px-3 text-left text-[0.8rem] text-[color:var(--color-foreground)] transition outline-none disabled:cursor-not-allowed disabled:opacity-60", open && "ui-select-trigger-open", fluid ? "w-full" : "w-auto", className)}
        onClick={toggleMenu}
      >
        {renderTrigger ? renderTrigger({ selectedOption, open, selectedLabel }) : (
          <>
            <span className="truncate">{selectedLabel}</span>
            <Icon icon={mdiChevronDown} size="sm" className={cn("ui-select-trigger-chevron ml-2 shrink-0", open && "ui-select-trigger-chevron-open")} />
          </>
        )}
      </button>
      {menu}
    </div>
  );
}

// src/components/ui/select/Select.vue
<template>
  <div
    ref="root"
    :class="rootClass"
    tabindex="-1"
    @click.stop
    @keydown.escape.stop="closeMenu"
  >
    <button
      ref="trigger"
      type="button"
      :disabled="disabled"
      :aria-expanded="open ? 'true' : 'false'"
      aria-haspopup="listbox"
      :class="triggerClass"
      @click="toggleMenu"
    >
      <slot
        name="trigger"
        :selected-option="selectedOption"
        :open="open"
      >
        <span class="truncate">{{ selectedLabel }}</span>
        <UiIcon :icon="mdiChevronDown" size="sm" :class-name="`ui-select-trigger-chevron ml-2 shrink-0 ${open ? 'ui-select-trigger-chevron-open' : ''}`" />
      </slot>
    </button>

    <Teleport to="body">
      <transition name="ui-select-menu" appear>
        <UiCard
          v-if="open"
          :class-name="menuClass"
          :style="menuStyle"
          role="listbox"
          @click.stop
          @mousedown.stop
        >
          <div v-if="searchable" class="ui-select-search-wrap">
            <input
              ref="searchInput"
              v-model="searchQuery"
              type="text"
              class="ui-select-search-input"
              :placeholder="searchPlaceholder"
            >
          </div>
          <UiScrollArea class-name="ui-select-menu-scroll" :native-scrollbar="true" :style="scrollEdgeStyle">
            <button
              v-for="(option, index) in visibleOptions"
              :key="option.key || index"
              type="button"
              role="option"
              :aria-selected="isSelected(option.raw) ? 'true' : 'false'"
              :class="getOptionClass(option.raw, index)"
              @mouseenter="hoveredIndex = index"
              @mouseleave="hoveredIndex = -1"
              @focus="focusedIndex = index"
              @blur="focusedIndex = -1"
              @click="selectOption(option.raw)"
            >
              <slot
                name="option"
                :option="option.raw"
                :selected="isSelected(option.raw)"
              >
                <span class="truncate">{{ option.label }}</span>
                <UiIcon
                  v-if="isSelected(option.raw)"
                  :icon="mdiCheck"
                  size="sm"
                  class-name="ml-3 shrink-0 text-[color:var(--color-foreground)]"
                />
              </slot>
            </button>
            <div v-if="visibleOptions.length === 0" class="ui-select-empty">
              No options found
            </div>
          </UiScrollArea>
        </UiCard>
      </transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, nextTick } from "vue";
import { mdiCheck, mdiChevronDown } from "@mdi/js";
import { cn } from "@/utils/functions";
import UiCard from "@/components/ui/card/Card.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import UiScrollArea from "@/components/ui/scroll-area/ScrollArea.vue";

function hasOwn(obj: unknown, key: string) {
  return !!obj && typeof obj === "object" && Object.prototype.hasOwnProperty.call(obj, key);
}

const props = withDefaults(defineProps<{
  modelValue?: any;
  options?: any[];
  placeholder?: string;
  labelKey?: string;
  valueKey?: string;
  className?: string;
  menuClassName?: string;
  optionClassName?: string;
  disabled?: boolean;
  align?: string;
  returnObject?: boolean;
  matchTriggerWidth?: boolean;
  fluid?: boolean;
  searchable?: boolean;
  searchPlaceholder?: string;
  searchFilterFn?: ((option: any, query: string) => boolean) | null;
}>(), {
  modelValue: undefined,
  options: () => [],
  placeholder: "Select an option",
  labelKey: "label",
  valueKey: "value",
  className: "",
  menuClassName: "",
  optionClassName: "",
  disabled: false,
  align: "left",
  returnObject: false,
  matchTriggerWidth: true,
  fluid: true,
  searchable: false,
  searchPlaceholder: "Search...",
  searchFilterFn: null,
});

const emit = defineEmits<{
  (e: "update:modelValue", value: any): void;
  (e: "open-change", value: boolean): void;
}>();

const root = ref<HTMLElement | null>(null);
const trigger = ref<HTMLElement | null>(null);
const searchInput = ref<HTMLInputElement | null>(null);

const open = ref(false);
const menuWidth = ref(0);
const searchQuery = ref("");
const hoveredIndex = ref(-1);
const focusedIndex = ref(-1);

function getOptionValue(option: any) {
  if (hasOwn(option, props.valueKey)) return option[props.valueKey];
  if (hasOwn(option, "value")) return option.value;
  return option;
}

function getOptionLabel(option: any) {
  if (hasOwn(option, props.labelKey)) return `${option[props.labelKey]}`;
  if (hasOwn(option, "text")) return `${option.text}`;
  if (hasOwn(option, "label")) return `${option.label}`;
  if (hasOwn(option, "name")) return `${option.name}`;
  return `${option ?? ""}`;
}

function isSelected(option: any) {
  const currentValue = props.returnObject ? getOptionValue(props.modelValue) : props.modelValue;
  return getOptionValue(option) === currentValue;
}

const normalizedOptions = computed(() =>
  (props.options || []).map((option, index) => ({
    raw: option,
    label: getOptionLabel(option),
    key: hasOwn(option, props.valueKey) ? `${getOptionValue(option)}` : `${index}-${getOptionLabel(option)}`,
  })),
);

const selectedOption = computed(() =>
  normalizedOptions.value.find((option) => isSelected(option.raw))?.raw || null,
);

const visibleOptions = computed(() => {
  const query = searchQuery.value.trim().toLowerCase();
  if (!query) return normalizedOptions.value;
  if (props.searchFilterFn) {
    return normalizedOptions.value.filter((option) => props.searchFilterFn!(option.raw, query));
  }
  return normalizedOptions.value.filter((option) => option.label.toLowerCase().includes(query));
});

const selectedLabel = computed(() =>
  selectedOption.value
    ? getOptionLabel(selectedOption.value)
    : props.placeholder,
);

const selectedVisibleIndex = computed(() =>
  visibleOptions.value.findIndex((option) => isSelected(option.raw)),
);

const edgeTopActive = computed(() =>
  visibleOptions.value.length > 0
  && (hoveredIndex.value === 0 || focusedIndex.value === 0 || selectedVisibleIndex.value === 0),
);

const edgeBottomActive = computed(() => {
  const lastIndex = visibleOptions.value.length - 1;
  return lastIndex >= 0
    && (hoveredIndex.value === lastIndex || focusedIndex.value === lastIndex || selectedVisibleIndex.value === lastIndex);
});

const scrollEdgeStyle = computed(() => ({
  "--edge-top": edgeTopActive.value ? "var(--color-base)" : "var(--colorbg)",
  "--edge-bottom": edgeBottomActive.value ? "var(--color-base)" : "var(--colorbg)",
}));

const triggerClass = computed(() =>
  cn(
    "ui-select-trigger flex h-11 items-center justify-between rounded-xl border border-[color:var(--color-border)] bg-[color:var(--color-card)] px-3 text-left text-[0.8rem] text-[color:var(--color-foreground)] transition outline-none disabled:cursor-not-allowed disabled:opacity-60",
    open.value && "ui-select-trigger-open",
    props.fluid ? "w-full" : "w-auto",
    props.className,
  ),
);

const rootClass = computed(() => cn(props.fluid ? "relative w-full" : "relative inline-block", "outline-none"));

const menuClass = computed(() =>
  cn(
    "ui-select-menu fixed z-[360] min-w-[max-content] overflow-hidden border bg-[color:var(--color-card)] p-0",
    props.searchable && "ui-select-menu-searchable",
    props.menuClassName,
  ),
);

const menuStyle = computed(() => {
  if (!open.value) return undefined;
  const rect = trigger.value?.getBoundingClientRect();
  if (!rect) return undefined;
  const style: Record<string, string> = {
    top: `${rect.bottom + 6}px`,
  };
  if (props.align === "right") {
    style.right = `${window.innerWidth - rect.right}px`;
  } else {
    style.left = `${rect.left}px`;
  }
  if (props.matchTriggerWidth && menuWidth.value) {
    style.minWidth = `${menuWidth.value}px`;
  }
  return style;
});

function isOptionActive(option: any, index: number) {
  return hoveredIndex.value === index || focusedIndex.value === index || isSelected(option);
}

function getOptionClass(option: any, index: number) {
  const lastIndex = visibleOptions.value.length - 1;
  const active = isOptionActive(option, index);
  const nextActive = active
    && index < lastIndex
    && isOptionActive(visibleOptions.value[index + 1].raw, index + 1);
  return cn(
    "ui-select-option flex w-full cursor-pointer items-center justify-between bg-transparent text-left text-[0.8rem] text-[color:var(--color-foreground)] transition-colors",
    isSelected(option) && "ui-select-option-selected",
    active && "ui-select-option-active",
    nextActive && "ui-select-option-active-join-next",
    active && index === 0 && "ui-select-option-active-first",
    active && index === lastIndex && "ui-select-option-active-last",
    props.optionClassName,
  );
}

function syncMenuWidth() {
  menuWidth.value = trigger.value?.offsetWidth || 0;
}

function setOpen(value: boolean) {
  if (value) {
    syncMenuWidth();
  }
  open.value = value;
  if (value) {
    nextTick(() => {
      if (props.searchable && searchInput.value) {
        searchInput.value.focus();
      } else if (root.value) {
        root.value.focus();
      }
    });
  } else {
    searchQuery.value = "";
    hoveredIndex.value = -1;
    focusedIndex.value = -1;
  }
  emit("open-change", value);
}

function toggleMenu() {
  if (props.disabled) return;
  setOpen(!open.value);
}

function closeMenu() {
  if (!open.value) return;
  setOpen(false);
}

function handleOutsideClick(event: MouseEvent) {
  if (!root.value?.contains(event.target as Node)) {
    closeMenu();
  }
}

function handleWindowScroll(event: Event) {
  if (!open.value) return;
  const target = event?.target;
  if (target instanceof Node && target !== document) {
    // Allow scroll from inside the select, from an ancestor, or from the teleported menu
    if (root.value?.contains(target) || target.contains(root.value)) return;
    if (target instanceof Element && target.closest?.(".ui-select-menu")) return;
  }
  closeMenu();
  const activeElement = document.activeElement;
  if (activeElement instanceof HTMLElement && root.value?.contains(activeElement)) {
    activeElement.blur();
  }
}

function selectOption(option: any) {
  emit("update:modelValue", props.returnObject ? option : getOptionValue(option));
  closeMenu();
}

onMounted(() => {
  document.addEventListener("mousedown", handleOutsideClick);
  window.addEventListener("resize", syncMenuWidth);
  window.addEventListener("scroll", handleWindowScroll, true);
});

onBeforeUnmount(() => {
  document.removeEventListener("mousedown", handleOutsideClick);
  window.removeEventListener("resize", syncMenuWidth);
  window.removeEventListener("scroll", handleWindowScroll, true);
});
</script>

<style scoped>
.ui-select-search-wrap {
  position: relative;
  padding: 0.5rem 0.75rem;
  background: var(--colorbg);
  border-top: 0 !important;
  border-bottom: 1px solid var(--color-light);
  box-shadow: none;
}

.ui-select-search-input {
  width: 100%;
  height: 1.95rem;
  border-radius: 0;
  border: 0;
  background: transparent;
  color: var(--color-foreground);
  padding: 0;
  font-size: 0.83rem;
  outline: none;
  box-shadow: none;
}

.ui-select-search-input:focus {
  border-color: transparent;
  box-shadow: none;
}

.ui-select-menu-scroll {
  position: relative;
  max-height: 18rem;
  overflow: hidden;
  background: var(--colorbg);
}

.ui-select-menu-scroll :deep(.scroll-area-viewport-native) {
  max-height: 18rem;
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;
  overscroll-behavior-y: contain;
  background: linear-gradient(
    to bottom,
    var(--edge-top, var(--colorbg)) 0%,
    var(--edge-bottom, var(--colorbg)) 100%
  );
}

.ui-select-menu-scroll :deep(.scroll-area-content-native) {
  background: transparent;
  width: 100%;
}

.ui-select-empty {
  padding: 0.65rem 0.95rem;
  color: var(--color-muted-foreground);
  font-size: 0.8rem;
}

.ui-select-menu {
  border-color: var(--color-light) !important;
  background: var(--colorbg) !important;
  -webkit-backdrop-filter: none !important;
  backdrop-filter: none !important;
  box-shadow: 0 20px 56px rgb(2 6 23 / 0.34);
}

.ui-select-menu-enter-active,
.ui-select-menu-leave-active {
  transition: transform 220ms cubic-bezier(0.16, 1, 0.3, 1), opacity 180ms ease;
}

.ui-select-menu-enter-from,
.ui-select-menu-leave-to {
  opacity: 0;
  transform: translateY(6px);
}

.ui-select-trigger {
  border-color: var(--color-light) !important;
  background: var(--color-card) !important;
  color: var(--color-muted-foreground) !important;
  cursor: pointer;
  -webkit-backdrop-filter: blur(14px);
  backdrop-filter: blur(14px);
  transition: border-color 180ms ease, background-color 180ms ease, color 180ms ease, box-shadow 180ms ease;
}

.ui-select-trigger:hover {
  border-color: var(--color-bold) !important;
  background: var(--color-base) !important;
  color: var(--color-foreground) !important;
}

.ui-select-trigger-open {
  border-color: var(--color-bold) !important;
  background: var(--color-base) !important;
  color: var(--color-foreground) !important;
  box-shadow: none;
}

.ui-select-trigger-chevron {
  color: var(--color-muted-foreground);
  transition: transform 180ms ease, color 180ms ease;
}

.ui-select-trigger-chevron-open {
  transform: rotate(180deg);
  color: var(--color-foreground);
}

.ui-select-trigger:focus {
  border-color: var(--color-bold);
  box-shadow: none;
}

.ui-select-option {
  --ui-select-line-top: transparent;
  --ui-select-line-bottom: transparent;
  width: 100%;
  white-space: nowrap;
  margin-inline: 0;
  position: relative;
  z-index: 1;
  border-radius: 0;
  padding: 0.68rem 0.75rem;
  background: var(--colorbg) !important;
  border: 0 !important;
  outline: none;
  box-shadow: inset 0 1px 0 var(--ui-select-line-top), inset 0 -1px 0 var(--ui-select-line-bottom);
}

.ui-select-option + .ui-select-option {
  margin-top: 0;
}

.ui-select-option-active,
.ui-select-option:hover,
.ui-select-option:focus,
.ui-select-option:focus-visible,
.ui-select-option:active {
  --ui-select-line-top: var(--color-light);
  --ui-select-line-bottom: var(--color-light);
  background: var(--color-base) !important;
  outline: none;
}

.ui-select-option-selected {
  --ui-select-line-top: var(--color-light);
  --ui-select-line-bottom: var(--color-light);
  background: var(--color-base) !important;
}

/* join/edge classes use doubled class selector to beat :hover specificity (0,2,0 > 0,1,1) */
.ui-select-option.ui-select-option-active-join-next {
  --ui-select-line-bottom: transparent;
}

.ui-select-option.ui-select-option-active-first {
  --ui-select-line-top: transparent;
}

.ui-select-option.ui-select-option-active-last {
  --ui-select-line-bottom: transparent;
}

</style>
