// src/components/chat/ArchiveTranslations.vue
<template>
  <UiCard class-name="tl-overlay w-full border border-white/10 p-0 text-sm shadow-none">
    <div class="flex items-center justify-between gap-3 border-b border-white/10 px-3 py-2">
      <div>TLdex [{{ liveTlLang }}]</div>
      <div class="flex items-center gap-1">
        <UiButton
          variant="ghost"
          size="icon"
          class-name="h-7 w-7 rounded-full"
          title="-2s"
          @click="timeOffsetSeconds -= 2"
        >
          <UiIcon :icon="mdiChevronLeft" size="sm" />
        </UiButton>
        <button
          type="button"
          class="rounded-md px-2 py-1 font-mono text-xs text-slate-300 transition hover:bg-white/8"
          @click="dialog = true"
        >
          {{ `${timeOffsetSeconds >= 0 ? "+" : ""}${timeOffsetSeconds}s` }}
        </button>
        <UiDialog
          :open="dialog"
          class-name="max-w-xs p-0"
          @update:open="dialog = $event"
        >
          <UiCard class-name="space-y-4 p-5">
            <div class="text-sm font-semibold text-white">
              Time Offset
            </div>
            <label class="flex flex-col gap-2 text-sm">
              <span class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Offset</span>
              <div class="flex items-center gap-2">
                <UiInput v-model.number="timeOffsetSeconds" type="number" class-name="flex-1" />
                <span class="text-slate-400">s</span>
              </div>
            </label>
          </UiCard>
        </UiDialog>
        <UiButton
          variant="ghost"
          size="icon"
          class-name="h-7 w-7 rounded-full"
          title="+2s"
          @click="timeOffsetSeconds += 2"
        >
          <UiIcon :icon="mdiChevronRight" size="sm" />
        </UiButton>
        <UiButton
          variant="ghost"
          size="icon"
          class-name="h-7 w-7 rounded-full"
          :title="$t('views.watch.chat.showSubtitle')"
          @click="showSubtitle = !showSubtitle"
        >
          <UiIcon
            :icon="mdiSubtitlesOutline"
            size="sm"
            :class-name="showSubtitle ? 'text-[color:var(--color-primary)]' : ''"
          />
        </UiButton>
        <UiButton
          variant="ghost"
          size="icon"
          class-name="h-7 w-7 rounded-full"
          :title="$t('views.watch.chat.expandTL')"
          @click="expanded = true"
        >
          <UiIcon :icon="mdiArrowExpand" size="sm" />
        </UiButton>
        <UiDialog
          :open="expanded"
          class-name="max-w-4xl p-0"
          @update:open="expanded = $event"
        >
          <UiCard class-name="p-0">
            <div :id="expandedMsgId" class="flex tl-expanded" />
            <div class="flex justify-end border-t border-white/10 px-4 py-3">
              <UiButton variant="destructive" size="sm" @click="expanded = false">
                {{ $t("views.app.close_btn") }}
              </UiButton>
            </div>
          </UiCard>
        </UiDialog>
        <WatchLiveTranslationsSetting />
      </div>
    </div>
    <Teleport :to="`#${expandedMsgId}`" :disabled="!expanded">
      <virtual-list
        ref="tlBody"
        class="archive tl-body px-1 py-0 lg:px-3"
        :style="{
          'font-size': liveTlFontSize + 'px',
        }"
        :data-component="ChatMessage"
        :data-key="getKey"
        :data-sources="dividedTLs"
        :item-height="20"
        :item-class-add="addClass"
        :keeps="50"
        @click="handleClick"
      />
    </Teleport>
    <Teleport v-if="showSubtitle" :to="`#overlay-${video.id}`">
      <WatchSubtitleOverlay :messages="toDisplay" />
    </Teleport>
  </UiCard>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick, getCurrentInstance } from "vue";
import VirtualList from "vue-virtual-scroll-list";
import { mdiChevronLeft, mdiChevronRight } from "@mdi/js";
import { mdiArrowExpand, mdiSubtitlesOutline } from "@mdi/js";
import { useChatMixin } from "@/composables/useChatMixin";
import UiButton from "@/components/ui/button/Button.vue";
import UiCard from "@/components/ui/card/Card.vue";
import UiDialog from "@/components/ui/dialog/Dialog.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import UiInput from "@/components/ui/input/Input.vue";
import WatchLiveTranslationsSetting from "./LiveTranslationsSetting.vue";
import ChatMessage from "./ChatMessage.vue";
import WatchSubtitleOverlay from "../watch/WatchSubtitleOverlay.vue";

defineOptions({ name: "ArchiveTranslations" });

const instance = getCurrentInstance();
const expandedMsgId = `tl-expanded-${instance?.uid ?? Math.random().toString(36).slice(2)}`;
const props = withDefaults(defineProps<{
  video: Record<string, any>;
  currentTime?: number;
  useLocalSubtitleToggle?: boolean;
}>(), {
  currentTime: 0,
});

const emit = defineEmits<{
  (e: "timeJump", time: number, a: boolean, b: boolean): void;
}>();

const {
  tlHistory,
  expanded,
  liveTlLang,
  liveTlFontSize,
  liveTlHideSpoiler,
  showSubtitle,
  blockedNames,
  loadMessages,
} = useChatMixin({
  video: props.video,
  currentTime: computed(() => props.currentTime),
  useLocalSubtitleToggle: props.useLocalSubtitleToggle,
});

const curIndex = ref(0);
const dialog = ref(false);
const timeOffsetSeconds = ref(0);

const tlBody = ref<any>(null);

const dividedTLs = computed(() => {
  const filtered = tlHistory.value.filter((m: any) => !blockedNames.value.has(m.name));
  return filtered.map((item: any, index: number, arr: any[]) => {
    const shouldHideAuthor = index > 0 && (!(index === 0
      || index === arr.length - 1
      || item.name !== arr[index - 1].name
      || !!item.breakpoint));
    const newtime = item.timestamp + timeOffsetSeconds.value * 1000;
    const relativeMs = item.relativeMs + timeOffsetSeconds.value * 1000;
    return { ...item, shouldHideAuthor, relativeMs, timestamp: newtime };
  });
});

const toDisplay = computed(() => {
  if (!dividedTLs.value.length || !showSubtitle.value) return [];
  const startIdx = Math.max(curIndex.value - 1, 0);
  const buffer = dividedTLs.value.slice(startIdx, startIdx + 2);
  return buffer.filter((m: any) => {
    const displayTime = +m.duration || (m.message.length * 65 + 1800);
    return props.currentTime * 1000 >= m.relativeMs && props.currentTime * 1000 < m.relativeMs + displayTime;
  });
});

watch(liveTlLang, () => {
  loadMessages(true, true);
});

watch(() => props.currentTime, (time) => {
  if (!dividedTLs.value.length) return;
  const msTime = time * 1000;
  const cur = dividedTLs.value[curIndex.value].relativeMs;

  const startIndex = time < cur ? 0 : curIndex.value;
  for (let i = startIndex; i < tlHistory.value.length; i += 1) {
    if (i === dividedTLs.value.length - 1) {
      curIndex.value = dividedTLs.value.length - 1;
      return;
    }
    if (msTime <= dividedTLs.value[i].relativeMs) {
      curIndex.value = Math.max(i - 1, 0);
      return;
    }
  }
});

watch(curIndex, (idx) => {
  if (liveTlHideSpoiler.value) {
    nextTick(() => {
      tlBody.value?.scrollToBottom();
    });
  } else {
    scrollToIndex(idx);
  }
});

// Load messages on creation
loadMessages(true, true);

function addClass(index: number) {
  if (index === curIndex.value) {
    return "active-message";
  }
  if (liveTlHideSpoiler.value && (index > curIndex.value)) {
    return "hide-spoiler";
  }
  return "";
}

function getKey(item: any) {
  return item.timestamp + item.message + item.name;
}

function handleClick(e: MouseEvent) {
  const target = e.target as HTMLElement;
  if (target.matches(".tl-message, .tl-message *")) {
    emit("timeJump", +target.parentElement!.getAttribute("data-time")!, true, true);
    e.preventDefault();
  }
}

function scrollToIndex(idx: number) {
  const ref = tlBody.value;
  if (!ref) return;
  const idxSize = ref.virtual.sizes.get(idx) ?? 50;
  const idxOffset = ref.virtual.getOffset(idx);
  const nearBottom = idxOffset + ref.getClientSize() > ref.getScrollSize();
  if (nearBottom) {
    ref.scrollToBottom();
  } else {
    ref.scrollToOffset(idxOffset - (ref.getClientSize() / 2) + idxSize);
  }
}
</script>

<style>
.tl-body.archive {
    overflow-y: auto;
    position: relative;
    overscroll-behavior: contain;
    height: calc(100% - 32px);
    display: flex;
    flex-direction: column-reverse;
    flex-direction: column;
    line-height: 1.35;
    letter-spacing: 0.0178571429em !important;
}

.active-message {
    position: relative;
}
.active-message {
    z-index: 0;
}
.active-message .tl-message::before {
    content: "";
    background-color: color-mix(in srgb, var(--color-primary) 70%, transparent);
    opacity: 0.25;
    width: calc(100%);
    height: calc(100%);
    background-size: cover;
    position: absolute;
    top: -1px;
    left: 0;
    z-index: -1;
}
.hide-spoiler {
    display: none;
}
</style>

// src/components/chat/ArchiveTranslations.tsx
"use client";

import { createPortal } from "react-dom";
import { useEffect, useId, useMemo, useRef, useState } from "react";
import { mdiArrowExpand, mdiChevronLeft, mdiChevronRight, mdiSubtitlesOutline } from "@mdi/js";
import { dayjs } from "@/lib/time";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Dialog } from "@/components/ui/Dialog";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/Input";
import { ChatMessage } from "@/components/chat/ChatMessage";
import { LiveTranslationsSetting } from "@/components/chat/LiveTranslationsSetting";
import { WatchSubtitleOverlay } from "@/components/watch/WatchSubtitleOverlay";
import { useAppState } from "@/lib/store";

export function ArchiveTranslations({ video, currentTime = 0, useLocalSubtitleToggle = false, className = "", style, onTimeJump }: { video: Record<string, any>; currentTime?: number; useLocalSubtitleToggle?: boolean; className?: string; style?: React.CSSProperties; onTimeJump?: (time: number, a?: boolean, b?: boolean) => void }) {
  const app = useAppState();
  const [tlHistory, setTlHistory] = useState<any[]>([]);
  const [expanded, setExpanded] = useState(false);
  const [dialog, setDialog] = useState(false);
  const [timeOffsetSeconds, setTimeOffsetSeconds] = useState(0);
  const [liveTlLang, setLiveTlLang] = useState(app.settings.liveTlLang);
  const [showSubtitle, setShowSubtitle] = useState(useLocalSubtitleToggle ? true : app.settings.liveTlShowSubtitle);
  const [curIndex, setCurIndex] = useState(0);
  const [subtitleTarget, setSubtitleTarget] = useState<HTMLElement | null>(null);
  const expandedMsgId = `tl-expanded-${useId().replace(/:/g, "")}`;
  const bodyRef = useRef<HTMLDivElement | null>(null);
  const startTimeMillis = video?.available_at ? Number(dayjs(video.available_at)) : null;
  const blockedNames = useMemo(() => new Set(app.settings.liveTlBlocked || []), [app.settings.liveTlBlocked]);

  function parseMessage(msg: any) {
    const next = { ...msg };
    next.timestamp = +next.timestamp;
    next.relativeMs = startTimeMillis ? next.timestamp - startTimeMillis : 0;
    next.key = next.name + next.timestamp + next.message;
    if (next.message?.includes?.("https://") && !next.parsed) {
      const regex = /(\S+)(https:\/\/(yt\d+\.ggpht\.com\/[a-zA-Z0-9_\-=/]+-c-k-nd|www\.youtube\.com\/[a-zA-Z0-9_\-=/]+\.svg))/gi;
      next.parsed = next.message.replace(/<([^>]*)>/g, "($1)").replace(regex, '<img src="$2" />');
    }
    return next;
  }
  function loadMessages() {
    if (!video?.id) return;
    api.chatHistory(video.id, { lang: liveTlLang, verified: app.settings.liveTlShowVerified, moderator: app.settings.liveTlShowModerator, vtuber: app.settings.liveTlShowVtuber, limit: 100000 })
      .then(({ data }: any) => setTlHistory((data || []).map(parseMessage)))
      .catch(console.error);
  }

  useEffect(() => { setLiveTlLang(app.settings.liveTlLang); }, [app.settings.liveTlLang]);
  useEffect(() => { if (!useLocalSubtitleToggle) setShowSubtitle(app.settings.liveTlShowSubtitle); }, [app.settings.liveTlShowSubtitle, useLocalSubtitleToggle]);
  useEffect(() => { loadMessages(); }, [video?.id, liveTlLang, app.settings.liveTlShowVerified, app.settings.liveTlShowModerator, app.settings.liveTlShowVtuber]);
  useEffect(() => { if (!video?.id) setSubtitleTarget(null); else setSubtitleTarget(document.getElementById(`overlay-${video.id}`)); }, [video?.id, showSubtitle]);

  const dividedTLs = useMemo(() => {
    const filtered = tlHistory.filter((m: any) => !blockedNames.has(m.name));
    return filtered.map((item: any, index: number, arr: any[]) => {
      const shouldHideAuthor = index > 0 && (!(index === 0 || index === arr.length - 1 || item.name !== arr[index - 1].name || !!item.breakpoint));
      const newtime = item.timestamp + timeOffsetSeconds * 1000;
      const relativeMs = item.relativeMs + timeOffsetSeconds * 1000;
      return { ...item, shouldHideAuthor, relativeMs, timestamp: newtime };
    });
  }, [tlHistory, blockedNames, timeOffsetSeconds]);

  const toDisplay = useMemo(() => {
    if (!dividedTLs.length || !showSubtitle) return [];
    const startIdx = Math.max(curIndex - 1, 0);
    const buffer = dividedTLs.slice(startIdx, startIdx + 2);
    return buffer.filter((m: any) => {
      const displayTime = +m.duration || (String(m.message || "").length * 65 + 1800);
      return currentTime * 1000 >= m.relativeMs && currentTime * 1000 < m.relativeMs + displayTime;
    });
  }, [dividedTLs, showSubtitle, curIndex, currentTime]);

  useEffect(() => {
    if (!dividedTLs.length) return;
    const msTime = currentTime * 1000;
    const cur = dividedTLs[curIndex]?.relativeMs ?? 0;
    const startIndex = currentTime < cur ? 0 : curIndex;
    for (let i = startIndex; i < dividedTLs.length; i += 1) {
      if (i === dividedTLs.length - 1) { setCurIndex(dividedTLs.length - 1); return; }
      if (msTime <= dividedTLs[i].relativeMs) { setCurIndex(Math.max(i - 1, 0)); return; }
    }
  }, [currentTime, dividedTLs.length, timeOffsetSeconds]);

  useEffect(() => {
    const el = bodyRef.current;
    if (!el) return;
    if (app.settings.liveTlHideSpoiler) el.scrollTop = el.scrollHeight;
    else {
      const target = el.querySelector(`[data-archive-index="${curIndex}"]`) as HTMLElement | null;
      if (target) target.scrollIntoView({ block: "center" });
    }
  }, [curIndex, app.settings.liveTlHideSpoiler]);

  function itemClass(index: number) {
    if (index === curIndex) return "active-message";
    if (app.settings.liveTlHideSpoiler && index > curIndex) return "hide-spoiler";
    return "";
  }
  function handleClick(e: React.MouseEvent) {
    const target = e.target as HTMLElement;
    const link = target.closest(".tl-message") as HTMLElement | null;
    if (link) {
      onTimeJump?.(+link.getAttribute("data-time")!, true, true);
      e.preventDefault();
    }
  }

  const body = <div ref={bodyRef} className="archive tl-body px-1 py-0 lg:px-3" style={{ fontSize: `${app.settings.liveTlFontSize}px` }} onClick={handleClick}>{dividedTLs.map((item, index) => <div key={item.key || `${item.timestamp}${item.message}${item.name}`} data-archive-index={index} className={itemClass(index)}><ChatMessage source={item} /></div>)}</div>;

  return (
    <Card className={`tl-overlay w-full border border-white/10 p-0 text-sm shadow-none ${className}`} style={style}>
      <div className="flex items-center justify-between gap-3 border-b border-white/10 px-3 py-2">
        <div>TLdex [{liveTlLang}]</div>
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="icon" className="h-7 w-7 rounded-full" title="-2s" onClick={() => setTimeOffsetSeconds((v) => v - 2)}><Icon icon={mdiChevronLeft} size="sm" /></Button>
          <button type="button" className="rounded-md px-2 py-1 font-mono text-xs text-slate-300 transition hover:bg-white/8" onClick={() => setDialog(true)}>{`${timeOffsetSeconds >= 0 ? "+" : ""}${timeOffsetSeconds}s`}</button>
          <Dialog open={dialog} className="max-w-xs p-0" onOpenChange={setDialog}><Card className="space-y-4 p-5"><div className="text-sm font-semibold text-white">Time Offset</div><label className="flex flex-col gap-2 text-sm"><span className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Offset</span><div className="flex items-center gap-2"><Input value={timeOffsetSeconds} type="number" className="flex-1" onChange={(event) => setTimeOffsetSeconds(Number(event.target.value))} /><span className="text-slate-400">s</span></div></label></Card></Dialog>
          <Button variant="ghost" size="icon" className="h-7 w-7 rounded-full" title="+2s" onClick={() => setTimeOffsetSeconds((v) => v + 2)}><Icon icon={mdiChevronRight} size="sm" /></Button>
          <Button variant="ghost" size="icon" className="h-7 w-7 rounded-full" title="Show Subtitle" onClick={() => setShowSubtitle((v) => !v)}><Icon icon={mdiSubtitlesOutline} size="sm" className={showSubtitle ? "text-[color:var(--color-primary)]" : ""} /></Button>
          <Button variant="ghost" size="icon" className="h-7 w-7 rounded-full" title="Expand TL" onClick={() => setExpanded(true)}><Icon icon={mdiArrowExpand} size="sm" /></Button>
          <Dialog open={expanded} className="max-w-4xl p-0" onOpenChange={setExpanded}><Card className="p-0"><div id={expandedMsgId} className="flex tl-expanded">{body}</div><div className="flex justify-end border-t border-white/10 px-4 py-3"><Button variant="destructive" size="sm" onClick={() => setExpanded(false)}>Close</Button></div></Card></Dialog>
          <LiveTranslationsSetting />
        </div>
      </div>
      {expanded ? null : body}
      {showSubtitle && subtitleTarget ? createPortal(<WatchSubtitleOverlay messages={toDisplay} />, subtitleTarget) : null}
    </Card>
  );
}
