// src/components/chat/ChatMessage.tsx
"use client";

import { useMemo, useState } from "react";
import { dayjs, formatDuration } from "@/lib/time";
import { useAppState } from "@/lib/store";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Dialog } from "@/components/ui/Dialog";
import { Icon } from "@/components/ui/Icon";
import { ChannelImg } from "@/components/channel/ChannelImg";
import * as icons from "@/lib/icons";

export function ChatMessage({ source, hideAuthor = false }: { source: Record<string, any>; index?: number; hideAuthor?: boolean }) {
  const app = useAppState();
  const [showBlockChannelDialog, setShowBlockChannelDialog] = useState(false);
  const realTime = useMemo(() => dayjs(source.timestamp).format("LTS"), [source.timestamp]);
  const displayTime = useMemo(() => {
    if (!source.relativeMs) return null;
    return (Math.sign(source.relativeMs) < 0 ? "-" : "") + formatDuration(Math.abs(source.relativeMs));
  }, [source.relativeMs]);
  const blockedNames = new Set(app.settings.liveTlBlocked || []);

  function toggleBlockName(name: string) {
    const next = new Set(app.settings.liveTlBlocked || []);
    if (next.has(name)) next.delete(name);
    else next.add(name);
    app.patchSettings({ liveTlBlocked: [...next] } as any);
  }

  return (
    <div className={`flex flex-row ${!hideAuthor && !source.shouldHideAuthor ? "with-author" : ""}`}>
      {source.is_vtuber && source.channel_id ? (
        <div style={{ minWidth: 28 }} className="mr-2">
          {!hideAuthor && !source.shouldHideAuthor ? (
            <ChannelImg className="self-center" channel={{ id: source.channel_id, name: source.name }} size={28} rounded noLink />
          ) : null}
        </div>
      ) : null}
      <div className="basis-full">
        {!hideAuthor && !source.shouldHideAuthor ? (
          <div
            className={`tl-caption ${source.is_owner ? "text-[color:var(--color-primary)]" : (!source.is_owner && (source.is_verified || source.is_moderator || source.is_vtuber) ? "text-[color:var(--color-accent)]" : "")}`}
          >
            <button type="button" className="tl-name relative text-left" onClick={() => setShowBlockChannelDialog(true)}>
              {source.is_vtuber ? <span>[Vtuber]</span> : null}
              {source.is_moderator ? <span>[Mod]</span> : null}
              {source.name}<span>{source.is_verified ? <span style={{ fontWeight: 800 }}> ✓</span> : null}:</span>
              <Icon icon={icons.mdiCog} size="xs" className="tl-name-icon absolute mt-[2px] w-[11px]" />
            </button>
          </div>
        ) : null}
        <a className="tl-message" data-time={source.relativeMs / 1000}>
          {source.timestamp ? (
            <span className="tl-caption mr-1">
              {app.settings.liveTlShowLocalTime || !displayTime ? realTime : displayTime}
            </span>
          ) : null}
          {source.parsed ? <span className="text-[color:var(--color-primary)]" dangerouslySetInnerHTML={{ __html: source.parsed }} /> : <span className="text-[color:var(--color-primary)]">{source.message}</span>}
        </a>
      </div>
      {!hideAuthor && !source.shouldHideAuthor ? (
        <Dialog open={showBlockChannelDialog} className="max-w-lg p-0" onOpenChange={setShowBlockChannelDialog}>
          <Card className="space-y-5 p-5">
            <div className="text-lg font-semibold text-white">
              {source.name}
            </div>
            <div className="flex flex-wrap gap-2">
              {source.channel_id ? (
                <Button as="a" href={`https://youtube.com/channel/${source.channel_id}`} target="_blank" rel="noreferrer" variant="destructive" size="sm">
                  <Icon icon={icons.mdiYoutube} size="sm" />
                  Youtube
                </Button>
              ) : null}
              {source.channel_id && source.is_vtuber ? (
                <Button as="a" href={`https://holodex.net/channel/${source.channel_id}`} target="_blank" rel="noreferrer" variant="secondary" size="sm">
                  Holodex
                </Button>
              ) : null}
              <Button variant="outline" size="sm" onClick={() => toggleBlockName(source.name)}>
                {!blockedNames.has(source.name) ? "Block Channel" : "Unblock"}
              </Button>
            </div>
          </Card>
        </Dialog>
      ) : null}
    </div>
  );
}

// src/components/chat/ChatMessage.vue
<template>
  <div class="flex flex-row" :class="{ 'with-author': !hideAuthor && !source.shouldHideAuthor}">
    <div v-if="source.is_vtuber && source.channel_id" style="min-width: 28px;" class="mr-2">
      <channel-img
        v-if="!hideAuthor && !source.shouldHideAuthor"
        class="self-center"
        :channel="{ id: source.channel_id, name: source.name }"
        :size="28"
        rounded
        no-link
      />
    </div>
    <div class="basis-full">
      <div
        v-if="!hideAuthor && !source.shouldHideAuthor"
        :class="{
          'tl-caption': true,
          'text-[color:var(--color-primary)]': source.is_owner,
          'text-[color:var(--color-accent)]': !source.is_owner && (source.is_verified || source.is_moderator || source.is_vtuber),
        }"
      >
        <button type="button" class="tl-name relative text-left" @click="showBlockChannelDialog = true">
          <!-- <span v-if="source.is_owner">👑</span> -->
          <span v-if="source.is_vtuber">[Vtuber]</span>
          <span v-if="source.is_moderator">[Mod]</span>
          {{ source.name }}<span v-if="source.is_verified" style="font-weight: 800"> ✓</span>:
          <UiIcon :icon="icons.mdiCog" size="xs" class-name="tl-name-icon absolute mt-[2px] w-[11px]" />
        </button>
      </div>
      <a class="tl-message" :data-time="source.relativeMs/1000">
        <span v-if="source.timestamp" class="tl-caption mr-1">
          {{ liveTlShowLocalTime || !displayTime ? realTime : displayTime }}
        </span>
        <span v-if="source.parsed" class="text-[color:var(--color-primary)]" v-html="source.parsed" />
        <span v-else class="text-[color:var(--color-primary)]">{{ source.message }}</span>
      </a>
    </div>
    <UiDialog
      v-if="!hideAuthor && !source.shouldHideAuthor"
      :open="showBlockChannelDialog"
      class-name="max-w-lg p-0"
      @update:open="showBlockChannelDialog = $event"
    >
      <UiCard class-name="space-y-5 p-5">
        <div class="text-lg font-semibold text-white">
          {{ source.name }}
        </div>
        <div class="flex flex-wrap gap-2">
          <UiButton
            v-if="source.channel_id"
            as="a"
            :href="`https://youtube.com/channel/${source.channel_id}`"
            target="_blank"
            rel="noreferrer"
            variant="destructive"
            size="sm"
          >
            <UiIcon :icon="icons.mdiYoutube" size="sm" />
            Youtube
          </UiButton>
          <UiButton
            v-if="source.channel_id && source.is_vtuber"
            as="a"
            :href="`https://holodex.net/channel/${source.channel_id}`"
            target="_blank"
            rel="noreferrer"
            variant="secondary"
            size="sm"
          >
            Holodex
          </UiButton>
          <UiButton variant="outline" size="sm" @click="toggleBlockName(source.name)">
            {{ !blockedNames.has(source.name) ? "Block Channel" : "Unblock" }}
          </UiButton>
        </div>
      </UiCard>
    </UiDialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { dayjs, formatDuration } from "@/utils/time";
import * as icons from "@/utils/icons";
import { useSettingsStore } from "@/stores/settings";
import UiButton from "@/components/ui/button/Button.vue";
import UiCard from "@/components/ui/card/Card.vue";
import UiDialog from "@/components/ui/dialog/Dialog.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import ChannelImg from "../channel/ChannelImg.vue";

defineOptions({ name: "ChatMessage" });

const props = defineProps<{
  source: Record<string, any>;
  index?: number;
  hideAuthor?: boolean;
}>();

const settingsStore = useSettingsStore();

const showBlockChannelDialog = ref(false);

const realTime = computed(() => dayjs(props.source.timestamp).format("LTS"));

const displayTime = computed(() => {
  if (!props.source.relativeMs) return null;
  return (Math.sign(props.source.relativeMs) < 0 ? "-" : "") + formatDuration(Math.abs(props.source.relativeMs));
});

const liveTlShowLocalTime = computed(() => settingsStore.liveTlShowLocalTime);
const blockedNames = computed(() => settingsStore.liveTlBlockedNames);

function toggleBlockName(name: string) {
  settingsStore.toggleLiveTlBlocked(name);
}
</script>

<style>
.tl-caption {
    color: hsla(0, 0%, 70%, 0.7);
}

.tl-body .tl-caption {
    letter-spacing: 0.033em;
    font-size: 0.85em;
}

.tl-name, .tl-message {
  word-break: break-word;
}

.tl-name {
  cursor: pointer;
  background: transparent;
  border: 0;
  padding: 0;
}
.tl-name .tl-name-icon {
  opacity: 0;
}

.tl-name:hover .tl-name-icon {
  opacity: 1;
}

.with-author {
  border-top: 1px solid rgb(255 255 255 / 0.08);
  margin-top: 4px;
  padding-top: 4px;
}

/* Emojis */
.tl-message img {
  width: auto;
  height: 1.3em;
  vertical-align: middle;
}
</style>
