// src/components/chat/MessageRenderer.tsx
"use client";

import { forwardRef, useImperativeHandle, useRef } from "react";
import { checkIOS } from "@/lib/functions";
import { ChatMessage } from "@/components/chat/ChatMessage";

export type MessageRendererHandle = { scrollToBottom: () => void };

export const MessageRenderer = forwardRef<MessageRendererHandle, { tlHistory?: any[]; fontSize?: number; children?: React.ReactNode }>(function MessageRenderer({ tlHistory = [], fontSize = 14, children }, ref) {
  const tlBody = useRef<HTMLDivElement | null>(null);
  const hideAuthor = (item: any, index: number) => index > 0 && index < tlHistory.length - 1 && item.name === tlHistory[index - 1].name && !item.breakpoint;
  const scrollToBottom = () => { if (tlBody.current && Math.abs(tlBody.current.scrollTop / tlBody.current.scrollHeight) <= 0.15) tlBody.current.scrollTop = 0; };
  useImperativeHandle(ref, () => ({ scrollToBottom }));
  const iosClass = checkIOS() ? "ios-safari-reverse-fix" : "";
  return (
    <div ref={tlBody} className={`tl-body p-1 lg:p-3 ${iosClass}`} style={{ fontSize: `${fontSize}px` }}>
      <div className={iosClass}>
        {tlHistory.map((item, index) => (
          <ChatMessage key={item.key || `${item.name}-${item.timestamp}-${index}`} source={item} hideAuthor={hideAuthor(item, index)} />
        ))}
      </div>
      <div className={`text-center ${iosClass}`}>
        {children}
      </div>
    </div>
  );
});

// src/components/chat/MessageRenderer.vue
<template>
  <div
    ref="tlBody"
    class="tl-body p-1 lg:p-3"
    :style="{
      'font-size': fontSize + 'px',
    }"
    :class="{'ios-safari-reverse-fix': checkIOS() }"
  >
    <transition-group name="fade" :class="{'ios-safari-reverse-fix': checkIOS() }">
      <template v-for="(item, index) in tlHistory" :key="item.key">
        <chat-message
          :source="item"
          :hide-author="hideAuthor(item, index)"
        />
      </template>
    </transition-group>
    <!-- Slot for adding a Load More button on top of Messages -->
    <div class="text-center" :class="{'ios-safari-reverse-fix': checkIOS() }">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { checkIOS } from "@/utils/functions";
import ChatMessage from "./ChatMessage.vue";

defineOptions({ name: "MessageRenderer" });

const props = withDefaults(defineProps<{
  tlHistory?: any[];
  fontSize?: number;
}>(), {
  tlHistory: () => [],
  fontSize: 14,
});

const tlBody = ref<HTMLElement | null>(null);

function hideAuthor(item: any, index: number) {
  return !(index === 0
    || index === props.tlHistory.length - 1
    || item.name !== props.tlHistory[index - 1].name
    || !!item.breakpoint);
}

function scrollToBottom() {
  if (tlBody.value && Math.abs(tlBody.value.scrollTop / tlBody.value.scrollHeight) <= 0.15) {
    tlBody.value.scrollTop = 0;
  }
}

defineExpose({ scrollToBottom });
</script>

<style>
.fade-enter-active,
.fade-leave-active {
    transition: all 0.4s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
    opacity: 0;
}

.ios-safari-reverse-fix {
  transform: scale(1,-1);
  flex-direction: column !important;
}
</style>
