// src/components/edit/VideoEditMentions.tsx
"use client";

import { useEffect, useState } from "react";
import { mdiAt } from "@mdi/js";
import { api } from "@/lib/api";
import { useAppState } from "@/lib/store";
import { Button } from "@/components/ui/Button";
import { Icon } from "@/components/ui/Icon";
import { ChannelAutocomplete } from "@/components/channel/ChannelAutocomplete";
import { ChannelImg } from "@/components/channel/ChannelImg";
import { ChannelInfo } from "@/components/channel/ChannelInfo";
import { channelDisplayName } from "@/lib/video-format";
import * as icons from "@/lib/icons";

export function VideoEditMentions({ video }: { video: any }) {
  const app = useAppState();
  const [mentions, setMentions] = useState<any[]>([]);
  const [showSuccessAlert, setShowSuccessAlert] = useState(false);
  const [showErrorAlert, setShowErrorAlert] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [selectedChannel, setSelectedChannel] = useState<any>(null);
  const useEnglishName = app.settings.nameProperty === "english_name";

  useEffect(() => { updateMentions(); }, [video.id]);
  function showSuccess(message: string) { setShowSuccessAlert(true); setSuccessMessage(message); setTimeout(() => setShowSuccessAlert(false), 4000); }
  function showError(message: string) { setErrorMessage(message); setShowErrorAlert(true); setTimeout(() => setShowErrorAlert(false), 4000); }
  function updateMentions() { api.getMentions(video.id).then(({ data }: any) => setMentions(data)).catch(console.error); }
  function deleteMention(channelId: string) { api.deleteMentions(video.id, [channelId], app.userdata.jwt).then(({ data }: any) => { if (!data) return; showSuccess("Successfully deleted mention"); updateMentions(); }).catch((e: any) => showError(e.response?.data?.message || e.message || "Error occured")); }
  function addMention(channelId: string) { api.addMention(video.id, channelId, app.userdata.jwt).then(({ data }: any) => { if (!data) return; showSuccess(`Added channel: ${channelDisplayName(selectedChannel, useEnglishName)}`); updateMentions(); }).catch((e: any) => showError(e.response?.data?.message || e.message || "Error occured")); }

  return <div>
    <div className="text-h6"><Icon icon={mdiAt} size="sm" /> Channel Mentions/Tags</div>
    {successMessage && showSuccessAlert ? <div className="mb-3 rounded-2xl border border-emerald-400/30 bg-emerald-500/20 px-4 py-3 text-sm text-white">{successMessage}</div> : null}
    {errorMessage && showErrorAlert ? <div className="mb-3 rounded-2xl border border-rose-400/30 bg-rose-500/20 px-4 py-3 text-sm text-white">{errorMessage}</div> : null}
    <div className="my-2 flex flex-col gap-2"><ChannelAutocomplete value={selectedChannel} onChange={setSelectedChannel} /><Button disabled={!selectedChannel?.id} onClick={() => addMention(selectedChannel.id)}>Add</Button></div>
    <div className="channel-list-container">{mentions.map((channel, index) => <div key={`${channel.id || "channel"}-${index}`}>{index > 0 ? <div className="channel-list-divider" /> : null}<div className="flex items-start gap-3 px-4 py-3 no-underline hover:bg-white/5"><div className="shrink-0"><ChannelImg channel={channel} size={55} /></div><ChannelInfo channel={channel} includeVideoCount={false} /><Button className="deleteBtn h-10 w-10" variant="destructive" size="icon" onClick={(e: React.MouseEvent) => { e.stopPropagation(); e.preventDefault(); deleteMention(channel.id); }}><Icon icon={icons.mdiDelete} size="lg" /></Button></div></div>)}</div>
  </div>;
}

// src/components/edit/VideoEditMentions.vue
<template>
  <div>
    <div class="text-h6">
      <UiIcon :icon="mdiAt" size="sm" /> Channel Mentions/Tags
    </div>
    <div
      v-if="successMessage && showSuccessAlert"
      class="mb-3 rounded-2xl border border-emerald-400/30 bg-emerald-500/20 px-4 py-3 text-sm text-white"
    >
      {{ successMessage }}
    </div>
    <div
      v-if="errorMessage && showErrorAlert"
      class="mb-3 rounded-2xl border border-rose-400/30 bg-rose-500/20 px-4 py-3 text-sm text-white"
    >
      {{ errorMessage }}
    </div>
    <div class="my-2 flex flex-col gap-2">
      <channel-autocomplete v-model="selectedChannel" />
      <UiButton :disabled="!selectedChannel?.id" @click="addMention(selectedChannel.id)">
        Add
      </UiButton>
    </div>
    <channel-list :channels="mentions" :include-video-count="false">
      <template #action="{ channel }">
        <UiButton
          class="deleteBtn"
          variant="destructive"
          size="icon"
          class-name="h-10 w-10"
          @click.stop.prevent="deleteMention(channel.id)"
        >
          <UiIcon :icon="icons.mdiDelete" size="lg" />
        </UiButton>
      </template>
    </channel-list>
    <!-- <loading-overlay :isLoading="isLoading" :showError="hasError" /> -->
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { mdiAt } from "@mdi/js";
import backendApi from "@/utils/backend-api";
import UiButton from "@/components/ui/button/Button.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import ChannelAutocomplete from "@/components/channel/ChannelAutocomplete.vue";
import ChannelList from "../channel/ChannelList.vue";
import { useAppStore } from "@/stores/app";
import { useSettingsStore } from "@/stores/settings";

const props = defineProps<{ video: any }>();

const appStore = useAppStore();
const settingsStore = useSettingsStore();
const mentions = ref<any[]>([]);
const isLoading = ref(true);
const showSuccessAlert = ref(false);
const showErrorAlert = ref(false);
const errorMessage = ref("");
const successMessage = ref("");
const selectedChannel = ref<any>(null);

function getChannelName(channel: any) {
  return channel[settingsStore.nameProperty] || channel.name;
}

function showSuccess(message: string) {
  showSuccessAlert.value = true;
  successMessage.value = message;
  setTimeout(() => { showSuccessAlert.value = false; }, 4000);
}

function showError(message: string) {
  errorMessage.value = message;
  showErrorAlert.value = true;
  setTimeout(() => { showErrorAlert.value = false; }, 4000);
}

function updateMentions() {
  backendApi.getMentions(props.video.id)
    .then(({ data }: any) => { mentions.value = data; })
    .catch((e: any) => { console.error(e); });
}

function deleteMention(channelId: string) {
  backendApi.deleteMentions(props.video.id, [channelId], appStore.userdata.jwt)
    .then(({ data }: any) => {
      if (!data) return;
      showSuccess("Successfully deleted mention");
      updateMentions();
    })
    .catch((e: any) => { showError((e.response?.data?.message) || e.message || "Error occured"); });
}

function addMention(channelId: string) {
  isLoading.value = true;
  backendApi.addMention(props.video.id, channelId, appStore.userdata.jwt)
    .then(({ data }: any) => {
      if (!data) return;
      showSuccess(`Added channel: ${getChannelName(selectedChannel.value)}`);
      updateMentions();
    })
    .catch((e: any) => { showError((e.response?.data?.message) || e.message || "Error occured"); });
}

onMounted(() => { updateMentions(); });
</script>

<style></style>
