// src/components/setting/AboutSection.tsx
"use client";

import { useTranslations } from "next-intl";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/api";
import {
  Bookmark,
  DiscordIcon,
  ExternalLink,
  GithubIcon,
  MoreVertical,
  Puzzle,
  Share,
  TwitterIcon,
} from "@/lib/icons";

const socialLinkClass = "h-auto w-full justify-start whitespace-normal font-normal";

function SocialLink({ item }: { item: any }) {
  return (
    <Button
      nativeButton={false}
      render={<a href={item.href} target="_blank" rel="noopener noreferrer" />}
      variant="outline"
      className={socialLinkClass}
    >
      <item.icon className="size-4" />
      <span className="truncate">{item.title}</span>
      <span className="truncate text-muted-foreground">{item.label}</span>
    </Button>
  );
}

function TwitterFeed() {
  const t = useTranslations();
  const [metrics, setMetrics] = useState<any>(null);
  const elRef = useRef<HTMLDivElement | null>(null);
  const s = metrics?.statistics ?? null;
  const links = useMemo(
    () => [
      {
        title: "X",
        label: "@holodex",
        bucket: "top",
        href: "https://x.com/holodex",
        icon: TwitterIcon,
      },
      {
        title: "Discord",
        label: t("about.links.community"),
        bucket: "top",
        href: "https://discord.gg/jctkgHBt4b",
        icon: DiscordIcon,
      },
      {
        title: "GitHub",
        label: t("about.links.repository"),
        bucket: "top",
        href: "https://github.com/RiceCakess/Holodex",
        icon: GithubIcon,
      },
      {
        title: t("about.links.docs"),
        label: "HoloAPI V2",
        bucket: "top",
        href: "https://docs.holodex.net/",
        icon: ExternalLink,
      },
      {
        title: t("about.links.extension"),
        label: t("about.links.browserAddon"),
        bucket: "bottom",
        href: "https://holodex.net/extension",
        icon: Puzzle,
      },
    ],
    [t],
  );
  const statCards = useMemo(() => {
    if (!s) return [];
    return [
      {
        label: t("about.stats.vtubers"),
        value: s.channelCount.vtuber || 0,
        delta: t("about.stats.lastMonth", { count: s.monthlyChannels.vtuber || 0 }),
      },
      {
        label: t("about.stats.subbers"),
        value: s.channelCount.subber || 0,
        delta: t("about.stats.lastMonth", { count: s.monthlyChannels.subber || 0 }),
      },
      {
        label: t("about.stats.videos"),
        value: s.totalVideos.count || 0,
        delta: t("about.stats.yesterday", { count: s.dailyVideos.count || 0 }),
      },
      { label: t("about.stats.songs"), value: s.totalSongs.count || 0, delta: " " },
    ];
  }, [s, t]);
  useEffect(() => {
    api
      .stats()
      .then(({ data }) => setMetrics(data))
      .catch(() => {});
  }, []);
  useEffect(() => {
    if (!metrics) return;
    const handles: number[] = [];
    (elRef.current?.querySelectorAll<HTMLElement>("[data-stat-value]") ?? []).forEach((el) => {
      const target = +(el.getAttribute("data-value") || 0);
      const step = Math.max(target / 200, 1);
      const tick = () => {
        const curr = +(el.innerText || 0);
        if (curr < target) {
          el.innerText = `${Math.ceil(curr + step)}`;
          handles.push(requestAnimationFrame(tick));
        } else el.innerText = `${target}`;
      };
      tick();
    });
    return () => handles.forEach(cancelAnimationFrame);
  }, [metrics]);

  return (
    <div ref={elRef} className="space-y-4 p-5">
      {s ? (
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
          {statCards.map((item) => (
            <Card key={item.label} role="article" size="sm">
              <div className="text-2xl font-normal" data-stat-value data-value={item.value}>
                0
              </div>
              <div className="text-xs font-medium text-muted-foreground">{item.label}</div>
              <div className="text-xs text-muted-foreground">{item.delta}</div>
            </Card>
          ))}
        </div>
      ) : null}
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
        {links
          .filter((l) => l.bucket === "top")
          .map((item) => (
            <SocialLink key={item.title} item={item} />
          ))}
      </div>
      <div className="grid gap-2 min-[1100px]:grid-cols-2">
        <div className="grid gap-2">
          {links
            .filter((l) => l.bucket === "bottom")
            .map((item) => (
              <SocialLink key={item.title} item={item} />
            ))}
        </div>
        <Button
          nativeButton={false}
          render={
            // biome-ignore lint/security/noScriptUrl: bookmarklet the user drags to their bookmarks bar, so the javascript: URL is the feature, not a navigation target.
            <a href="javascript:(function(){var v=new%20URLSearchParams(window.location.search).get('v');v&&(window.location.href='https://holodex.net/watch/'+v)})()" />
          }
          variant="outline"
          className={socialLinkClass}
        >
          <Bookmark className="size-4" />
          <span>{t("about.bookmarklet.title")}</span>
          <span className="text-muted-foreground">{t("about.bookmarklet.openYoutube")}</span>
        </Button>
      </div>
    </div>
  );
}

export function AboutSection() {
  const t = useTranslations();
  return (
    <div id="about" className="space-y-6">
      <TwitterFeed />
      <section className="px-5">
        <h3 className="text-lg leading-7 text-foreground">{t("about.credits.title")}</h3>
        <div className="about-credits mt-4 space-y-4 text-sm leading-6 text-muted-foreground">
          <p>
            {t("about.credits.contents.0")}{" "}
            <a
              className="font-medium text-primary underline underline-offset-4 transition-opacity hover:opacity-90"
              href="https://hololive.jetri.co/"
            >
              HoloTools
            </a>{" "}
            {t("about.credits.contents.1")}{" "}
            <a
              className="font-medium text-primary underline underline-offset-4 transition-opacity hover:opacity-90"
              href="https://github.com/holofans/holoapi"
            >
              holoapi
            </a>
            .<br />
            {t("about.credits.contents.2")}
          </p>
          <p>
            {t("about.credits.contents.3")}{" "}
            <a
              className="font-medium text-primary underline underline-offset-4 transition-opacity hover:opacity-90"
              href="https://en.hololive.tv/terms"
              target="_blank"
              rel="noopener noreferrer"
            >
              {t("about.credits.contents.4")}
            </a>
          </p>
          <p>
            {t("about.youtubeTerms.before")}{" "}
            <a
              className="font-medium text-primary underline underline-offset-4 transition-opacity hover:opacity-90"
              href="https://www.youtube.com/t/terms"
            >
              {t("about.youtubeTerms.link")}
            </a>
            {t("about.youtubeTerms.after")}
          </p>
        </div>
      </section>
      <section className="px-5">
        <h3 className="text-lg leading-7 text-foreground">{t("about.faq.title")}</h3>
        <div className="mt-4">
          <Accordion multiple>
            <Faq title={t("about.faq.ytchatHeader")}>
              {t("about.faq.ytchatContent")}
              <br />
              <a
                className="text-primary underline underline-offset-4"
                href="https://support.mozilla.org/en-US/kb/third-party-cookies-firefox-tracking-protection?redirectslug=disable-third-party-cookies"
              >
                {t("about.faq.ytchatFirefox")}
              </a>
            </Faq>
            <Faq title={t("about.faq.autoplayHeader")}>
              <div className="space-y-4">
                <p>{t("about.faq.autoplayContent")}</p>
                <div className="space-y-4">
                  <div>
                    <div className="mb-2 text-sm font-normal text-foreground">Safari</div>
                    <img
                      width="80%"
                      src="https://www.imore.com/sites/imore.com/files/styles/large/public/field/image/2017/07/safari-custom-settings-websites-mac-screenshot-06.jpg?itok=ONVYTcno"
                      alt=""
                    />
                  </div>
                  <div>
                    <div className="mb-2 text-sm font-normal text-foreground">Firefox</div>
                    <img
                      width="80%"
                      src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/firefox/files/2019/04/Screen-Shot-2019-04-01-at-11.21.21-AM.png"
                      alt=""
                    />
                  </div>
                </div>
              </div>
            </Faq>
            <Faq title={t("about.faq.mobile.title")}>
              <p>{t("about.faq.mobile.content.summary")}</p>
              <ul className="mt-3 space-y-2 pl-5">
                <li>
                  {t("about.faq.mobile.content.android.0")} <MoreVertical className="size-4 mx-1" />{" "}
                  {t("about.faq.mobile.content.android.1")}
                </li>
                <li>
                  {t("about.faq.mobile.content.ios.0")} <Share className="size-4 mx-1" />{" "}
                  {t("about.faq.mobile.content.ios.1")}
                </li>
              </ul>
            </Faq>
            <Faq title={t("about.faq.favorite.disappear.title")}>
              {t("about.faq.favorite.contents.0")}
            </Faq>
            <Faq title={t("about.faq.subber.title")}>
              {t("about.faq.subber.contents.0")}{" "}
              <a
                className="text-primary underline underline-offset-4"
                href="https://forms.gle/xkN4w8fyPr6YTGfx6"
              >
                {t("about.faq.subber.contents.1")}
              </a>{" "}
              {t("about.faq.subber.contents.2")}
            </Faq>
            <Faq title={t("about.faq.videoLinkage")}>{t("about.faq.videoLinkageContent")}</Faq>
            <Faq title={t("about.faq.quitHolodex")}>{t("about.faq.quitHolodexContent")}</Faq>
            <Faq title={t("about.faq.feedback.title")}>{t("about.faq.feedback.contents.0")}</Faq>
            <Faq title={t("about.faq.support.title")}>
              <div dangerouslySetInnerHTML={{ __html: t.raw("about.faq.support.contents.0") }} />
            </Faq>
            <Faq title={t("about.privacyPolicy")}>
              <PrivacyPolicy />
            </Faq>
            <Faq title={t("about.gdpr")}>
              {t("about.gdprContent")}{" "}
              <span className="font-normal text-foreground">{t("about.gdprDeletion")}</span>
            </Faq>
          </Accordion>
        </div>
      </section>
    </div>
  );
}

function Faq({ title, children }: { title: React.ReactNode; children: React.ReactNode }) {
  return (
    <AccordionItem value={String(title)}>
      <AccordionTrigger>{title}</AccordionTrigger>
      <AccordionContent className="text-sm leading-6 text-muted-foreground [&_a]:font-medium [&_a]:text-primary [&_a]:underline [&_a]:underline-offset-4">
        {children}
      </AccordionContent>
    </AccordionItem>
  );
}

function PrivacyPolicy() {
  const t = useTranslations();
  return (
    <div className="space-y-4">
      <p>{t("about.privacy.content.intro")}</p>
      <div>
        <h4 className="text-base font-normal text-foreground">
          {t("about.privacy.firstParty.title")}
        </h4>
        <p className="mt-2">{t("about.privacy.firstParty.collection")}</p>
        <p className="mt-2">{t("about.privacy.firstParty.voluntary")}</p>
        <p className="mt-2">{t("about.privacy.firstParty.access")}</p>
        <p className="mt-2">{t("about.privacy.firstParty.limitedUse")}</p>
        <p className="mt-2">{t("about.privacy.firstParty.noPosting")}</p>
        <p className="mt-2">{t("about.privacy.firstParty.revoking")}</p>
        <p className="mt-2">{t("about.privacy.firstParty.changes")}</p>
      </div>
      <div>
        <h4 className="text-base font-normal text-foreground">
          {t("about.privacy.thirdParty.title")}
        </h4>
        <h5 className="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-foreground">
          {t("about.privacy.thirdParty.analyticsTitle")}
        </h5>
        <p className="mt-2">{t("about.privacy.thirdParty.analyticsBody")}</p>
        <p className="mt-2">{t("about.privacy.thirdParty.analyticsUse")}</p>
        <h5 className="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-foreground">
          {t("about.privacy.thirdParty.embedsTitle")}
        </h5>
        <p className="mt-2">{t("about.privacy.thirdParty.embedsBody")}</p>
        <p className="mt-2">{t("about.privacy.thirdParty.linksIntro")}</p>
        <h5 className="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-foreground">
          {t("about.privacy.thirdParty.choicesTitle")}
        </h5>
        <p className="mt-2">{t("about.privacy.thirdParty.choicesBody")}</p>
        <h5 className="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-foreground">
          {t("about.privacy.thirdParty.contactTitle")}
        </h5>
        <p className="mt-2">{t("about.privacy.thirdParty.contactBody")}</p>
        <p className="mt-2">{t("about.privacy.thirdParty.commitment")}</p>
        <div className="space-y-2">
          <a
            className="block text-primary underline underline-offset-4"
            href="https://policies.google.com/privacy"
          >
            {t("about.privacy.links.google")}
          </a>
          <a
            className="block text-primary underline underline-offset-4"
            href="https://www.twitch.tv/p/en/legal/privacy-notice/"
          >
            {t("about.privacy.links.twitch")}
          </a>
        </div>
      </div>
    </div>
  );
}

// src/components/setting/AboutSection.vue
<template>
  <UiCard id="about" class-name="space-y-6 border-[color:var(--color-border)] p-6">
    <header>
      <h2 class="text-3xl font-semibold tracking-tight text-[color:var(--color-foreground)]">
        {{ t("component.mainNav.about") }}
      </h2>
    </header>

    <div class="grid gap-6">
      <UiCard class-name="overflow-hidden p-0">
        <TwitterFeed :key="'twtrTimeline' + timelinekey" :show-header="false" />
      </UiCard>
    </div>

    <UiCard class-name="p-6">
      <h3 class="text-lg font-semibold text-[color:var(--color-foreground)]">
        {{ t("about.credits.title") }}
      </h3>
      <div class="about-credits mt-4 space-y-4 text-sm leading-6 text-[color:var(--color-muted-foreground)]">
        <p>
          {{ t("about.credits.contents[0]") }}
          <a
            class="font-medium text-[color:var(--color-primary)] underline underline-offset-4 transition-opacity hover:opacity-90"
            href="https://hololive.jetri.co/"
          >HoloTools</a>
          {{ t("about.credits.contents[1]") }}
          <a
            class="font-medium text-[color:var(--color-primary)] underline underline-offset-4 transition-opacity hover:opacity-90"
            href="https://github.com/holofans/holoapi"
          >holoapi</a>.
          <br>
          {{ t("about.credits.contents[2]") }}
        </p>
        <p>
          {{ t("about.credits.contents[3]") }}
          <a
            class="font-medium text-[color:var(--color-primary)] underline underline-offset-4 transition-opacity hover:opacity-90"
            href="https://en.hololive.tv/terms"
            target="_blank"
            rel="noopener noreferrer"
          >
            {{ t("about.credits.contents[4]") }}
          </a>
        </p>
        <p>
          By using this site you are agreeing to be bound by the
          <a
            class="font-medium text-[color:var(--color-primary)] underline underline-offset-4 transition-opacity hover:opacity-90"
            href="https://www.youtube.com/t/terms"
          >Youtube Terms of Service</a>.
        </p>
      </div>
    </UiCard>

    <div class="grid gap-6">
      <UiCard class-name="p-6">
        <h3 class="text-lg font-semibold text-[color:var(--color-foreground)]">
          {{ t("about.faq.title") }}
        </h3>
        <div class="mt-4 faq-list">
          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.ytchatHeader") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              {{ t("about.faq.ytchatContent") }}
              <br>
              <a
                class="text-sky-300 hover:text-sky-200"
                href="https://support.mozilla.org/en-US/kb/third-party-cookies-firefox-tracking-protection?redirectslug=disable-third-party-cookies"
              >
                {{ t("about.faq.ytchatFirefox") }}
              </a>
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.autoplayHeader") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content space-y-4">
              <p>{{ t("about.faq.autoplayContent") }}</p>
              <div class="space-y-4">
                <div>
                  <div class="mb-2 text-sm font-normal text-[color:var(--color-foreground)]">
                    Safari
                  </div>
                  <img
                    width="80%"
                    src="https://www.imore.com/sites/imore.com/files/styles/large/public/field/image/2017/07/safari-custom-settings-websites-mac-screenshot-06.jpg?itok=ONVYTcno"
                  >
                </div>
                <div>
                  <div class="mb-2 text-sm font-normal text-[color:var(--color-foreground)]">
                    Firefox
                  </div>
                  <img
                    width="80%"
                    src="https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/firefox/files/2019/04/Screen-Shot-2019-04-01-at-11.21.21-AM.png"
                  >
                </div>
              </div>
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.mobile.title") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              <p>{{ t("about.faq.mobile.content.summary") }}</p>
              <ul class="mt-3 space-y-2 pl-5">
                <li>
                  {{ t("about.faq.mobile.content.android.0") }}
                  <UiIcon :icon="mdiDotsVertical" size="sm" class-name="mx-1 text-sky-300" />
                  {{ t("about.faq.mobile.content.android.1") }}
                </li>
                <li>
                  {{ t("about.faq.mobile.content.ios.0") }}
                  <UiIcon :icon="mdiExportVariant" size="sm" class-name="mx-1 text-sky-300" />
                  {{ t("about.faq.mobile.content.ios[1]") }}
                </li>
              </ul>
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.favorite.disappear.title") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              {{ t("about.faq.favorite.contents.0") }}
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.subber.title") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              {{ t("about.faq.subber.contents.0") }}
              <a class="text-sky-300 hover:text-sky-200" href="https://forms.gle/xkN4w8fyPr6YTGfx6">
                {{ t("about.faq.subber.contents.1") }}
              </a>
              {{ t("about.faq.subber.contents.2") }}
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.videoLinkage") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              {{ t("about.faq.videoLinkageContent") }}
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.quitHolodex") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              {{ t("about.faq.quitHolodexContent") }}
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.feedback.title") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              {{ t("about.faq.feedback.contents.0") }}
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.faq.support.title") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              <div v-html="t('about.faq.support.contents.0')" />
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.privacyPolicy") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content space-y-4">
              <p>
                This Privacy Policy governs the manner in which Holodex collects, uses, maintains, and discloses information collected from users (each, a "User") of the Holodex website ("Site"). This privacy policy applies to the Site and all products and services offered by Holodex.
              </p>

              <div>
                <h4 class="text-base font-normal text-[color:var(--color-foreground)]">
                  Holodex First Party Information collection and usage:
                </h4>
                <p class="mt-2">
                  We collect limited personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our Site, register on the Site, fill out a form, and in connection with other activities, services, features or resources we make available on our Site.
                </p>
                <p class="mt-2">
                  We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personal identification information and use the Site without logging in.
                </p>
                <p class="mt-2">
                  i) Information Access: When you log in using your social media account, we will only access the basic information required to facilitate your login. This typically includes your email address or social media handle. We will not retrieve or store any other personal data from your social media account. We will also store the minimum amount of ID or email handle used to distinctly link a Holodex account with a Social Media Account so we may facilitate future logins.
                </p>
                <p class="mt-2">
                  ii) Limited Use: The information obtained from your social media account is solely for the purpose of allowing you to log into our service. We will not use this information for identification purposes outside of this function or share it with third parties without your explicit consent.
                </p>
                <p class="mt-2">
                  iii) No Posting: We will not post any content to your social media accounts on your behalf or access your contacts, friends, or followers.
                </p>
                <p class="mt-2">
                  iv) Revoking Access: You can revoke our access to your social media account at any time through your social media platform's settings. Revoking our access will not affect your account with us, but you may need to set up an alternative login method for our service.
                </p>
                <p class="mt-2">
                  Changes to This Clause: Any changes to our social media login policy will be updated on this page. We recommend that you periodically review this clause for any changes.
                </p>
              </div>

              <div>
                <h4 class="text-base font-normal text-white">
                  Third Party Information collection and usage:
                </h4>
                <h5 class="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-[color:var(--color-foreground)]">
                  1. Google Analytics
                </h5>
                <p class="mt-2">
                  We use Google Analytics, a service provided by Google, Inc., to analyze our website traffic. Google Analytics utilizes cookies to track visitor interactions and collects information about how visitors use our site. This data might include your IP address, browser type, browser version, the pages of our site that you visit, the time and date of your visit, the time spent on those pages, and other statistics.
                </p>
                <p class="mt-2">
                  The data collected is primarily used to report on website usage to help us understand our visitors' preferences and to enhance the user experience. Please refer to Google's privacy policy.
                </p>

                <h5 class="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-[color:var(--color-foreground)]">
                  2. YouTube & Twitch Embeds
                </h5>
                <p class="mt-2">
                  Our website may feature embedded videos from YouTube (owned by Google, Inc.) or Twitch (owned by Twitch Interactive, Inc.). When you watch these videos, these platforms may set cookies on your device and collect data such as your IP address, your browser type, and the page you visited on our site.
                </p>
                <p class="mt-2">
                  We've added links below to their respective privacy policies.
                </p>

                <h5 class="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-[color:var(--color-foreground)]">
                  Your Choices
                </h5>
                <p class="mt-2">
                  You can control and limit the data that third-party services collect by using the respective settings in your browser or device and by consulting the privacy settings specific to each third-party service.
                </p>

                <h5 class="mt-3 text-sm font-normal uppercase tracking-[0.18em] text-[color:var(--color-foreground)]">
                  Contact Us about Privacy
                </h5>
                <p class="mt-2">
                  If you have concerns about the data these third parties collect or wish to find out more about your data protection rights, we encourage you to visit their respective privacy policies.
                </p>
                <p class="mt-2">
                  Your privacy is of paramount importance to us, and we are committed to ensuring the best standards are upheld. If you have any questions or concerns regarding our use of social media logins, please contact our team on discord.
                </p>
                <div class="space-y-2">
                  <a class="block text-sky-300 hover:text-sky-200" href="https://policies.google.com/privacy">Google and Youtube Privacy Policy</a>
                  <a class="block text-sky-300 hover:text-sky-200" href="https://www.twitch.tv/p/en/legal/privacy-notice/">Twitch Privacy Policy</a>
                </div>
              </div>
            </div>
          </details>

          <details class="faq-item">
            <summary class="faq-trigger">
              <span>{{ t("about.gdpr") }}</span>
              <UiIcon :icon="mdiChevronDown" size="sm" class-name="faq-chevron" />
            </summary>
            <div class="faq-content">
              {{ t("about.gdprContent") }}
              <span class="font-normal text-[color:var(--color-foreground)]">{{ t("about.gdprDeletion") }}</span>
            </div>
          </details>
        </div>
      </UiCard>
    </div>
  </UiCard>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useI18n } from "vue-i18n";
import {
  mdiChevronDown,
  mdiExportVariant,
  mdiDotsVertical,
} from "@mdi/js";
import UiCard from "@/components/ui/card/Card.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import TwitterFeed from "@/components/common/TwitterFeed.vue";

const { t } = useI18n();
const timelinekey = ref(12);

// Note: `activated` hook is not available in `<script setup>`.
// If this component is used within <KeepAlive>, use onActivated:
import { onActivated } from "vue";
onActivated(() => {
  timelinekey.value += 1;
});
</script>

<style scoped>
.faq-list {
  display: grid;
  gap: 0.65rem;
}

.about-credits a {
  text-decoration: underline !important;
  text-underline-offset: 4px;
  text-decoration-thickness: 1px;
}

.faq-content :deep(a) {
  color: var(--color-primary);
  text-decoration: underline !important;
  text-underline-offset: 4px;
  text-decoration-thickness: 1px;
}

.faq-item {
  border: 1px solid var(--color-border);
  border-radius: calc(var(--radius) + 2px);
  background: color-mix(in srgb, var(--surface-soft) 90%, transparent);
  overflow: hidden;
  transition: border-color 160ms ease;
}

.faq-item:hover {
  border-color: var(--color-bold);
}

.faq-trigger {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.85rem;
  cursor: pointer;
  list-style: none;
  padding: 0.95rem 1rem;
  color: var(--color-foreground);
  font-size: 0.92rem;
  font-weight: 400;
  line-height: 1.35;
}

.faq-trigger::-webkit-details-marker {
  display: none;
}

.faq-chevron {
  flex-shrink: 0;
  color: var(--color-muted-foreground);
  transition: transform 180ms ease, color 180ms ease;
}

.faq-item[open] .faq-chevron {
  transform: rotate(180deg);
  color: var(--color-foreground);
}

.faq-content {
  border-top: 1px solid var(--color-border);
  padding: 0.85rem 1rem 1rem;
  color: var(--color-muted-foreground);
  line-height: 1.6;
}

</style>
