// src/components/channel/ChannelChip.tsx
"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { HoverCard, HoverCardContent, HoverCardTrigger } from "@/components/ui/hover-card";

import { ChannelSocials } from "@/components/channel/ChannelSocials";
import { getChannelPhoto } from "@/lib/functions";
import { channelDisplayName } from "@/lib/video-format";
import { useAppState } from "@/lib/store";
import * as icons from "@/lib/icons";

export function ChannelChip({
  channel,
  size = 60,
  closeDelay = 250,
  children,
}: {
  channel: Record<string, any>;
  size?: number;
  closeDelay?: number;
  children?: (ctx: { isHover: boolean }) => React.ReactNode;
}) {
  const app = useAppState();
  const [open, setOpen] = useState(false);
  const channelName = channelDisplayName(channel, app.settings.useEnglishName);
  const photo = useMemo(() => getChannelPhoto(channel?.id), [channel?.id]);

  function toggleHover() {
    if (app.isMobile) setOpen((value) => !value);
  }

  return (
    <HoverCard open={open} onOpenChange={setOpen}>
      <div
        className="relative mr-1 overflow-hidden rounded-full"
        style={{ width: `${size}px`, height: `${size}px` }}
      >
        <HoverCardTrigger
          delay={0}
          closeDelay={closeDelay}
          render={
            <Button
              type="button"
              variant="ghost"
              className="h-full w-full rounded-full p-0 hover:bg-transparent"
              onClick={toggleHover}
            />
          }
        >
          <img src={photo} alt={`${channel.name}'s profile picture`} width={size} height={size} decoding="async" className="h-full w-full object-cover" />
        </HoverCardTrigger>
        {children ? children({ isHover: open }) : open ? (
          <div className="pointer-events-none absolute inset-0 flex items-center justify-center bg-slate-950/70">
            <Button nativeButton={false}
              render={<Link href={`/channel/${channel.id}`} />}
              size="icon"
              variant="ghost"
              className="pointer-events-auto"
            >
              <icons.LogIn className="size-5" />
            </Button>
          </div>
        ) : null}
      </div>
      <HoverCardContent align="center" sideOffset={8} className="z-[80] flex max-h-12 w-auto flex-row items-baseline gap-2 overflow-hidden border border-white/10 px-2 py-2">
        <ChannelSocials channel={channel} vertical hideYt hideTwitter />
        <span className="ml-2 text-sm text-slate-300">{channelName}</span>
      </HoverCardContent>
    </HoverCard>
  );
}

// src/components/channel/ChannelChip.vue
<template>
  <div
    ref="root"
    class="relative mr-1"
    @mouseenter="handleEnter"
    @mouseleave="handleLeave"
  >
    <button
      type="button"
      class="relative overflow-hidden rounded-full"
      :style="{ width: `${size}px`, height: `${size}px` }"
      @click="toggleHover"
    >
      <img
        :src="photo"
        crossorigin="anonymous"
        :alt="`${channel.name}'s profile picture`"
        :width="size"
        :height="size"
        class="h-full w-full object-cover"
      >
      <slot :is-hover="isHover">
        <div
          v-if="isHover"
          class="absolute inset-0 flex items-center justify-center bg-slate-950/70"
        >
          <UiButton
            as="router-link"
            size="icon"
            variant="ghost"
            :to="`/channel/${channel.id}`"
          >
            <UiIcon :icon="icons.mdiLoginVariant" />
          </UiButton>
        </div>
      </slot>
    </button>

    <UiCard
      v-if="isHover"
      class-name="channel-hover-tooltip absolute left-1/2 top-full z-[80] mt-2 flex -translate-x-1/2 flex-row items-baseline gap-2 border border-white/10 px-2 py-2"
    >
      <ChannelSocials
        :channel="channel"
        vertical
        hide-yt
        hide-twitter
      />
      <span class="ml-2 text-sm text-slate-300">{{ channelName }}</span>
    </UiCard>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onBeforeUnmount } from "vue";
import { getChannelPhoto, resizeChannelPhoto } from "@/utils/functions";
import * as icons from "@/utils/icons";
import { useAppStore } from "@/stores/app";
import { useSettingsStore } from "@/stores/settings";
import UiButton from "@/components/ui/button/Button.vue";
import UiCard from "@/components/ui/card/Card.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import ChannelSocials from "@/components/channel/ChannelSocials.vue";

const props = withDefaults(defineProps<{
  channel: Record<string, any>;
  size?: number;
  closeDelay?: number;
}>(), {
  size: 60,
  closeDelay: 250,
});

const appStore = useAppStore();
const settingsStore = useSettingsStore();

const isHover = ref(false);
let closeTimer: ReturnType<typeof setTimeout> | null = null;

const channelName = computed(() => {
  const prop = settingsStore.nameProperty;
  if (props.channel[prop]) return props.channel[prop];
  return props.channel.name;
});

const photo = computed(() => {
  return getChannelPhoto(props.channel?.id);
});

function handleEnter() {
  if (closeTimer) clearTimeout(closeTimer);
  if (!appStore.isMobile) isHover.value = true;
}

function handleLeave() {
  if (appStore.isMobile) return;
  closeTimer = setTimeout(() => {
    isHover.value = false;
  }, props.closeDelay);
}

function toggleHover() {
  if (appStore.isMobile) {
    isHover.value = !isHover.value;
  }
}

onBeforeUnmount(() => {
  if (closeTimer) clearTimeout(closeTimer);
});
</script>

<style>
.channel-hover-tooltip {
  max-height: 48px;
  overflow: hidden;
}
</style>
