// src/components/channel/ChannelSocials.tsx
"use client";

import { mdiAccountCancel, mdiHeartOutline, mdiTwitch } from "@mdi/js";
import { Button } from "@/components/ui/Button";
import { Icon } from "@/components/ui/Icon";
import { useAppState } from "@/lib/store";
import { useI18n } from "@/lib/i18n";
import * as icons from "@/lib/icons";
import { cn } from "@/lib/cn";

export function ChannelSocials({
  channel,
  vertical = false,
  hideYt = false,
  hideTwitter = false,
  hideTwitch = false,
  hideFav = false,
  showDelete = false,
  className = "",
}: {
  channel: Record<string, any>;
  vertical?: boolean;
  hideYt?: boolean;
  hideTwitter?: boolean;
  hideTwitch?: boolean;
  hideFav?: boolean;
  showDelete?: boolean;
  className?: string;
}) {
  const app = useAppState();
  const { t } = useI18n();
  const isBlocked = app.blockedChannelIDs.has(channel?.id);
  const isFavorited = app.isFavorited(channel?.id);
  const tooltip = !app.isLoggedIn
    ? t("component.channelList.signInToFavorite")
    : !isFavorited
      ? t("component.channelSocials.addToFavorites")
      : t("component.channelSocials.removeFromFavorites");
  const blockTooltip = !isBlocked
    ? t("component.channelSocials.block")
    : t("component.channelSocials.unblock");
  function toggleFavorite(event: React.MouseEvent) {
    event.preventDefault();
    if (!app.isLoggedIn) return;
    app.toggleFavorite(channel.id);
  }
  function toggleBlocked() {
    const blocked = app.settings.blockedChannels || [];
    if (isBlocked)
      app.patchSettings({
        blockedChannels: blocked.filter((x: any) => x.id !== channel.id),
      } as any);
    else app.patchSettings({ blockedChannels: [...blocked, channel] } as any);
  }
  return (
    <div
      className={cn(
        "flex gap-2",
        vertical
          ? "flex-col items-start"
          : "channel-social-horizontal items-center",
        className,
      )}
      onClick={(e) => e.stopPropagation()}
    >
      {channel?.id && !hideYt ? (
        <Button
          as="a"
          variant="ghost"
          size="icon"
          href={`https://www.youtube.com/channel/${channel.id}`}
          rel="noreferrer"
          target="_blank"
          title="YouTube"
        >
          <Icon icon={icons.mdiYoutube} className="text-red-500" />
        </Button>
      ) : null}
      {channel?.twitter && !hideTwitter ? (
        <Button
          as="a"
          variant="ghost"
          size="icon"
          href={`https://twitter.com/${channel.twitter}`}
          rel="noreferrer"
          target="_blank"
          title="Twitter"
        >
          <Icon icon={icons.mdiTwitter} className="text-sky-400" />
        </Button>
      ) : null}
      {channel?.twitch && !hideTwitch ? (
        <Button
          as="a"
          variant="ghost"
          size="icon"
          href={`https://twitch.tv/${channel.twitch}`}
          rel="noreferrer"
          target="_blank"
          title="Twitch"
        >
          <Icon icon={mdiTwitch} className="text-violet-400" />
        </Button>
      ) : null}
      {channel?.type === "vtuber" && !hideFav ? (
        <Button
          type="button"
          variant="ghost"
          size="icon"
          title={tooltip}
          onClick={toggleFavorite}
        >
          <Icon
            icon={isFavorited ? icons.mdiHeart : mdiHeartOutline}
            className={
              isFavorited && app.isLoggedIn ? "text-rose-400" : "text-slate-500"
            }
          />
        </Button>
      ) : null}
      {showDelete ? (
        <Button
          type="button"
          variant={isBlocked ? "destructive" : "ghost"}
          size="sm"
          title={blockTooltip}
          onClick={(e: any) => {
            e.preventDefault();
            e.stopPropagation();
            toggleBlocked();
          }}
        >
          <Icon icon={mdiAccountCancel} />
          {isBlocked ? (
            <span>{t("component.channelSocials.blocked")}</span>
          ) : null}
        </Button>
      ) : null}
    </div>
  );
}

// src/components/channel/ChannelSocials.vue
<template>
  <div
    class="flex gap-2"
    :class="vertical ? 'flex-col items-start' : 'channel-social-horizontal items-center'"
    @click.stop=""
  >
    <UiButton
      v-if="channel.id && !hideYt"
      as="a"
      variant="ghost"
      size="icon"
      :href="`https://www.youtube.com/channel/${channel.id}`"
      rel="noreferrer"
      target="_blank"
      title="YouTube"
    >
      <UiIcon :icon="icons.mdiYoutube" class-name="text-red-500" />
    </UiButton>
    <UiButton
      v-if="channel.twitter && !hideTwitter"
      as="a"
      variant="ghost"
      size="icon"
      :href="`https://twitter.com/${channel.twitter}`"
      rel="noreferrer"
      target="_blank"
      title="Twitter"
    >
      <UiIcon :icon="icons.mdiTwitter" class-name="text-sky-400" />
    </UiButton>
    <UiButton
      v-if="channel.twitch && !hideTwitch"
      as="a"
      variant="ghost"
      size="icon"
      :href="`https://twitch.tv/${channel.twitch}`"
      rel="noreferrer"
      target="_blank"
      title="Twitch"
    >
      <UiIcon :icon="mdiTwitch" class-name="text-violet-400" />
    </UiButton>
    <UiButton
      v-if="channel.type === 'vtuber' && !hideFav"
      type="button"
      variant="ghost"
      size="icon"
      :title="tooltip"
      @click.stop="toggleFavorite($event)"
    >
      <UiIcon :icon="isFavorited ? icons.mdiHeart : mdiHeartOutline" :class-name="isFavorited && isLoggedIn ? 'text-rose-400' : 'text-slate-500'" />
    </UiButton>
    <UiButton
      v-if="showDelete"
      type="button"
      :variant="isBlocked ? 'destructive' : 'ghost'"
      size="sm"
      :title="blockTooltip"
      @click.stop.prevent="toggleBlocked"
    >
      <UiIcon :icon="mdiAccountCancel" />
      <span v-if="isBlocked">{{ t("component.channelSocials.blocked") }}</span>
    </UiButton>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { mdiAccountCancel, mdiHeartOutline, mdiTwitch } from "@mdi/js";
import * as icons from "@/utils/icons";
import { useAppStore } from "@/stores/app";
import { useFavoritesStore } from "@/stores/favorites";
import { useSettingsStore } from "@/stores/settings";
import UiButton from "@/components/ui/button/Button.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";

const props = withDefaults(defineProps<{
  channel: Record<string, any>;
  vertical?: boolean;
  hideYt?: boolean;
  hideTwitter?: boolean;
  hideTwitch?: boolean;
  hideFav?: boolean;
  showDelete?: boolean;
}>(), {
  vertical: false,
  hideYt: false,
  hideTwitter: false,
  hideTwitch: false,
  hideFav: false,
  showDelete: false,
});

const { t } = useI18n();
const appStore = useAppStore();
const favoritesStore = useFavoritesStore();
const settingsStore = useSettingsStore();

const tooltip = computed(() => {
  if (!isLoggedIn.value) return t("component.channelList.signInToFavorite");
  return !isFavorited.value
    ? t("component.channelSocials.addToFavorites")
    : t("component.channelSocials.removeFromFavorites");
});

const blockTooltip = computed(() =>
  !isBlocked.value
    ? t("component.channelSocials.block")
    : t("component.channelSocials.unblock"),
);

const isBlocked = computed(() => settingsStore.blockedChannelIDs.has(props.channel.id));
const isFavorited = computed(() => favoritesStore.isFavorited(props.channel.id));
const isLoggedIn = computed(() => appStore.isLoggedIn);

function toggleFavorite(event: Event) {
  event.preventDefault();
  if (!isLoggedIn.value) return;
  favoritesStore.toggleFavorite(props.channel.id);
  favoritesStore.updateFavorites();
}

function toggleBlocked() {
  settingsStore.toggleBlocked(props.channel);
}
</script>

<style>
.channel-social-horizontal {
    margin: 0 !important;
    flex: 0 1 auto !important;
    flex-wrap: wrap;
}
</style>
