// src/components/common/ReportDialog.vue
<template>
  <div>
    <UiDialog
      :open="!!showReportDialog"
      class-name="max-w-[500px]"
      @update:open="showReportDialog = $event"
    >
      <UiCard v-if="video" class-name="border-0 p-0 shadow-none">
        <div class="space-y-4 p-5">
          <div class="text-xl font-semibold text-[color:var(--color-foreground)]">
            {{ $t("component.reportDialog.title") }}
          </div>

          <div v-if="error" class="rounded-xl border border-red-400/30 bg-red-500/15 px-3 py-2 text-sm text-red-100">
            Error Occurred
          </div>
          <div v-if="isCollab" class="rounded-xl border border-sky-400/20 bg-sky-500/15 px-3 py-2 text-sm text-sky-100">
            {{ $t("component.reportDialog.collabing", {org: appStore.currentOrg.name }) }}
          </div>

          <div class="text-sm text-[color:var(--color-foreground)]">
            <div>{{ video.title }}</div>
            <div class="text-[color:var(--color-muted-foreground)]">
              {{ video.channel.name }}
            </div>
          </div>

          <div class="space-y-2">
            <label
              v-for="reason in filteredReasons()"
              :key="reason.value"
              class="flex items-start gap-3 rounded-xl border border-white/10 bg-white/4 px-3 py-2 text-sm text-[color:var(--color-foreground)]"
            >
              <input
                v-model="selectedReasons"
                type="checkbox"
                :value="reason.value"
                class="mt-0.5 h-4 w-4 rounded border-white/20 bg-slate-950/80"
                @change="reason.value.includes('mention') && suggestedMentions === null ? loadMentions() : null"
              >
              <span>{{ reason.text }}</span>
            </label>
          </div>

          <div v-if="selectedReasons.includes('Incorrect video topic')" class="space-y-2">
            <div class="text-xs uppercase tracking-[0.18em] text-[color:var(--color-muted-foreground)]">
              {{ $t("component.search.type.topic") }}
              <span class="ml-2 text-[color:var(--color-primary)]">{{ video.topic_id || "None" }}</span>
            </div>
            <select
              v-model="suggestedTopic"
              class="w-full rounded-xl border border-white/12 bg-slate-950/70 px-3 py-2 text-sm text-[color:var(--color-foreground)] outline-none"
              @focus="loadTopics"
            >
              <option :value="false">
                Suggest new topic (leave empty to unset)
              </option>
              <option v-for="topic in topics" :key="topic.value" :value="topic.value">
                {{ topic.text }}
              </option>
            </select>
          </div>

          <div v-if="selectedReasons.includes('Incorrect channel mentions')" class="space-y-3">
            <div class="flex flex-wrap gap-2">
              <UiButton
                type="button"
                variant="outline"
                size="sm"
                @click="applyDeleteMentions()"
              >
                <UiIcon v-if="!isApplyingBulkEdit" :icon="icons.mdiContentSaveEdit" />
                <span v-else>...</span>
                Apply Changes
              </UiButton>
              <UiButton
                type="button"
                variant="ghost"
                size="sm"
                @click="toggleMentionSelection()"
              >
                <UiIcon :icon="isSelectedAll ? icons.mdiSelectOff : icons.mdiSelectAll" />
                {{ isSelectedAll ? "Deselect All" : "Select All" }}
              </UiButton>
            </div>

            <div class="flex flex-wrap gap-2">
              <ChannelChip
                v-for="item in suggestedMentions"
                :key="item.id"
                :channel="item"
                :size="60"
                :close-delay="0"
              >
                <template #default>
                  <div
                    class="absolute inset-0 flex items-center justify-center"
                    :class="isAddedToDeletionSet(item.id) ? 'bg-slate-950/70' : 'bg-transparent'"
                  >
                    <UiButton
                      v-if="isAddedToDeletionSet(item.id)"
                      type="button"
                      size="icon"
                      variant="ghost"
                      @click.stop.prevent="removeChannelFromDeletionSet(item.id)"
                    >
                      <UiIcon :icon="icons.mdiDelete" />
                    </UiButton>
                    <button
                      v-else
                      type="button"
                      class="absolute inset-0"
                      @click.stop.prevent="addChannelToDeletionSet(item.id)"
                    />
                  </div>
                </template>
              </ChannelChip>
            </div>

            <div ref="mentionRoot" class="relative">
              <UiInput
                v-model="search"
                placeholder="Adjust Mentioned Channels"
                @focus="mentionsMenuOpen = true"
              />
              <div
                v-if="mentionsMenuOpen && searchResults.length"
                class="absolute inset-x-0 top-[calc(100%+0.35rem)] z-20 overflow-hidden rounded-xl border border-white/10 bg-slate-950/96 shadow-2xl shadow-slate-950/40"
              >
                <button
                  v-for="dropdownItem in searchResults"
                  :key="dropdownItem.id"
                  type="button"
                  class="block w-full px-4 py-3 text-left text-sm text-[color:var(--color-foreground)] transition hover:bg-white/6"
                  @click.stop="addMention(dropdownItem)"
                >
                  {{ getChannelName(dropdownItem) }}
                </button>
              </div>
            </div>

            <div class="flex flex-wrap gap-2">
              <div
                v-for="selection in suggestedMentions"
                :key="`${selection.id}chip`"
                class="flex items-center gap-2 rounded-full border border-white/10 bg-white/6 px-3 py-1.5"
              >
                <ChannelChip :channel="selection" :size="40" />
                <button type="button" @click.stop.prevent="deleteMention(selection)">
                  <UiIcon :icon="icons.mdiClose" class-name="h-4 w-4 text-[color:var(--color-primary)]" />
                </button>
              </div>
            </div>
          </div>

          <div
            v-if="selectedReasons.includes('This video does not belong to the org')
              && !collabsAlreadyHidden
              && video.type !== 'clip'"
            class="space-y-2"
          >
            <div class="text-sm text-[color:var(--color-primary)]">
              {{ $t('component.reportDialog.consider') }}
            </div>
            <VideoListFilters :placeholder-filter="false" :topic-filter="false" :missing-filter="false" />
          </div>

          <div
            v-if="video.channel.id === 'UCF4-I8ZQL6Aa-iHfdz-B9KQ'"
            class="rounded-xl border border-red-400/30 bg-red-500/10 px-3 py-3 text-sm text-red-100"
          >
            <b>Note: Please don't report just because you disagree / dislike this subber.</b>
            <div v-if="readMore" class="mt-2 space-y-2">
              <p>
                Holodex platform doesn't arbitrate between sub-par and good TLs. For minor issues, you
                should feedback changes to the subber on youtube via comments, or else reporting them to
                whoever they're clipping (Cover or Nijisanji etc.).
              </p>
              <p>
                However, if the video in question is indeed dangerously translated to cause
                misunderstandings, we will definitely either delete the video or deplatform the channel,
                in addition to escalating to relevant organizations.
              </p>
              <p>
                If you'd like to not see this channel ever again, there's a
                <b>Block Channel</b> button below, and on the channel page.
              </p>
            </div>
            <button
              v-else
              type="button"
              class="mt-2 underline"
              @click.stop="readMore = true"
            >
              Read more...
            </button>
          </div>

          <div class="space-y-2">
            <label class="text-sm text-[color:var(--color-muted-foreground)]">{{ $t('component.reportDialog.comments') }}</label>
            <textarea
              v-model="comments"
              class="min-h-32 w-full rounded-xl border border-white/12 bg-white/6 px-3 py-2 text-sm text-[color:var(--color-foreground)] outline-none"
            />
            <div class="text-xs text-[color:var(--color-muted-foreground)]">
              * English / 日本語 / 繁體中文 OK
            </div>
          </div>

          <div class="h-px bg-white/10" />
          <div class="flex items-center gap-3 text-sm text-[color:var(--color-muted-foreground)]">
            <ChannelSocials
              :channel="video.channel"
              show-delete
              hide-yt
              vertical
              class="inline-block"
            />
            <UiIcon :icon="icons.mdiArrowLeft" class-name="h-4 w-4" />
            <span>{{ $t("component.channelSocials.block") }}</span>
          </div>

          <div class="flex items-center gap-3">
            <UiButton type="button" variant="ghost" @click="showReportDialog = false">
              {{ $t("views.app.close_btn") }}
            </UiButton>
            <UiButton
              type="button"
              class-name="ml-auto"
              :disabled="comments.length === 0"
              @click="sendReport"
            >
              {{ $t("views.multiview.confirmOverwriteYes") }}
            </UiButton>
          </div>
        </div>
      </UiCard>
    </UiDialog>

    <div
      v-if="showSnackbar"
      class="fixed bottom-6 right-6 z-50 rounded-xl border border-emerald-400/25 bg-emerald-500/20 px-4 py-3 text-sm text-emerald-100 shadow-xl"
    >
      <div class="flex items-center gap-3">
        <span>{{ $t("component.reportDialog.success") }}</span>
        <UiButton
          type="button"
          variant="ghost"
          size="sm"
          @click="showSnackbar = false"
        >
          {{ $t("views.app.close_btn") }}
        </UiButton>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, reactive, watch, onMounted, onBeforeUnmount } from "vue";
import { useRoute } from "vue-router";
import { useI18n } from "vue-i18n";
import backendApi from "@/utils/backend-api";
import ChannelChip from "@/components/channel/ChannelChip.vue";
import ChannelSocials from "@/components/channel/ChannelSocials.vue";
import { useFilterVideos } from "@/composables/useFilterVideos";
import debounce from "lodash-es/debounce";
import { CHANNEL_TYPES } from "@/utils/consts";
import VideoListFilters from "@/components/setting/VideoListFilters.vue";
import UiButton from "@/components/ui/button/Button.vue";
import UiCard from "@/components/ui/card/Card.vue";
import UiDialog from "@/components/ui/dialog/Dialog.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import UiInput from "@/components/ui/input/Input.vue";
import { useAppStore } from "@/stores/app";
import { useSettingsStore } from "@/stores/settings";

defineOptions({ name: "ReportDialog" });

const route = useRoute();
const { t } = useI18n();
const appStore = useAppStore();
const settingsStore = useSettingsStore();
const { filterVideos: filterVideosFn } = useFilterVideos();

const mentionRoot = ref<HTMLElement | null>(null);
const selectedReasons = ref<string[]>([]);
const comments = ref("");
const isLoading = ref(false);
const showSnackbar = ref(false);
const error = ref(false);
const readMore = ref(false);
const topics = ref<any[]>([]);
const suggestedTopic = ref<string | false>(false);
const search = ref("");
const searchResults = ref<any[]>([]);
const originalMentions = ref<any[]>([]);
const suggestedMentions = ref<any[] | null>(null);
// Using reactive Set so mutations are tracked without needing $forceUpdate
const deletionSet = reactive(new Set<string>());
const isSelectedAll = ref(false);
const isApplyingBulkEdit = ref(false);
const collabsAlreadyHidden = ref(settingsStore.hideCollabStreams);
const mentionsMenuOpen = ref(false);

const video = computed(() => appStore.reportVideo);

const currentOrg = computed(() => appStore.currentOrg);

const isCollab = computed(() =>
  !filterVideosFn(video.value, { hideCollabs: true }),
);

const showReportDialog = computed({
  get() { return appStore.reportVideo; },
  set(val: any) {
    if (!val) appStore.setReportVideo(null);
    suggestedTopic.value = false;
    suggestedMentions.value = null;
    search.value = "";
    searchResults.value = [];
    selectedReasons.value = [];
    comments.value = "";
    mentionsMenuOpen.value = false;
  },
});

const reasons = computed(() => {
  const vtype = video.value?.type === "stream" ? "video" : video.value?.type;
  return [
    { text: t("component.reportDialog.reasons[4]"), value: "Incorrect video topic", types: ["stream", "placeholder"], orgRequired: false },
    { text: t("component.reportDialog.reasons[5]"), value: "Incorrect channel mentions", types: null, orgRequired: false },
    { text: t("component.reportDialog.reasons[6]", [vtype, currentOrg.value.name]), value: "This video does not belong to the org", types: null, orgRequired: true },
    { text: t("component.reportDialog.reasons[1]"), value: "Low Quality/Misleading Content", types: ["clip"], orgRequired: false },
    { text: t("component.reportDialog.reasons[2]"), value: "Violates the org's derivative work guidelines or inappropriate", types: ["clip"], orgRequired: false },
    { text: t("component.reportDialog.reasons[3]"), value: "Other", types: null, orgRequired: false },
  ];
});

const debouncedSearch = debounce(() => {
  if (!search.value) {
    searchResults.value = [];
    return;
  }
  backendApi
    .searchChannel({ type: CHANNEL_TYPES.VTUBER, queryText: search.value })
    .then(({ data }: any) => {
      searchResults.value = data.filter(
        (d: any) => !(video.value?.channel.id === d.id || suggestedMentions.value?.find((m) => m.id === d.id)),
      );
      mentionsMenuOpen.value = true;
    });
}, 400);

watch(search, debouncedSearch);

onMounted(() => {
  document.addEventListener("click", handleOutsideClick);
});

onBeforeUnmount(() => {
  document.removeEventListener("click", handleOutsideClick);
});

function handleOutsideClick(event: MouseEvent) {
  if (!mentionRoot.value?.contains(event.target as Node)) {
    mentionsMenuOpen.value = false;
  }
}

function filteredReasons() {
  return reasons.value.filter((reason) => {
    if (reason.orgRequired && ((!currentOrg.value || currentOrg.value.name === "All Vtubers" || currentOrg.value.name === video.value?.channel.org) || route.name !== "home")) return false;
    if (reason.types && !reason.types.includes(video.value?.type)) return false;
    return true;
  });
}

function sendReport() {
  isLoading.value = true;
  const commentField = { name: "Comments", value: comments.value ? comments.value : "No comment" };
  const reasonString = selectedReasons.value.join("\n");
  const thisTopic = video.value.topic_id;
  const fieldBody: any[] = [{ name: "Reason", value: reasonString }];
  if (suggestedTopic.value !== false || reasonString.includes("topic")) {
    fieldBody.push({ name: "Original Topic", value: thisTopic ? `\`${thisTopic}\`` : "None" });
    if (thisTopic !== suggestedTopic.value) {
      fieldBody.push({ name: "Suggested Topic", value: suggestedTopic.value ? `\`${suggestedTopic.value}\`` : "None" });
    }
  }
  if (suggestedMentions.value !== null || reasonString.includes("mentions")) {
    fieldBody.push({
      name: "Original Mentions",
      value: originalMentions.value?.length > 0 ? originalMentions.value.map((m) => `\`${m.id}\``).join("\n") : "None",
    });
    if (suggestedMentions.value !== null && suggestedMentions.value !== originalMentions.value) {
      fieldBody.push({
        name: "Suggested Mentions",
        value: suggestedMentions.value?.length > 0 ? suggestedMentions.value.map((m) => `\`${m.id}\``).join("\n") : "None",
      });
    }
  }
  fieldBody.push(commentField);
  backendApi.reportVideo(video.value.id, fieldBody, appStore.userdata?.jwt)
    .then(() => {
      showReportDialog.value = false;
      showSnackbar.value = true;
      error.value = false;
    })
    .catch((e: any) => {
      console.error(e);
      error.value = true;
    })
    .finally(() => {
      isLoading.value = false;
    });
}

function getChannelName(channel: any) {
  const prop = settingsStore.nameProperty;
  return channel[prop] || channel.name;
}

function isAddedToDeletionSet(id: string) {
  return deletionSet.has(id);
}

function addChannelToDeletionSet(id: string) {
  deletionSet.add(id);
  if (deletionSet.size === suggestedMentions.value?.length) isSelectedAll.value = true;
}

function removeChannelFromDeletionSet(id: string) {
  deletionSet.delete(id);
  if (deletionSet.size === 0) isSelectedAll.value = false;
}

function toggleMentionSelection() {
  isSelectedAll.value = !isSelectedAll.value;
  if (isSelectedAll.value) {
    suggestedMentions.value?.forEach((mention) => deletionSet.add(mention.id));
  } else {
    deletionSet.clear();
  }
}

function loadMentions() {
  if (suggestedMentions.value !== null) return originalMentions.value;
  backendApi.getMentions(video.value.id).then(({ data }: any) => {
    originalMentions.value = data;
    updateMentions(data);
  }).catch((e: any) => console.error(e));
  return originalMentions.value;
}

async function loadTopics() {
  if (topics.value.length > 0) return;
  topics.value = (await backendApi.topics()).data.map((topic: any) => ({
    value: topic.id,
    text: `${topic.id} (${topic.count ?? 0})`,
  }));
}

function updateMentions(data: any[] | null = null) {
  if (data) suggestedMentions.value = data;
  searchResults.value = [];
  search.value = "";
  mentionsMenuOpen.value = false;
}

function deleteMention(channel: any) {
  removeChannelFromDeletionSet(channel.id);
  suggestedMentions.value = suggestedMentions.value!.filter((mention) => mention.id !== channel.id);
  updateMentions();
}

function addMention(channel: any) {
  if (!suggestedMentions.value!.find((mention) => mention.id === channel.id)) {
    suggestedMentions.value!.push(channel);
  }
  updateMentions();
}

function applyDeleteMentions() {
  isApplyingBulkEdit.value = true;
  const ids = Array.from(deletionSet);
  if (ids.length === 0) {
    isApplyingBulkEdit.value = false;
    return;
  }
  suggestedMentions.value = suggestedMentions.value!.filter((mention) => !ids.includes(mention.id));
  deletionSet.clear();
  isSelectedAll.value = false;
  updateMentions();
  isApplyingBulkEdit.value = false;
}
</script>

// src/components/app/ReportDialog.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import debounce from "lodash-es/debounce";
import { toast } from "sonner";
import { ALL_VTUBERS_ORG, CHANNEL_TYPES } from "@/lib/consts";
import { api } from "@/lib/api";
import { useAppState } from "@/lib/store";
import { useTranslations } from "next-intl";
import { filterVideo } from "@/lib/filter-videos";
import { ChannelChip } from "@/components/channel/ChannelChip";
import { ChannelSocials } from "@/components/channel/ChannelSocials";
import { VideoListFilters } from "@/components/setting/VideoListFilters";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Combobox, ComboboxContent, ComboboxEmpty, ComboboxInput, ComboboxItem, ComboboxList } from "@/components/ui/combobox";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { channelDisplayName } from "@/lib/video-format";
import * as icons from "@/lib/icons";

export function ReportDialog() {
  const app = useAppState();
  const t = useTranslations();
  const pathname = usePathname();
  const video = app.reportVideo;
  const [reasons, setReasons] = useState<string[]>([]);
  const [comments, setComments] = useState("");
  const [error, setError] = useState(false);
  const [readMore, setReadMore] = useState(false);
  const [topics, setTopics] = useState<any[]>([]);
  const [sugTopic, setSugTopic] = useState<string | false>(false);
  const [search, setSearch] = useState("");
  const [results, setResults] = useState<any[]>([]);
  const [origMentions, setOrigMentions] = useState<any[]>([]);
  const [sugMentions, setSugMentions] = useState<any[] | null>(null);
  const [delSet, setDelSet] = useState<Set<string>>(new Set());
  const isHome = pathname === "/";
  const isCollab = video ? !filterVideo(video, app, { forOrg: app.currentOrg.name, hideCollabs: true }) : false;
  const collabsHidden = app.settings.hideCollabStreams;
  const allSelected = !!sugMentions?.length && delSet.size === sugMentions.length;
  const { useEnglishName } = app.settings;
  const vidChId = video?.channel?.id;

  const reasonList = useMemo(() => {
    const vt = video?.type === "stream" ? "video" : video?.type;
    return [
      { text: t("component.reportDialog.reasons.4"), value: "Incorrect video topic", types: ["stream", "placeholder"], orgReq: false },
      { text: t("component.reportDialog.reasons.5"), value: "Incorrect channel mentions", types: null, orgReq: false },
      { text: t("component.reportDialog.reasons.6", { arg0: vt, arg1: app.currentOrg.name }), value: "This video does not belong to the org", types: null, orgReq: true },
      { text: t("component.reportDialog.reasons.1"), value: "Low Quality/Misleading Content", types: ["clip"], orgReq: false },
      { text: t("component.reportDialog.reasons.2"), value: "Violates the org's derivative work guidelines or inappropriate", types: ["clip"], orgReq: false },
      { text: t("component.reportDialog.reasons.3"), value: "Other", types: null, orgReq: false },
    ];
  }, [video?.type, app.currentOrg.name, t]);

  const filteredReasons = reasonList.filter((r) => {
    if (!video) return false;
    if (r.orgReq && ((!app.currentOrg || app.currentOrg.name === ALL_VTUBERS_ORG || app.currentOrg.name === video.channel?.org) || !isHome)) return false;
    if (r.types && !r.types.includes(video.type)) return false;
    return true;
  });

  const mentionOptions = useMemo(() => results.map((i) => i.id), [results]);
  const mentionById = useMemo(() => new Map(results.map((i) => [i.id, i])), [results]);
  const mentionLabels = useMemo(() => new Map(results.map((i) => [i.id, channelDisplayName(i, useEnglishName)])), [results, useEnglishName]);

  const debouncedSearch = useMemo(() => debounce((v: string) => {
    if (!v) { setResults([]); return; }
    api.searchChannel({ type: CHANNEL_TYPES.VTUBER, queryText: v }).then(({ data }: any) => {
      setResults(data.filter((d: any) => !(vidChId === d.id || sugMentions?.find((m) => m.id === d.id))));
    }).catch(console.error);
  }, 400), [vidChId, sugMentions]);

  useEffect(() => { debouncedSearch(search); return () => debouncedSearch.cancel(); }, [search, debouncedSearch]);

  function close() {
    app.setReportVideo(null);
    setSugTopic(false); setSugMentions(null); setSearch(""); setResults([]);
    setReasons([]); setComments(""); setDelSet(new Set());
  }

  function toggleReason(v: string, checked: boolean) {
    setReasons((p) => checked ? [...new Set([...p, v])] : p.filter((i) => i !== v));
    if (v.includes("mention") && sugMentions === null) loadMentions();
  }

  async function loadTopics() {
    if (topics.length) return;
    const { data } = await api.topics();
    setTopics(data.map((tp: any) => ({ value: tp.id, text: `${tp.id} (${tp.count ?? 0})` })));
  }

  function loadMentions() {
    if (!video || sugMentions !== null) return;
    api.getMentions(video.id).then(({ data }: any) => { setOrigMentions(data); setSugMentions(data); }).catch(console.error);
  }

  function deleteMention(ch: any) {
    setSugMentions((p) => (p || []).filter((m) => m.id !== ch.id));
    setDelSet((p) => { const n = new Set(p); n.delete(ch.id); return n; });
  }

  function addMention(ch: any) {
    setSugMentions((p) => p?.find((m) => m.id === ch.id) ? p : [...(p || []), ch]);
    setResults([]); setSearch("");
  }

  const addToDelSet = (id: string) => setDelSet((p) => new Set(p).add(id));
  const removeFromDelSet = (id: string) => setDelSet((p) => { const n = new Set(p); n.delete(id); return n; });
  const toggleSelectAll = () => setDelSet((p) =>
    p.size === sugMentions?.length ? new Set() : new Set((sugMentions || []).map((m) => m.id)));

  function applyDelete() {
    const ids = [...delSet];
    if (!ids.length) return;
    setSugMentions((p) => (p || []).filter((m) => !ids.includes(m.id)));
    setDelSet(new Set()); setResults([]); setSearch("");
  }

  function sendReport() {
    if (!video) return;
    const r = reasons.join("\n");
    const body: any[] = [{ name: "Reason", value: r }];
    if (sugTopic !== false || r.includes("topic")) {
      body.push({ name: "Original Topic", value: video.topic_id ? `\`${video.topic_id}\`` : "None" });
      if (video.topic_id !== sugTopic) body.push({ name: "Suggested Topic", value: sugTopic ? `\`${sugTopic}\`` : "None" });
    }
    if (sugMentions !== null || r.includes("mentions")) {
      body.push({ name: "Original Mentions", value: origMentions.length ? origMentions.map((m) => `\`${m.id}\``).join("\n") : "None" });
      if (sugMentions !== null && sugMentions !== origMentions) body.push({ name: "Suggested Mentions", value: sugMentions.length ? sugMentions.map((m) => `\`${m.id}\``).join("\n") : "None" });
    }
    body.push({ name: "Comments", value: comments || "No comment" });
    api.reportVideo(video.id, body, app.userdata?.jwt || "")
      .then(() => { close(); toast.success(t("component.reportDialog.success")); setError(false); })
      .catch((e) => { console.error(e); setError(true); });
  }

  const mentionOverlay = (item: any) => (
    <div className="absolute inset-0 flex items-center justify-center">
      {delSet.has(item.id) ? (
        <Button type="button" size="icon" variant="destructive" onClick={(e) => { e.stopPropagation(); removeFromDelSet(item.id); }}>
          <icons.Trash2 className="size-5" />
        </Button>
      ) : (
        <Button type="button" variant="ghost" className="absolute inset-0 h-full w-full rounded-full p-0" onClick={(e) => { e.stopPropagation(); addToDelSet(item.id); }} />
      )}
    </div>
  );

  return (
    <div>
      <Dialog open={!!video} onOpenChange={(o) => { if (!o) close(); }}>
        <DialogContent className="max-w-[500px]">
          {video ? (
            <div className="space-y-4">
              <DialogTitle>{t("component.reportDialog.title")}</DialogTitle>
              {error ? <Alert variant="destructive"><AlertDescription>{t("component.form.error")}</AlertDescription></Alert> : null}
              {isCollab ? <Alert><AlertDescription>{t("component.reportDialog.collabing", { org: app.currentOrg.name })}</AlertDescription></Alert> : null}
              <div className="text-sm text-foreground">
                <div>{video.title}</div>
                <div className="text-muted-foreground">{video.channel?.name}</div>
              </div>
              <div className="space-y-2">
                {filteredReasons.map((r) => (
                  <Label key={r.value} className="items-start rounded-md border p-3 text-sm">
                    <Checkbox checked={reasons.includes(r.value)} onCheckedChange={(c) => toggleReason(r.value, c === true)} />
                    <span>{r.text}</span>
                  </Label>
                ))}
              </div>
              {reasons.includes("Incorrect video topic") ? (
                <div className="space-y-2">
                  <div className="text-xs uppercase tracking-[0.18em] text-muted-foreground">
                    {t("component.search.type.topic")}
                    <span className="ml-2 text-primary">{video?.topic_id || t("component.form.none")}</span>
                  </div>
                  <Select value={sugTopic || "__unset__"} onOpenChange={(o) => { if (o) void loadTopics(); }} onValueChange={(v) => setSugTopic(v === "__unset__" ? false : v)}>
                    <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="__unset__">{t("component.reportDialog.topicUnsetPlaceholder")}</SelectItem>
                      {topics.map((tp) => <SelectItem key={tp.value} value={tp.value}>{tp.text}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
              ) : null}
              {reasons.includes("Incorrect channel mentions") ? (
                <div className="space-y-3">
                  <div className="flex flex-wrap gap-2">
                    <Button type="button" variant="outline" size="sm" onClick={applyDelete}>
                      <icons.SaveAll className="size-5" />{t("component.reportDialog.applyChanges")}
                    </Button>
                    <Button type="button" variant="ghost" size="sm" onClick={toggleSelectAll}>
                      {allSelected ? <icons.Square className="size-5" /> : <icons.CheckSquare className="size-5" />}
                      {allSelected ? t("component.reportDialog.deselectAll") : t("component.reportDialog.selectAll")}
                    </Button>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {(sugMentions || []).map((item) => (
                      <ChannelChip key={item.id} channel={item} size={60} closeDelay={0}>{() => mentionOverlay(item)}</ChannelChip>
                    ))}
                  </div>
                  <Combobox items={mentionOptions} value="" inputValue={search} filter={null}
                    itemToStringLabel={(i) => mentionLabels.get(i) || i}
                    onInputValueChange={setSearch}
                    onValueChange={(id) => { const c = mentionById.get(id); if (c) addMention(c); }}>
                    <ComboboxInput placeholder={t("component.reportDialog.adjustMentionedChannels")} showClear={!!search} />
                    <ComboboxContent>
                      <ComboboxEmpty>{search.trim().length < 2 ? t("component.search.typeTwoCharacters") : t("component.search.noChannelsFound")}</ComboboxEmpty>
                      <ComboboxList>{(item: string, i: number) => <ComboboxItem key={item} value={item} index={i}>{mentionLabels.get(item) || item}</ComboboxItem>}</ComboboxList>
                    </ComboboxContent>
                  </Combobox>
                  <div className="flex flex-wrap gap-2">
                    {(sugMentions || []).map((s) => (
                      <div key={`${s.id}chip`} className="flex items-center gap-2 rounded-full border px-3 py-1.5">
                        <ChannelChip channel={s} size={40} />
                        <Button type="button" variant="ghost" size="icon-xs" onClick={(e) => { e.stopPropagation(); deleteMention(s); }}><icons.XIcon className="h-4 w-4" /></Button>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}
              {reasons.includes("This video does not belong to the org") && !collabsHidden && video?.type !== "clip" ? (
                <div className="space-y-2">
                  <div className="text-sm text-primary">{t("component.reportDialog.consider")}</div>
                  <VideoListFilters placeholderFilter={false} topicFilter={false} missingFilter={false} upcomingFilter={false} />
                </div>
              ) : null}
              {video?.channel?.id === "UCF4-I8ZQL6Aa-iHfdz-B9KQ" ? (
                <Alert variant="destructive">
                  <AlertDescription>
                    <b>{t("component.reportDialog.specificChannelWarningTitle")}</b>
                    {readMore ? (
                      <div className="mt-2 space-y-2">
                        <p>{t("component.reportDialog.specificChannelWarningBody1")}</p>
                        <p>{t("component.reportDialog.specificChannelWarningBody2")}</p>
                        <p>{t("component.reportDialog.specificChannelWarningBody3")}</p>
                      </div>
                    ) : <Button type="button" variant="link" className="mt-2 h-auto p-0 underline" onClick={() => setReadMore(true)}>{t("component.comment.readMore")}</Button>}
                  </AlertDescription>
                </Alert>
              ) : null}
              <div className="space-y-2">
                <Label>{t("component.reportDialog.comments")}</Label>
                <Textarea value={comments} className="min-h-32" onChange={(e) => setComments(e.target.value)} />
                <div className="text-xs text-muted-foreground">{t("component.reportDialog.commentLanguagesOk")}</div>
              </div>
              <Separator />
              <div className="flex items-center gap-3 text-sm text-muted-foreground">
                <ChannelSocials channel={video.channel} showDelete hideYt vertical className="inline-block" />
                <icons.ArrowLeft className="h-4 w-4" />
                <span>{t("component.channelSocials.block")}</span>
              </div>
              <div className="flex items-center gap-3">
                <Button type="button" variant="ghost" onClick={close}>{t("views.app.close_btn")}</Button>
                <Button type="button" className="ml-auto" disabled={!comments.length} onClick={sendReport}>{t("views.multiview.confirmOverwriteYes")}</Button>
              </div>
            </div>
          ) : null}
        </DialogContent>
      </Dialog>
    </div>
  );
}
