// src/components/video/VideoQuickPlaylist.tsx
"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { useAppState } from "@/lib/store";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { useTranslations } from "next-intl";
export function VideoQuickPlaylist({ videoId, video }: { videoId: string; video: Record<string, any> }) {
  const appStore = useAppState();
  const t = useTranslations();
  const [playlistState, setPlaylistState] = useState<any[]>([]);
  const unnamedPlaylistLabel = t("component.playlist.unnamed-playlist");
  const activePlaylistName = !appStore.playlistActive?.id && appStore.playlistActive?.name === "Unnamed Playlist"
    ? unnamedPlaylistLabel
    : appStore.playlistActive?.name || unnamedPlaylistLabel;

  useEffect(() => {
    let cancelled = false;
    async function load() {
      const next: any[] = [];
      const jwt = appStore.userdata?.jwt;
      if (jwt) {
        const playlists = await api.getPlaylistState(videoId, jwt).catch(() => ({ data: [] as any[] }));
        next.push(...(playlists.data || []));
      }
      const active = {
        id: appStore.playlistActive?.id,
        active: true,
        name: activePlaylistName,
        contains: appStore.playlist.some((item) => item.id === videoId),
      };
      const activeIdx = next.findIndex((p) => p.id === active.id);
      if (activeIdx >= 0) next.splice(activeIdx, 1);
      next.unshift(active);
      if (!cancelled) setPlaylistState(next);
    }
    void load();
    return () => { cancelled = true; };
  }, [appStore.userdata?.jwt, appStore.playlist, appStore.playlistActive?.id, activePlaylistName, videoId]);

  async function toggle(index: number) {
    const { id, active, contains } = playlistState[index];

    if (active) {
      if (contains) appStore.removeFromPlaylist(videoId);
      else appStore.addToPlaylist(video);
    } else {
      setPlaylistState((prev) => prev.map((item, idx) => idx === index ? { ...item, loading: true } : item));
      const jwt = appStore.userdata?.jwt;
      if (contains) await api.deleteVideoFromPlaylist(videoId, id, jwt);
      else await api.addVideoToPlaylist(videoId, id, jwt);
      setPlaylistState((prev) => prev.map((item, idx) => idx === index ? { ...item, loading: false } : item));
    }

    setPlaylistState((prev) => prev.map((item, idx) => idx === index ? { ...item, contains: !contains } : item));
  }

  return (
    <div className="flex flex-col gap-1">
      {playlistState.map((p, idx) => (
        <Button
          key={`${p.id}${p.name}`}
          type="button"
          variant="ghost"
          className={cn(
            "h-auto justify-start rounded-xl px-3 py-2 text-left font-normal whitespace-normal text-slate-200 hover:bg-white/8 hover:text-slate-200",
            p.contains && "bg-emerald-500/12 text-emerald-100 hover:text-emerald-100",
          )}
          onClick={(event) => { event.stopPropagation(); toggle(idx); }}
        >
          <span>{p.name}</span>
          {p.loading ? <Spinner className="ml-2 size-3" /> : null}
        </Button>
      ))}
    </div>
  );
}

// src/components/playlist/VideoQuickPlaylist.vue
<template>
  <div class="flex flex-col gap-1">
    <button
      v-for="(p,idx) in playlistState"
      :key="p.id + p.name"
      type="button"
      class="flex items-center gap-2 rounded-xl px-3 py-2 text-left text-sm text-slate-200 transition hover:bg-white/8"
      :class="{ 'bg-emerald-500/12 text-emerald-100': p.contains }"
      @click.stop="toggle(p, idx)"
    >
      <span>{{ p.name }}</span>
      <span
        v-if="p.loading"
        class="ml-2 inline-block h-3 w-3 animate-spin rounded-full border-2 border-white/30 border-t-white"
      />
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import backendApi from "@/utils/backend-api";
import { usePlaylistStore } from "@/stores/playlist";
import { useAppStore } from "@/stores/app";

defineOptions({ name: "VideoQuickPlaylist" });

const props = defineProps<{
  videoId: string;
  video: Record<string, any>;
}>();

const playlistStore = usePlaylistStore();
const appStore = useAppStore();

const playlistState = ref<any[]>([]);

onMounted(async () => {
  const jwt = appStore.userdata?.jwt;
  if (jwt) {
    const playlists = await backendApi.getPlaylistState(props.videoId, jwt);
    playlistState.value.push(...playlists.data);
  }
  const activeIdx = playlistState.value.findIndex((p) => p.id === playlistStore.active.id);
  if (activeIdx >= 0) {
    playlistState.value.splice(activeIdx, 1);
  }
  playlistState.value.unshift({
    id: playlistStore.active.id,
    active: true,
    name: playlistStore.active.name,
    contains: playlistStore.contains(props.videoId),
  });
});

async function toggle(playlist: any, index: number) {
  const { id, active, contains } = playlistState.value[index];

  if (active) {
    if (contains) playlistStore.removeVideoByID(props.videoId);
    else playlistStore.addVideo(props.video);
  } else {
    playlistState.value[index].loading = true;
    const jwt = appStore.userdata?.jwt;
    if (contains) await backendApi.deleteVideoFromPlaylist(props.videoId, id, jwt);
    else await backendApi.addVideoToPlaylist(props.videoId, id, jwt);
    playlistState.value[index].loading = false;
  }

  playlistState.value[index].contains = !contains;
}
</script>
