// src/components/video/PlaceholderCard.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Dialog } from "@/components/ui/Dialog";
import { Icon } from "@/components/ui/Icon";
import { WatchInfo } from "@/components/watch/WatchInfo";
import { api } from "@/lib/api";
import { staticThumbnailPath } from "@/lib/video-format";
import { useAppState } from "@/lib/store";
import { useI18n } from "@/lib/i18n";
import * as icons from "@/lib/icons";

export function PlaceholderCard({ open, video, onOpenChange }: { open: boolean; video: any; onOpenChange?: (value: boolean) => void }) {
  const app = useAppState();
  const { t } = useI18n();
  const [discordCredits, setDiscordCredits] = useState<any>({});
  const [mentions, setMentions] = useState<any[]>([]);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [isTooSmall, setIsTooSmall] = useState(false);
  const videoWithMentions = useMemo(() => ({ ...video, mentions }), [video, mentions]);

  useEffect(() => {
    const update = () => setIsTooSmall(window.innerWidth < 700);
    update();
    window.addEventListener("resize", update);
    return () => window.removeEventListener("resize", update);
  }, []);
  useEffect(() => {
    if (!open || !video?.id) return;
    api.getMentions(video.id).then(({ data }: any) => setMentions(data || [])).catch(console.error);
    if (video?.credits?.discord) api.discordServerInfo(video.credits.discord.link).then((res: any) => setDiscordCredits(res)).catch(console.error);
  }, [open, video?.id]);

  async function deletePlaceholder() {
    try {
      await api.deletePlaceholderStream(video.id, app.userdata.jwt);
      alert("Successfully deleted, probably.");
    } catch (e) {
      console.error(e);
      alert("Failed to delete");
    }
    setShowDeleteConfirm(false);
  }

  if (!video) return null;
  return (
    <Dialog open={open} className={isTooSmall ? "max-w-[96%] p-0" : "max-w-[980px] w-[80%] p-0"} onOpenChange={onOpenChange}>
      <Card className="relative p-0">
        {video.thumbnail ? <img src={staticThumbnailPath(video.thumbnail, "maxres")} className="placeholder-img" alt="" /> : null}
        <div className="absolute right-5 z-30 mt-[15px]">
          {video.placeholderType === "scheduled-yt-stream" ? (
            <Button size="lg" className="placeholder-punchout" as="a" href={video.link} target="_blank"><Icon icon={icons.mdiYoutube} size="sm" />{t("component.placeholderVideo.scheduledEvent")}</Button>
          ) : (
            <Button size="lg" className="placeholder-punchout" as="a" href={video.link} target="_blank"><Icon icon={icons.mdiOpenInNew} size="sm" />{video.placeholderType === "external-stream" ? t("component.placeholderVideo.streamPageBtn") : t("component.placeholderVideo.eventPageBtn")}</Button>
          )}
        </div>
        <WatchInfo video={videoWithMentions} noSubCount />
        {app.userdata.user && app.userdata.user.role !== "user" ? (
          <div className="pl-6">
            <code className="text-h6">{video.id}</code>
            <Button variant="secondary" className="m-2" as="a" href={`/add_placeholder?id=${video.id}`}>Edit</Button>
            <Button variant="destructive" className="m-2" onClick={() => setShowDeleteConfirm(true)}>Delete</Button>
            <Dialog open={showDeleteConfirm} className="max-w-[290px] p-0" onOpenChange={setShowDeleteConfirm}><Card className="space-y-4 p-5"><div className="text-lg font-semibold text-white">Are you sure?</div><div className="flex justify-end"><Button variant="destructive" size="sm" onClick={deletePlaceholder}>Delete</Button></div></Card></Dialog>
          </div>
        ) : null}
        <div style={{ height: 12 }} />
        <div className="mt-n4 pl-7 pb-5 text-left text-body-2">
          <div className="space-y-1">
            <span>{t("component.placeholderVideo.creditTitleText")}</span>
            {video.credits?.discord && discordCredits?.data ? <span> {t("component.placeholderVideo.discordCredit", [video.credits.discord.user, discordCredits.data.guild.name])} <strong><a href={`https://discord.gg/${video.credits.discord.link}`} style={{ display: "inline-block" }}><Icon icon={icons.mdiDiscord} size="sm" />{discordCredits.data.guild.name}</a></strong></span> : null}
            {video.credits?.datasource ? <span> {t("component.placeholderVideo.datasourceCredit", [video.credits.datasource.name])} <strong><a href={video.credits.datasource.link}><Icon icon={icons.mdiOpenInNew} size="sm" />{video.credits.datasource.link}</a></strong></span> : null}
            {video.credits?.bot ? <span> {t("component.placeholderVideo.botCredit", [video.credits.bot.name, video.credits.bot.user])} <strong><a href={video.credits.bot.link}><Icon icon={icons.mdiOpenInNew} size="sm" />{video.credits.bot.link}</a></strong></span> : null}
            {video.credits?.editor ? <span> {t("component.placeholderVideo.editorCredit", [video.credits.editor.name])}</span> : null}
          </div>
        </div>
      </Card>
    </Dialog>
  );
}

// src/components/video/PlaceholderCard.vue
<template>
  <UiDialog
    :open="value"
    :class-name="isTooSmall ? 'max-w-[96%] p-0' : 'max-w-[980px] w-[80%] p-0'"
    @update:open="$emit('input', $event)"
  >
    <UiCard class-name="relative p-0">
      <img v-if="video.thumbnail" :src="'/statics/thumbnail/maxres/'+enc(video.thumbnail)+'.jpg'" class="placeholder-img">

      <watch-info :video="videoWithMentions" no-sub-count>
        <div v-if="appStore.userdata.user && appStore.userdata.user.role !== 'user'" class="pl-6">
          <code class="text-h6">{{ video.id }}</code>
          <UiButton
            variant="secondary"
            class-name="m-2"
            as="a"
            :href="`/add_placeholder?id=${video.id}`"
          >
            Edit
          </UiButton>
          <UiButton
            variant="destructive"
            class-name="m-2"
            @click="showDeleteConfirm = true"
          >
            Delete
          </UiButton>
          <UiDialog
            :open="showDeleteConfirm"
            class-name="max-w-[290px] p-0"
            @update:open="showDeleteConfirm = $event"
          >
            <UiCard class-name="space-y-4 p-5">
              <div class="text-lg font-semibold text-white">
                Are you sure?
              </div>
              <div class="flex justify-end">
                <UiButton variant="destructive" size="sm" @click="deletePlaceholder">
                  Delete
                </UiButton>
              </div>
            </UiCard>
          </UiDialog>
        </div>
        <div style="height:12px;" />
        <template #rightTitleAction>
          <UiButton
            v-if="video.placeholderType === 'scheduled-yt-stream'"
            size="lg"
            class="float-right placeholder-punchout"
            as="a"
            :href="video.link"
            target="_blank"
          >
            <UiIcon :icon="icons.mdiYoutube" size="sm" />
            {{ $t('component.placeholderVideo.scheduledEvent') }}
          </UiButton>
          <UiButton
            v-else
            size="lg"
            class="float-right placeholder-punchout"
            as="a"
            target="_blank"
            :href="video.link"
          >
            <UiIcon :icon="icons.mdiOpenInNew" size="sm" />
            {{ video.placeholderType === 'external-stream' ? $t('component.placeholderVideo.streamPageBtn') : $t('component.placeholderVideo.eventPageBtn') }}
          </UiButton>
        </template>
        <div class="mt-n4 pl-7 text-left text-body-2">
          <div class="space-y-1">
            <span>{{ $t('component.placeholderVideo.creditTitleText') }}</span>
            <span v-if="video.credits.discord && discordCredits && discordCredits.data">
              <i18n path="component.placeholderVideo.discordCredit" :tag="false">
                <template #0>
                  {{ video.credits.discord.user }}
                </template>
                <template #1>
                  <strong><a :href="`https://discord.gg/${video.credits.discord.link}`" style="display:inline-block;">
                    <UiIcon :icon="icons.mdiDiscord" size="sm" />{{ discordCredits.data.guild.name }}</a>
                  </strong>
                </template>
              </i18n>
            </span>
            <span v-if="video.credits.datasource">
              {{ $t('component.placeholderVideo.datasourceCredit', [video.credits.datasource.name]) }}
              <strong><a :href="video.credits.datasource.link">
                <UiIcon :icon="icons.mdiOpenInNew" size="sm" />{{ video.credits.datasource.link }}</a>
              </strong>
            </span>
            <span v-if="video.credits.bot">
              {{ $t('component.placeholderVideo.botCredit', [video.credits.bot.name, video.credits.bot.user]) }}
              <strong><a :href="video.credits.bot.link">
                <UiIcon :icon="icons.mdiOpenInNew" size="sm" />{{ video.credits.bot.link }}</a>
              </strong>
            </span>
            <span v-if="video.credits.editor">
              {{ $t('component.placeholderVideo.editorCredit', [video.credits.editor.name]) }}
            </span>
          </div>
        </div>
      </watch-info>
    </UiCard>
  </UiDialog>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import WatchInfo from "@/components/watch/WatchInfo.vue";
import UiButton from "@/components/ui/button/Button.vue";
import UiCard from "@/components/ui/card/Card.vue";
import UiDialog from "@/components/ui/dialog/Dialog.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import backendApi from "@/utils/backend-api";
import { useAppStore } from "@/stores/app";

const props = defineProps<{ value: boolean; video: any }>();
defineEmits<{ (e: "input", val: boolean): void }>();

const appStore = useAppStore();
const discordCredits = ref<any>({});
const mentions = ref<any[]>([]);
const showDeleteConfirm = ref(false);

const isTooSmall = computed(() => window.innerWidth < 700);
const videoWithMentions = computed(() => ({ ...props.video, mentions: mentions.value }));

function enc(url: string) {
  const encoded = btoa(url);
  return encoded.replace("+", "-").replace("/", "_").replace(/=+$/, "");
}

function updateMentions() {
  backendApi.getMentions(props.video.id).then(({ data }: any) => {
    mentions.value = data;
  });
}

async function deletePlaceholder() {
  try {
    await backendApi.deletePlaceholderStream(props.video.id, appStore.userdata.jwt);
    alert("Successfully deleted, probably.");
  } catch (e) {
    console.error(e);
    alert("Failed to delete");
  }
  showDeleteConfirm.value = false;
}

onMounted(async () => {
  if (props.video?.credits?.discord) {
    discordCredits.value = await backendApi.discordServerInfo(props.video.credits.discord.link);
  }
  updateMentions();
});
</script>

<style>
.placeholder-punchout {
    position: absolute;
    right: 20px;
    margin-top: 15px;
    z-index: 30;
}
.placeholder-img {
  object-fit: contain;
  width: 100%;height: 500px;
  background: black;
  max-height: 50vh;
}
</style>
