// src/components/video/VirtualVideoCardList.vue
<template>
  <!-- Video Card grid rows -->
  <virtual-list
    ref="virtualVideoList"
    style="overflow-y: auto; overflow-x: hidden; overscroll-behavior: contain"
    :style="{ height: computedHeight }"
    :data-key="'id'"
    :data-sources="videos"
    :data-component="VideoCard"
    :extra-props="{ ...$props, parentPlaylistId: (playlist && playlist.id) || 'local' }"
    :estimate-size="88"
    :keeps="keeps"
    :page-mode="pageMode"
    :item-class="'virtual-video-list-item'"
    :item-class-add="checkActive"
  />
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from "vue";
import VideoCard from "@/components/video/VideoCard.vue";
import VirtualList from "vue-virtual-scroll-list";

defineOptions({ name: "VirtualVideoCardList" });

const props = withDefaults(defineProps<{
  playlist: Record<string, any>;
  includeChannel?: boolean;
  includeAvatar?: boolean;
  hideThumbnail?: boolean;
  horizontal?: boolean;
  keeps?: number;
  pageMode?: boolean;
  activeId?: string | null;
  dense?: boolean;
  disableDefaultClick?: boolean;
  activePlaylistItem?: boolean;
  activeIndex?: number;
  height?: string;
}>(), {
  includeChannel: undefined,
  includeAvatar: undefined,
  hideThumbnail: false,
  horizontal: true,
  keeps: 10,
  pageMode: undefined,
  activeId: null,
  dense: undefined,
  disableDefaultClick: undefined,
  activePlaylistItem: undefined,
  activeIndex: -1,
  height: "500px",
});

const virtualVideoList = ref<InstanceType<typeof VirtualList> | null>(null);

const videos = computed(() => props.playlist.videos || []);
const computedHeight = computed(() => props.pageMode ? "" : props.height);

watch(() => props.activeIndex, (idx) => {
  virtualVideoList.value?.scrollToIndex(idx);
});

onMounted(() => {
  virtualVideoList.value?.scrollToIndex(props.activeIndex);
});

function checkActive(index: number) {
  if (index === props.activeIndex) return "video-card-active";
  return "";
}
</script>

<style lang="scss">
.virtual-video-list-item {
    padding: 6px 4px;
}
.video-card-active {
    /* primary color with opacity */
    /* background-color: #f0629257; */
    height: auto;
    width: auto;
    position: relative;
}

.video-card-active::before {
    content: "";
    background-color: color-mix(in srgb, var(--color-primary) 55%, transparent);
    background-size: cover;
    position: absolute;
    top: -1px;
    right: -1px;
    bottom: -1px;
    left: -1px;
    opacity: 0.15;
    border-radius: 4px;
}
</style>

// src/components/video/VirtualVideoCardList.tsx
"use client";

import { useEffect, useMemo, useRef } from "react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { VideoCard } from "@/components/video/VideoCard";
import { cn } from "@/lib/utils";
export function VirtualVideoCardList({
  playlist,
  includeChannel,
  includeAvatar,
  hideThumbnail = false,
  horizontal = true,
  activeId = null,
  dense,
  disableDefaultClick,
  activePlaylistItem,
  activeIndex = -1,
  height = "500px",
  pageMode,
  ...rest
}: {
  playlist: Record<string, any>;
  includeChannel?: boolean;
  includeAvatar?: boolean;
  hideThumbnail?: boolean;
  horizontal?: boolean;
  keeps?: number;
  pageMode?: boolean;
  activeId?: string | null;
  dense?: boolean;
  disableDefaultClick?: boolean;
  activePlaylistItem?: boolean;
  activeIndex?: number;
  height?: string;
  [key: string]: any;
}) {
  const itemRefs = useRef<Record<number, HTMLDivElement | null>>({});
  const videos = useMemo(() => playlist?.videos || [], [playlist]);

  useEffect(() => {
    if (activeIndex < 0) return;
    itemRefs.current[activeIndex]?.scrollIntoView({ block: "nearest" });
  }, [activeIndex]);

  return (
    <ScrollArea
      className="[&>[data-slot=scroll-area-viewport]]:overscroll-contain"
      style={{ height: pageMode ? undefined : height }}
    >
      {videos.map((video: any, index: number) => (
        <div
          key={`${video.id || "video"}-${index}`}
          ref={(el) => { itemRefs.current[index] = el; }}
          className={cn("relative px-1 py-1.5", index === activeIndex && "before:pointer-events-none before:absolute before:-inset-px before:rounded before:bg-primary/15 before:content-['']")}
        >
          <VideoCard
            video={video}
            includeChannel={includeChannel}
            includeAvatar={includeAvatar}
            hideThumbnail={hideThumbnail}
            horizontal={horizontal}
            active={activePlaylistItem ? index === activeIndex : video.id === activeId}
            activePlaylistItem={activePlaylistItem}
            dense={dense}
            disableDefaultClick={disableDefaultClick}
            parentPlaylistId={playlist?.id || "local"}
            {...rest}
          />
        </div>
      ))}
    </ScrollArea>
  );
}
