// src/components/multiview/CustomUrlField.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/Button";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/Input";
import { getVideoIDFromUrl } from "@/lib/functions";
import { readJSON, writeJSON } from "@/lib/storage";
import { useOptionalMultiviewStore } from "@/lib/multiview-store";
import * as icons from "@/lib/icons";


export function CustomUrlField({ twitch = false, slim = false, onSuccess }: { twitch?: boolean; slim?: boolean; onSuccess?: (content: any) => void }) {
  const store = useOptionalMultiviewStore();
  const [url, setUrl] = useState("");
  const [error, setError] = useState(false);
  const localKey = twitch ? "holodex-v2-multiview-tw-url-history" : "holodex-v2-multiview-yt-url-history";
  const [localHistory, setLocalHistory] = useState<string[]>([]);
  const historyId = twitch ? "multiview-twitch-history" : "multiview-youtube-history";
  const hint = twitch ? "https://www.twitch.tv/..." : "https://www.youtube.com/watch?v=...";
  const label = twitch ? "Twitch Channel Link" : "Youtube Video Link";
  const history = useMemo(() => [...(store ? (twitch ? store.twUrlHistory : store.ytUrlHistory) : localHistory)].reverse(), [store, twitch, localHistory]);

  useEffect(() => { if (!store) setLocalHistory(readJSON(localKey, [] as string[])); }, [store, localKey]);
  useEffect(() => { setUrl(""); setError(false); }, [twitch]);

  function addHistory(value: string) {
    if (store) {
      store.addUrlHistory({ twitch, url: value });
      return;
    }
    setLocalHistory((prev) => {
      const next = prev.filter((item) => item !== value);
      next.push(value);
      while (next.length > 8) next.shift();
      writeJSON(localKey, next);
      return next;
    });
  }

  function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    const content = getVideoIDFromUrl(url) as any;
    if (content?.id) {
      setError(false);
      onSuccess?.(content);
      if (!history.includes(url)) addHistory(url);
      setUrl("");
    } else {
      setError(true);
    }
  }

  return (
    <form className="flex w-full items-center gap-2 px-3" onSubmit={handleSubmit}>
      <Input value={url} list={historyId} placeholder={slim ? hint : label} className={error ? "border-amber-400/60 focus:border-amber-400/70 focus:ring-amber-400/20" : ""} onChange={(event) => { setUrl(event.target.value); if (error) setError(false); }} />
      <datalist id={historyId}>{history.map((item) => <option key={item} value={item} />)}</datalist>
      <Button type="submit" size="icon" variant={(url && !error) ? "default" : "outline"}><Icon icon={icons.mdiCheck} /></Button>
    </form>
  );
}

// src/components/multiview/CustomUrlField.vue
<template>
  <form class="flex w-full items-center gap-2 px-3" @submit.prevent="handleSubmit">
    <UiInput
      v-model="url"
      :list="historyId"
      :placeholder="slim ? hint : label"
      :class-name="error ? 'border-amber-400/60 focus:border-amber-400/70 focus:ring-amber-400/20' : ''"
    />
    <datalist :id="historyId">
      <option v-for="item in history" :key="item" :value="item" />
    </datalist>
    <UiButton
      type="submit"
      size="icon"
      :variant="(url && !error) ? 'default' : 'outline'"
    >
      <UiIcon :icon="icons.mdiCheck" />
    </UiButton>
  </form>
</template>

<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { getVideoIDFromUrl } from "@/utils/functions";
import { useMultiviewStore } from "@/stores/multiview";
import UiButton from "@/components/ui/button/Button.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import UiInput from "@/components/ui/input/Input.vue";

defineOptions({ name: "CustomUrlField" });

const props = defineProps<{
  twitch?: boolean;
  slim?: boolean;
}>();

const emit = defineEmits<{
  (e: "onSuccess", content: any): void;
}>();

const multiviewStore = useMultiviewStore();

const url = ref("");
const error = ref(false);

const hint = computed(() =>
  props.twitch ? "https://www.twitch.tv/..." : "https://www.youtube.com/watch?v=...",
);

const label = computed(() =>
  props.twitch ? "Twitch Channel Link" : "Youtube Video Link",
);

const history = computed(() => {
  const hist = props.twitch ? multiviewStore.twUrlHistory : multiviewStore.ytUrlHistory;
  return [...hist].reverse();
});

const historyId = computed(() =>
  props.twitch ? "multiview-twitch-history" : "multiview-youtube-history",
);

watch(() => props.twitch, () => {
  url.value = "";
  error.value = false;
});

function handleSubmit() {
  const content = getVideoIDFromUrl(url.value);
  if (content && content.id) {
    error.value = false;
    emit("onSuccess", content);
    if (!history.value.includes(url.value)) multiviewStore.addUrlHistory({ twitch: props.twitch, url: url.value });
    url.value = "";
  } else {
    error.value = true;
  }
}
</script>
