// src/components/multiview/EmptyCell.vue
<template>
  <div class="cell-content pt-4">
    <div class="centered-btn">
      <UiButton
        type="button"
        class-name="w-[190px] bg-indigo-600 text-white hover:brightness-110"
        size="lg"
        @click="$emit('showSelector', item.i)"
      >
        <UiIcon :icon="mdiVideoPlus" />
        {{ $t("views.multiview.video.selectLive") }}
      </UiButton>

      <div class="mt-2 flex max-w-[190px] gap-2">
        <UiButton
          type="button"
          size="lg"
          class-name="flex-1 bg-teal-600 text-white hover:brightness-110"
          @click="setItemAsChat(item, false)"
        >
          <UiIcon :icon="icons.ytChat" />
          Chat
        </UiButton>
        <UiButton
          type="button"
          size="lg"
          class-name="flex-1 bg-teal-600 text-white hover:brightness-110"
          @click="setItemAsChat(item, true)"
        >
          <UiIcon :icon="icons.tlChat" />
          TL
        </UiButton>
      </div>
    </div>

    <CellControl :play-icon="icons.mdiPlay" class="mx-1 mb-2" @delete="deleteCell" />
  </div>
</template>

<script setup lang="ts">
import { mdiVideoPlus } from "@mdi/js";
import UiButton from "@/components/ui/button/Button.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import CellControl from "./CellControl.vue";
import { useMultiviewCell, type CellItem } from "@/composables/useMultiviewCell";
import { useMultiviewStore } from "@/stores/multiview";

defineOptions({ name: "EmptyCell" });

const props = defineProps<{
  item: CellItem;
}>();

const emit = defineEmits<{
  (e: "delete", id: string): void;
  (e: "showSelector", id: string): void;
}>();

const multiviewStore = useMultiviewStore();
const { deleteCell } = useMultiviewCell(props.item, emit);

function setItemAsChat(item: CellItem, initAsTL: boolean) {
  multiviewStore.setLayoutContentById({
    id: item.i,
    content: {
      type: "chat",
      initAsTL,
    },
  });
}
</script>

<style lang="scss" scoped>
.centered-btn {
    display: flex;
    flex-grow: 1;
    flex-shrink: 1;
    justify-content: center;
    align-items: center;
    overflow: hidden;
    position: relative;
    flex-direction: column;
}
</style>

// src/components/multiview/EmptyCell.tsx
"use client";

import { mdiVideoPlus } from "@mdi/js";
import { Button } from "@/components/ui/Button";
import { Icon } from "@/components/ui/Icon";
import { CellControl } from "@/components/multiview/CellControl";
import { useI18n } from "@/lib/i18n";
import { useOptionalMultiviewStore } from "@/lib/multiview-store";
import * as icons from "@/lib/icons";

export function EmptyCell({ item, onDelete, onShowSelector, onSetChat }: { item: any; onDelete?: (id: string) => void; onShowSelector?: (id: string) => void; onSetChat?: (id: string, initAsTL: boolean) => void }) {
  const { t } = useI18n();
  const store = useOptionalMultiviewStore();
  const setItemAsChat = (initAsTL: boolean) => { if (store) store.setLayoutContentById({ id: item.i, content: { type: "chat", initAsTL } }); onSetChat?.(item.i, initAsTL); };
  return (
    <div className="cell-content pt-4">
      <div className="centered-btn">
        <Button type="button" className="w-[190px] bg-indigo-600 text-white hover:brightness-110" size="lg" onClick={() => onShowSelector?.(item.i)}><Icon icon={mdiVideoPlus} />{t("views.multiview.video.selectLive")}</Button>
        <div className="mt-2 flex max-w-[190px] gap-2">
          <Button type="button" size="lg" className="flex-1 bg-teal-600 text-white hover:brightness-110" onClick={() => setItemAsChat(false)}><Icon icon={icons.ytChat} />Chat</Button>
          <Button type="button" size="lg" className="flex-1 bg-teal-600 text-white hover:brightness-110" onClick={() => setItemAsChat(true)}><Icon icon={icons.tlChat} />TL</Button>
        </div>
      </div>
      <CellControl playIcon={icons.mdiPlay} className="mx-1 mb-2" onDelete={() => onDelete?.(item.i)} />
    </div>
  );
}
