// src/components/multiview/LayoutPreviewCard.tsx
"use client";

import { LayoutPreview } from "@/components/multiview/LayoutPreview";
import { cn } from "@/lib/cn";

export function LayoutPreviewCard({ preset, custom = false, active = false, scale = 1, children, pre, post, onClick }: { preset: Record<string, any>; custom?: boolean; active?: boolean; scale?: number; children?: React.ReactNode; pre?: React.ReactNode; post?: React.ReactNode; onClick?: (event: React.MouseEvent) => void }) {
  return (
    <div className="layout-btn rounded-[calc(var(--radius)+4px)] p-2 transition" onClick={onClick}>
      <LayoutPreview layout={preset.layout} content={preset.content} mobile={preset.portrait} scale={scale} />
      <div className="layout-card-text mt-2 flex items-center justify-center gap-2 text-center text-sm">
        {pre}
        <span className={cn("min-w-0 truncate", custom && "flex-grow", active && "text-sky-300")}>{children || preset.name}</span>
        {post}
      </div>
    </div>
  );
}

// src/components/multiview/LayoutPreviewCard.vue
<template>
  <div
    class="layout-btn rounded-[calc(var(--radius)+4px)] p-2 transition"
    @click="
      (e) => {
        $emit('click', e);
      }
    "
  >
    <LayoutPreview
      :layout="preset.layout"
      :content="preset.content"
      :mobile="preset.portrait"
      :scale="scale"
    />
    <div class="layout-card-text mt-2 flex items-center justify-center gap-2 text-center text-sm">
      <slot name="pre" />
      <span class="min-w-0 truncate" :class="{ 'flex-grow': custom, 'text-sky-300': active }">{{ preset.name }}</span>
      <slot name="post" />
    </div>
  </div>
</template>

<script setup lang="ts">
import LayoutPreview from "./LayoutPreview.vue";

defineOptions({ name: "LayoutPreviewCard" });

defineProps<{
  preset: Record<string, any>;
  custom?: boolean;
  active?: boolean;
  scale?: number;
}>();

defineEmits<{
  (e: "click", event: MouseEvent): void;
}>();
</script>

<style>
.layout-btn:hover {
    background-color: rgb(255 255 255 / 0.06);
    cursor: pointer;
}

.layout-card-text {
  position: relative;
}
</style>
