// src/components/multiview/VideoCell.vue
<template>
  <div
    :key="`uid-${uniqueId}`"
    class="cell-content video-cell"
  >
    <div
      class="mv-frame"
      :class="{ 'elevation-4': editMode }"
    >
      <!-- Twitch Player -->
      <TwitchPlayer
        v-if="isTwitchVideo"
        ref="player"
        :channel="cellContent.id"
        :plays-inline="true"
        :mute="muted"
        manual-update
        @ready="onReady"
        @ended="editMode = true"
        @playing="onPlayPause(false)"
        @paused="onPlayPause(true)"
        @error="editMode = true"
        @mute="setMuted($event)"
        @volume="volume = $event"
      />
      <!-- Youtube Player -->
      <YoutubePlayer
        v-else
        ref="player"
        :key="cellContent.id"
        :video-id="cellContent.id"
        :player-vars="{
          playsinline: 1,
          cc_lang_pref: getLang,
          hl: getLang,
        }"
        :mute="muted"
        manual-update
        @ready="onReady"
        @ended="editMode = true"
        @playing="onPlayPause(false)"
        @paused="onPlayPause(true)"

        @cued="editMode = true"
        @error="editMode = true"
        @playbackRate="playbackRate = $event"
        @mute="setMuted($event)"
        @volume="volume = $event"
      />
      <div :id="`overlay-${video.id}`" style="font-size: 18px;" />
    </div>
    <cell-control
      v-if="editMode"
      @reset="uniqueId = Date.now()"
      @back="resetCell"
      @delete="deleteCell"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onBeforeUnmount, defineAsyncComponent } from "vue";
import { getYTLangFromState } from "@/utils/functions";
import YoutubePlayer from "../player/YoutubePlayer.vue";
import CellControl from "./CellControl.vue";
import { useMultiviewCell, type CellItem } from "@/composables/useMultiviewCell";
import { useMultiviewStore } from "@/stores/multiview";
import { useSettingsStore } from "@/stores/settings";

defineOptions({ name: "VideoCell" });

const TwitchPlayer = defineAsyncComponent(() => import("../player/TwitchPlayer.vue"));

const props = defineProps<{
  item: CellItem;
}>();

const emit = defineEmits<{
  (e: "delete", id: string): void;
}>();

const multiviewStore = useMultiviewStore();
const settingsStore = useSettingsStore();

const { uniqueId, cellContent, editMode, resetCell, deleteCell } = useMultiviewCell(props.item, emit);

const ytPlayer = ref<any>(null);
const twPlayer = ref<any>(null);
const playbackRate = ref(1);
const volume = ref(50);
const firstPlay = ref(true);
const timer = ref<ReturnType<typeof setInterval> | null>(null);
const player = ref<any>(null);

const isTwitchVideo = computed(() => cellContent.value?.video?.type === "twitch");

const muted = computed({
  get() {
    if (!cellContent.value) return false;
    return cellContent.value.muted;
  },
  set(value: boolean) {
    if (value !== cellContent.value?.muted) {
      multiviewStore.setLayoutContentWithKey({
        id: props.item.i,
        key: "muted",
        value,
      });
    }
  },
});

const currentTime = computed({
  get() {
    if (!cellContent.value) return 0;
    return cellContent.value.currentTime;
  },
  set(value: number) {
    if (value !== cellContent.value?.currentTime) {
      multiviewStore.setLayoutContentWithKey({
        id: props.item.i,
        key: "currentTime",
        value,
      });
    }
  },
});

const video = computed(() => {
  if (!cellContent.value) return null;
  return cellContent.value.video;
});

const isFastFoward = computed(() => playbackRate.value !== 1);

const getLang = computed(() => {
  return getYTLangFromState({ settings: settingsStore.$state });
});

function refresh() {
  uniqueId.value = Date.now();
  editMode.value = true;
}

function setPlaying(val: boolean) {
  if (editMode.value !== val) return;
  if (ytPlayer.value) {
    if (!editMode.value) { ytPlayer.value.pauseVideo(); } else { ytPlayer.value.playVideo(); }
  }
  if (twPlayer.value) {
    if (!editMode.value) { twPlayer.value.pause(); } else { twPlayer.value.play(); }
  }
}

function setMuted(val: boolean) {
  if (val === !!muted.value) return;
  if (!val) multiviewStore.muteOthersAction(props.item.i);
  muted.value = val;
}

function setVolume(val: number) {
  if (ytPlayer.value) ytPlayer.value.setVolume(val);
  if (twPlayer.value) twPlayer.value.setVolume(val / 100);
  volume.value = val;
}

function togglePlaybackRate() {
  if (!ytPlayer.value) return;
  ytPlayer.value.setPlaybackRate(isFastFoward.value ? 1 : 2);
}

function setPlaybackRate(val: number) {
  if (!ytPlayer.value) return;
  ytPlayer.value.setPlaybackRate(val);
}

function updatePausedState(paused = false) {
  if (editMode.value === paused) return;
  editMode.value = paused;
  if (firstPlay.value && !paused) {
    multiviewStore.muteOthersAction(props.item.i);
    firstPlay.value = false;
  }
}

function onPlayPause(paused = false) {
  if (ytPlayer.value && (!ytPlayer.value.getVideoData().isLive || ytPlayer.value.getVideoData().allowLiveDvr)) {
    setTimeout(() => {
      const recheck = ytPlayer.value.getPlayerState() === 2;
      updatePausedState(recheck);
    }, 200);
  } else {
    updatePausedState(paused);
  }
}

function onReady(p: any) {
  if (p && isTwitchVideo.value) {
    twPlayer.value = p;
  } else if (p) {
    ytPlayer.value = p;
  }
}

function manualRefresh() {
  if (!player.value) return;
  player.value.updateListeners();
}

async function manualCheckMuted() {
  if (!player.value) return;
  setMuted(await player.value.isMuted());
}

function setTimer() {
  if (timer.value) clearInterval(timer.value);
  timer.value = setInterval(async () => {
    if (player.value) {
      currentTime.value = await player.value.getCurrentTime();
    }
  }, 500);
}

function seekTo(t: number) {
  player.value?.seekTo(t);
}

watch(cellContent, (nw, old) => {
  if (nw?.id !== old?.id && !editMode.value) editMode.value = true;
  if (!isTwitchVideo.value) twPlayer.value = null;
  else ytPlayer.value = null;

  if (editMode.value) multiviewStore.unfreezeLayoutItem(props.item.i);
  else multiviewStore.freezeLayoutItem(props.item.i);
  setTimer();
});

watch(() => video.value?.id, () => {
  setTimer();
});

onMounted(() => {
  if (!editMode.value) editMode.value = true;
  setTimer();
});

onBeforeUnmount(() => {
  if (timer.value) clearInterval(timer.value);
});

defineExpose({
  video,
  editMode,
  muted,
  volume,
  isTwitchVideo,
  isFastFoward,
  currentTime,
  refresh,
  setPlaying,
  setMuted,
  setVolume,
  togglePlaybackRate,
  setPlaybackRate,
  manualRefresh,
  manualCheckMuted,
  seekTo,
  deleteCell,
});
</script>

<style>
.mv-frame > div > iframe {
    position: absolute;
    width: 100%;
    height: 100%;
}

.mv-frame {
    position: relative;
    width: 100%;
    flex: 1 1 auto;
    min-height: 0;
    height: auto;
}

.video-cell {
    min-height: 0;
}

.video-cell .cell-control {
    flex-shrink: 0;
}
</style>

// src/components/multiview/VideoCell.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { CellControl } from "@/components/multiview/CellControl";
import { TwitchPlayer, type TwitchPlayerHandle } from "@/components/player/TwitchPlayer";
import { YoutubePlayer, type YoutubePlayerHandle } from "@/components/player/YoutubePlayer";
import { useMultiviewStore } from "@/lib/multiview-store";
import { useRegisterMultiviewVideoCell, type MultiviewVideoCellHandle } from "@/lib/multiview-video-cells";
import { getYTLangFromState } from "@/lib/functions";
import { useAppState } from "@/lib/store";

type PlayerHandle = YoutubePlayerHandle | TwitchPlayerHandle;

export function VideoCell({ item, onDelete }: { item: any; onDelete?: (id: string) => void }) {
  const app = useAppState();
  const store = useMultiviewStore();
  const content = store.layoutContent[item.i];
  const [uniqueId, setUniqueId] = useState(0);
  const player = useRef<PlayerHandle | null>(null);
  const firstPlay = useRef(true);
  const lastExternalTime = useRef<number | null>(null);
  const storeRef = useRef(store);
  const onDeleteRef = useRef(onDelete);
  const videoRef = useRef(content?.video);
  const editModeRef = useRef(content?.editMode ?? true);
  const mutedRef = useRef(!!content?.muted);
  const volumeRef = useRef(Number(content?.volume ?? 50));
  const playbackRateRef = useRef(Number(content?.playbackRate ?? 1));
  const currentTimeRef = useRef(Number(content?.currentTime || 0));
  const isTwitchVideoRef = useRef(content?.video?.type === "twitch");
  const editMode = content?.editMode ?? true;
  const isTwitchVideo = content?.video?.type === "twitch";
  const video = content?.video;
  const muted = !!content?.muted;
  const currentTime = Number(content?.currentTime || 0);
  const lang = getYTLangFromState({ settings: app.settings });

  useEffect(() => {
    storeRef.current = store;
    onDeleteRef.current = onDelete;
    videoRef.current = video;
    editModeRef.current = editMode;
    mutedRef.current = muted;
    volumeRef.current = Number(content?.volume ?? 50);
    playbackRateRef.current = Number(content?.playbackRate ?? 1);
    currentTimeRef.current = currentTime;
    isTwitchVideoRef.current = isTwitchVideo;
  }, [store, onDelete, video, editMode, muted, content?.volume, content?.playbackRate, currentTime, isTwitchVideo]);

  useEffect(() => {
    if (!content) return;
    if (editMode) store.unfreezeLayoutItem(item.i);
    else store.freezeLayoutItem(item.i);
    player.current?.setPlaying?.(!editMode);
  }, [editMode, item.i, !!content]);

  useEffect(() => {
    player.current?.setMute?.(muted);
  }, [muted]);

  useEffect(() => {
    if (!content || isTwitchVideo) return;
    if (lastExternalTime.current === currentTime) return;
    if (lastExternalTime.current === null || Math.abs(currentTime - lastExternalTime.current) > 1) {
      (player.current as any)?.seekTo?.(currentTime);
    }
    lastExternalTime.current = currentTime;
  }, [currentTime, content?.id, isTwitchVideo]);

  useEffect(() => {
    if (!content || !video) return;
    const timer = setInterval(async () => {
      if (!player.current) return;
      const value = await player.current.getCurrentTime?.();
      if (typeof value === "number" && Number.isFinite(value) && Math.abs(value - currentTimeRef.current) >= 0.25) {
        lastExternalTime.current = value;
        currentTimeRef.current = value;
        store.setLayoutContentWithKey({ id: item.i, key: "currentTime", value });
      }
    }, 500);
    return () => clearInterval(timer);
  }, [content?.id, video?.id, item.i]);

  useEffect(() => {
    if (!content) return;
    setUniqueId((value) => value + 1);
    store.setLayoutContentWithKey({ id: item.i, key: "editMode", value: true });
  }, [content?.id]);

  function resetCell() { storeRef.current.deleteLayoutContent(item.i); }
  function deleteCell() { onDeleteRef.current?.(item.i); }
  function refresh() { setUniqueId((value) => value + 1); storeRef.current.setLayoutContentWithKey({ id: item.i, key: "editMode", value: true }); }
  function setEditMode(value: boolean) { storeRef.current.setLayoutContentWithKey({ id: item.i, key: "editMode", value }); }
  function setMuted(val: boolean) {
    if (val === mutedRef.current) return;
    if (!val) storeRef.current.muteOthersAction(item.i);
    storeRef.current.setLayoutContentWithKey({ id: item.i, key: "muted", value: val });
  }
  function setVolume(val: number) {
    player.current?.setVolume?.(val);
    volumeRef.current = val;
    storeRef.current.setLayoutContentWithKey({ id: item.i, key: "volume", value: val });
  }
  function setPlaybackRate(val: number) {
    if (isTwitchVideoRef.current) return;
    (player.current as YoutubePlayerHandle | null)?.setPlaybackRate?.(val);
    playbackRateRef.current = val;
    storeRef.current.setLayoutContentWithKey({ id: item.i, key: "playbackRate", value: val });
  }
  function togglePlaybackRate() {
    if (isTwitchVideoRef.current) return;
    setPlaybackRate(playbackRateRef.current !== 1 ? 1 : 2);
  }
  function setPlaying(val: boolean) {
    if (editModeRef.current !== val) return;
    player.current?.setPlaying?.(editModeRef.current);
  }
  function manualRefresh() {
    player.current?.updateListeners?.();
  }
  async function manualCheckMuted() {
    const value = await player.current?.isMuted?.();
    if (typeof value === "boolean") setMuted(value);
  }
  function seekTo(t: number) {
    player.current?.seekTo?.(t);
  }
  function updatePausedState(paused = false) {
    if (editModeRef.current === paused) return;
    setEditMode(paused);
    if (firstPlay.current && !paused) {
      storeRef.current.muteOthersAction(item.i);
      firstPlay.current = false;
    }
  }

  function onPlayPause(paused = false) {
    const currentPlayer = player.current as YoutubePlayerHandle | null;
    const videoData = currentPlayer?.getVideoData?.();
    if (!isTwitchVideoRef.current && currentPlayer && (!videoData?.isLive || videoData?.allowLiveDvr)) {
      setTimeout(async () => {
        const playerState = await currentPlayer.getPlayerState?.();
        updatePausedState(playerState === 2);
      }, 200);
    } else {
      updatePausedState(paused);
    }
  }
  function onReady(p: PlayerHandle) {
    player.current = p;
    p.setMute?.(muted);
  }

  const exposedCell = useMemo<MultiviewVideoCellHandle>(() => ({
    get id() { return String(item.i); },
    get video() { return videoRef.current; },
    get editMode() { return editModeRef.current; },
    get muted() { return mutedRef.current; },
    get volume() { return volumeRef.current; },
    get isTwitchVideo() { return isTwitchVideoRef.current; },
    get isFastFoward() { return playbackRateRef.current !== 1; },
    get currentTime() { return currentTimeRef.current; },
    refresh,
    setPlaying,
    setMuted,
    setVolume,
    togglePlaybackRate,
    setPlaybackRate,
    manualRefresh,
    manualCheckMuted,
    seekTo,
    deleteCell,
  }), [item.i]);

  useRegisterMultiviewVideoCell(String(item.i), content && video ? exposedCell : null);

  if (!content || !video) return null;
  return (
    <div key={`uid-${uniqueId}`} className="cell-content video-cell">
      <div className={`mv-frame ${editMode ? "elevation-4" : ""}`}>
        {isTwitchVideo ? (
          <TwitchPlayer
            ref={player as React.Ref<TwitchPlayerHandle>}
            channel={content.id}
            playsInline
            mute={muted}
            manualUpdate
            onReady={onReady as any}
            onEnded={() => setEditMode(true)}
            onPlaying={() => onPlayPause(false)}
            onPaused={() => onPlayPause(true)}
            onError={() => setEditMode(true)}
            onMute={setMuted}
            onVolume={(value) => { volumeRef.current = value; store.setLayoutContentWithKey({ id: item.i, key: "volume", value }); }}
          />
        ) : (
          <YoutubePlayer
            ref={player as React.Ref<YoutubePlayerHandle>}
            key={content.id}
            videoId={content.id}
            playerVars={{ playsinline: 1, cc_lang_pref: lang, hl: lang }}
            mute={muted}
            manualUpdate
            onReady={onReady as any}
            onEnded={() => setEditMode(true)}
            onPlaying={() => onPlayPause(false)}
            onPaused={() => onPlayPause(true)}
            onCued={() => setEditMode(true)}
            onError={() => setEditMode(true)}
            onPlaybackRate={(value) => { playbackRateRef.current = value; store.setLayoutContentWithKey({ id: item.i, key: "playbackRate", value }); }}
            onMute={setMuted}
            onVolume={(value) => { volumeRef.current = value; store.setLayoutContentWithKey({ id: item.i, key: "volume", value }); }}
          />
        )}
        <div id={`overlay-${video.id}`} style={{ fontSize: 18 }} />
      </div>
      {editMode ? <CellControl onReset={refresh} onBack={resetCell} onDelete={deleteCell} /> : null}
    </div>
  );
}
