// src/components/common/HomeOrgMultiSelect.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { mdiChevronDown, mdiDomain } from "@mdi/js";
import { Icon } from "@/components/ui/Icon";
import { Button } from "@/components/ui/Button";
import { SelectCard } from "@/components/setting/SelectCard";
import { useAppState } from "@/lib/store";
import { formatOrgDisplayName } from "@/lib/functions";
import { cn } from "@/lib/cn";
import { useAnimatedPresence } from "@/lib/useAnimatedPresence";

type HomeOrgMultiSelectProps = {
  hideTrigger?: boolean;
  buttonVariant?: string;
  buttonClass?: string;
  iconOnly?: boolean;
  emptySelectionLabel?: string;
  clearSelectionLabel?: string;
  fallbackSelection?: string[];
  selectedNamesOverride?: string[] | null;
  manualApply?: boolean;
  inline?: boolean;
  className?: string;
  onApply?: (value: string[]) => void;
};

const allSelectionKey = "__all_selection__";
const preferredOrgNames = [
  "Hololive",
  "Nijisanji",
  "VSpo",
  "Neo-Porte",
  "774inc",
  "Varium",
  "RK Music",
  "Riot Music",
];

export function HomeOrgMultiSelect({
  hideTrigger = false,
  buttonVariant = "secondary",
  buttonClass = "h-10 min-w-[12rem] px-3",
  iconOnly = false,
  emptySelectionLabel = "All Vtubers",
  clearSelectionLabel = "All Vtubers",
  fallbackSelection = [],
  selectedNamesOverride = null,
  manualApply = false,
  inline = false,
  className = "",
  onApply,
}: HomeOrgMultiSelectProps) {
  const app = useAppState();
  const root = useRef<HTMLDivElement | null>(null);
  const [isOpen, setIsOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [draftSelectedNames, setDraftSelectedNames] = useState<string[]>([]);
  const panelPresence = useAnimatedPresence(isOpen, 220);
  const bodyScrollLocked = useRef(false);
  const previousHtmlOverflow = useRef("");
  const previousBodyOverflow = useRef("");
  const previousBodyPaddingRight = useRef("");

  useEffect(() => {
    if (!app.orgs.length) app.fetchOrgs();
  }, [app.orgs.length]);

  const orgs = useMemo(
    () => (app.orgs || []).filter((org) => org.name !== "All Vtubers"),
    [app.orgs],
  );

  const selectedNames = selectedNamesOverride || app.selectedHomeOrgs || [];
  const workingSelectedNames = isOpen ? draftSelectedNames : selectedNames;

  const quickSelectOrgNames = useMemo(() => {
    const available = new Set(orgs.map((org) => org.name));
    return preferredOrgNames.filter((name) => available.has(name));
  }, [orgs]);

  const { quickSelectOptions, quickSelectAllOption, quickSelectOrgOptions } = useMemo(() => {
    const quickSelectOrgOptions = quickSelectOrgNames.map((name) => ({
      key: name,
      type: "org",
      value: name,
      label: formatOrgDisplayName(name),
    }));
    const quickSelectAllOption =
      fallbackSelection.length === 0
        ? { key: allSelectionKey, type: "all", value: null as string | null, label: clearSelectionLabel }
        : null;
    const quickSelectOptions = quickSelectAllOption
      ? [quickSelectAllOption, ...quickSelectOrgOptions]
      : quickSelectOrgOptions;
    return { quickSelectOptions, quickSelectAllOption, quickSelectOrgOptions };
  }, [quickSelectOrgNames, fallbackSelection.length, clearSelectionLabel]);

  const filteredOrgs = useMemo(() => {
    const query = search.trim().toLowerCase();
    if (!query) return orgs;
    return orgs.filter((org) =>
      [org.name, org.short, org.name_jp]
        .filter(Boolean)
        .some((value) => String(value).toLowerCase().includes(query)),
    );
  }, [orgs, search]);

  const triggerLabel = useMemo(() => {
    if (selectedNames.length === 0) return emptySelectionLabel;
    if (selectedNames.length === 1) return formatOrgDisplayName(selectedNames[0]);
    if (selectedNames.length === 2)
      return selectedNames.map((name) => formatOrgDisplayName(name)).join(" + ");
    return `${selectedNames.length} Orgs`;
  }, [selectedNames, emptySelectionLabel]);

  const resolvedButtonClass = cn(
    "home-org-trigger rounded-xl",
    iconOnly ? "justify-center" : "justify-between",
    isOpen && "home-org-trigger-open",
    buttonClass,
  );

  useEffect(() => {
    function handleKeydown(event: KeyboardEvent) {
      if (!isOpen) return;
      if (event.key === "Escape") closeDialog();
    }
    function handlePointerDown(event: PointerEvent) {
      if (!inline || !isOpen) return;
      if (root.current && !root.current.contains(event.target as Node))
        closeDialog();
    }
    window.addEventListener("keydown", handleKeydown);
    window.addEventListener("pointerdown", handlePointerDown);
    return () => {
      window.removeEventListener("keydown", handleKeydown);
      window.removeEventListener("pointerdown", handlePointerDown);
      setBodyScrollLock(false);
    };
  });

  function setBodyScrollLock(lock: boolean) {
    if (inline || typeof document === "undefined" || !document.body) return;
    if (lock && !bodyScrollLocked.current) {
      if (typeof window === "undefined") return;
      const html = document.documentElement;
      const body = document.body;
      previousHtmlOverflow.current = html.style.overflow;
      previousBodyOverflow.current = body.style.overflow;
      previousBodyPaddingRight.current = body.style.paddingRight;
      const scrollbarWidth = Math.max(0, window.innerWidth - html.clientWidth);
      html.style.overflow = "hidden";
      body.style.overflow = "hidden";
      if (scrollbarWidth > 0) body.style.paddingRight = `${scrollbarWidth}px`;
      bodyScrollLocked.current = true;
    } else if (!lock && bodyScrollLocked.current) {
      const html = document.documentElement;
      const body = document.body;
      html.style.overflow = previousHtmlOverflow.current;
      body.style.overflow = previousBodyOverflow.current;
      body.style.paddingRight = previousBodyPaddingRight.current;
      bodyScrollLocked.current = false;
    }
  }

  async function openDialog() {
    if (!app.orgs.length) await app.fetchOrgs();
    setDraftSelectedNames(
      selectedNames.length ? [...selectedNames] : [...fallbackSelection],
    );
    setIsOpen(true);
    if (!inline) setBodyScrollLock(true);
  }

  function closeDialog() {
    applySelection(draftSelectedNames);
    setIsOpen(false);
    setSearch("");
    if (!inline) setBodyScrollLock(false);
  }

  function toggleName(name: string) {
    const next = draftSelectedNames.includes(name)
      ? draftSelectedNames.filter((value) => value !== name)
      : [...draftSelectedNames, name];
    setDraftSelectedNames(next);
    if (inline) applySelection(next);
  }

  function clearSelection() {
    const next = [...fallbackSelection];
    setDraftSelectedNames(next);
    if (inline) applySelection(next);
  }

  function applySelection(nextRaw: string[]) {
    const nextSelection = [...new Set(nextRaw)];
    const prevSelection = [...selectedNames];
    const changed =
      nextSelection.length !== prevSelection.length ||
      nextSelection.some((name, index) => name !== prevSelection[index]);
    if (!changed) return;
    if (manualApply) {
      onApply?.(nextSelection);
      return;
    }
    app.setSelectedHomeOrgs(nextSelection);
  }

  const panel = panelPresence.present ? (
    <div
      data-state={panelPresence.state}
      className={cn(
        inline
          ? "home-org-inline-panel absolute left-0 top-[calc(100%+0.5rem)] z-[360] w-[min(94vw,58rem)] max-w-[58rem] rounded-2xl p-3"
          : "home-org-backdrop fixed inset-0 z-[110] flex items-center justify-center overflow-hidden p-4 backdrop-blur-sm",
        panelPresence.state === "closed" && "pointer-events-none",
      )}
      style={
        inline ? undefined : { backgroundColor: "var(--overlay-backdrop)" }
      }
      onClick={(event) => {
        if (!inline && event.target === event.currentTarget) closeDialog();
      }}
      onAnimationEnd={inline ? panelPresence.onAnimationEnd : undefined}
    >
      <div
        data-state={panelPresence.state}
        className={
          inline
            ? "home-org-panel w-full"
            : "home-org-panel w-full max-w-[min(94vw,58rem)]"
        }
        onAnimationEnd={!inline ? panelPresence.onAnimationEnd : undefined}
      >
        <SelectCard
          className="home-org-select-card"
          showSearch
          searchValue={search}
          searchPlaceholder="Search organizations"
          showClear
          clearDisabled={workingSelectedNames.length === 0}
          clearAriaLabel={`Reset to ${clearSelectionLabel}`}
          onSearchChange={setSearch}
          onClear={clearSelection}
        >
          <div className="space-y-0">
            {quickSelectOptions.length > 0 ? (
              <div className="home-org-quick-select px-1 py-2">
                <div className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-[color:var(--color-muted-foreground)]">
                  Quick Select
                </div>
                <div className="select-card-chip-flow">
                  {quickSelectAllOption ? (
                    <button
                      key={quickSelectAllOption.key}
                      type="button"
                      className={cn(
                        "settings-check-chip select-card-chip-compact",
                        workingSelectedNames.length === 0 &&
                          "settings-check-chip-selected",
                      )}
                      onClick={clearSelection}
                    >
                      <span className="select-card-chip-label">
                        {quickSelectAllOption.label}
                      </span>
                    </button>
                  ) : null}
                  {quickSelectAllOption && quickSelectOrgOptions.length ? (
                    <div
                      role="none"
                      className="home-org-quick-separator h-full w-px shrink-0 bg-[color:var(--color-border)]"
                    />
                  ) : null}
                  {quickSelectOrgOptions.map((option) => (
                    <button
                      key={option.key}
                      type="button"
                      className={cn(
                        "settings-check-chip select-card-chip-compact",
                        workingSelectedNames.includes(option.value as string) &&
                          "settings-check-chip-selected",
                      )}
                      onClick={() => toggleName(option.value as string)}
                    >
                      <span className="select-card-chip-label">
                        {option.label}
                      </span>
                    </button>
                  ))}
                </div>
                <div
                  className="home-org-quick-select-divider"
                  aria-hidden="true"
                />
              </div>
            ) : null}
            <div className="home-org-select-scroll h-[40vh] overflow-y-auto overscroll-contain md:h-[44vh]">
              <div className="select-card-chip-flow pr-1 pt-2">
                {filteredOrgs.map((org) => (
                  <button
                    key={org.name}
                    type="button"
                    className={cn(
                      "settings-check-chip select-card-chip-compact",
                      workingSelectedNames.includes(org.name) && "settings-check-chip-selected",
                    )}
                    onClick={() => toggleName(org.name)}
                  >
                    <span className="select-card-chip-label">
                      {formatOrgDisplayName(org.name)}
                    </span>
                  </button>
                ))}
              </div>
            </div>
          </div>
          {filteredOrgs.length === 0 ? (
            <div className="text-xs text-[color:var(--color-muted-foreground)]">
              No organizations found
            </div>
          ) : null}
        </SelectCard>
      </div>
    </div>
  ) : null;

  return (
    <div ref={root} className={cn("relative", className)}>
      {!hideTrigger ? (
        <Button
          type="button"
          variant={buttonVariant as any}
          className={resolvedButtonClass}
          aria-haspopup={inline ? "listbox" : "dialog"}
          aria-expanded={isOpen ? "true" : "false"}
          onClick={() => (inline && isOpen ? closeDialog() : openDialog())}
        >
          {iconOnly ? (
            <Icon
              icon={mdiDomain}
              size="sm"
              className="home-org-trigger-icon"
            />
          ) : (
            <>
              <span className="min-w-0 flex flex-1 items-center gap-2">
                <Icon
                  icon={mdiDomain}
                  size="sm"
                  className="home-org-trigger-icon"
                />
                <span className="min-w-0 truncate text-left">
                  {triggerLabel}
                </span>
              </span>
              <span className="shrink-0 flex items-center gap-2">
                <Icon
                  icon={mdiChevronDown}
                  size="sm"
                  className={cn(
                    "home-org-trigger-chevron",
                    isOpen && "home-org-trigger-chevron-open",
                  )}
                />
              </span>
            </>
          )}
        </Button>
      ) : null}
      {panel}
    </div>
  );
}

// src/components/common/HomeOrgMultiSelect.vue
<template>
  <div ref="root" class="relative">
    <UiButton
      v-if="!hideTrigger"
      type="button"
      :variant="buttonVariant"
      :class-name="resolvedButtonClass"
      :aria-haspopup="inline ? 'listbox' : 'dialog'"
      :aria-expanded="isOpen ? 'true' : 'false'"
      @click="handleTriggerClick"
    >
      <template v-if="iconOnly">
        <UiIcon :icon="mdiDomain" size="sm" class-name="home-org-trigger-icon" />
      </template>
      <template v-else>
        <span class="min-w-0 flex flex-1 items-center gap-2">
          <UiIcon :icon="mdiDomain" size="sm" class-name="home-org-trigger-icon" />
          <span class="min-w-0 truncate text-left">{{ triggerLabel }}</span>
        </span>
        <span class="shrink-0 flex items-center gap-2">
          <UiIcon
            :icon="mdiChevronDown"
            size="sm"
            :class-name="`home-org-trigger-chevron ${isOpen ? 'home-org-trigger-chevron-open' : ''}`"
          />
        </span>
      </template>
    </UiButton>

    <teleport to="body" :disabled="inline">
      <transition :name="inline ? 'home-org-inline' : 'home-org-backdrop'">
        <div
          v-if="isOpen"
          :class="inline
            ? 'home-org-inline-panel absolute left-0 top-[calc(100%+0.5rem)] z-[360] w-[min(94vw,58rem)] max-w-[58rem] rounded-2xl p-3'
            : 'fixed inset-0 z-[110] flex items-center justify-center overflow-hidden p-4 backdrop-blur-sm'"
          :style="inline ? undefined : 'background-color: var(--overlay-backdrop);'"
          @click.self="!inline && closeDialog()"
        >
          <transition name="home-org-panel" appear>
            <div :class="inline ? 'w-full' : 'w-full max-w-[min(94vw,58rem)]'">
              <SelectCard
                class="home-org-select-card"
                :show-search="true"
                :search-value="search"
                search-placeholder="Search organizations"
                :show-clear="true"
                :clear-disabled="workingSelectedNames.length === 0"
                :clear-aria-label="`Reset to ${clearSelectionLabel}`"
                :scroll-options="false"
                @update:searchValue="search = $event"
                @clear="clearSelection"
              >
                <template #selectedTags>
                  <transition-group
                    v-if="workingSelectedNames.length > 0"
                    name="home-org-chip"
                    tag="div"
                    class="select-card-chip-flow"
                  >
                    <div
                      v-for="name in workingSelectedNames"
                      :key="name"
                      class="settings-check-chip settings-check-chip-selected select-card-chip-compact"
                    >
                      <span class="settings-check-chip-indicator" />
                      <span class="select-card-chip-label">{{ displayOrgName(name) }}</span>
                      <button
                        type="button"
                        class="select-card-chip-meta select-card-chip-remove select-card-chip-remove-btn"
                        :aria-label="`Remove ${name}`"
                        @click.stop="toggleName(name)"
                      >
                        <UiIcon :icon="mdiClose" size="xs" />
                      </button>
                    </div>
                  </transition-group>
                </template>

                <template #options>
                  <div class="space-y-0">
                    <div
                      v-if="quickSelectOptions.length > 0"
                      class="home-org-quick-select px-1 py-2"
                    >
                      <div class="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-[color:var(--color-muted-foreground)]">
                        Quick Select
                      </div>
                      <div class="select-card-chip-flow">
                        <button
                          v-if="quickSelectAllOption"
                          :key="quickSelectAllOption.key"
                          type="button"
                          class="settings-check-chip select-card-chip-compact"
                          :class="{ 'settings-check-chip-selected': isQuickSelected(quickSelectAllOption) }"
                          @click="toggleQuickSelect(quickSelectAllOption)"
                        >
                          <span class="settings-check-chip-indicator" />
                          <span class="select-card-chip-label">{{ quickSelectAllOption.label }}</span>
                        </button>
                        <UiSeparator
                          v-if="quickSelectAllOption && quickSelectOrgOptions.length"
                          orientation="vertical"
                          class-name="home-org-quick-separator"
                        />
                        <button
                          v-for="option in quickSelectOrgOptions"
                          :key="option.key"
                          type="button"
                          class="settings-check-chip select-card-chip-compact"
                          :class="{ 'settings-check-chip-selected': isQuickSelected(option) }"
                          @click="toggleQuickSelect(option)"
                        >
                          <span class="settings-check-chip-indicator" />
                          <span class="select-card-chip-label">{{ option.label }}</span>
                        </button>
                      </div>
                      <div class="home-org-quick-select-divider" aria-hidden="true" />
                    </div>
                    <UiScrollArea
                      class-name="home-org-select-scroll h-[40vh] md:h-[44vh]"
                      :native-scrollbar="true"
                    >
                      <transition-group
                        name="home-org-option"
                        tag="div"
                        class="select-card-chip-flow pr-1 pt-2"
                      >
                        <button
                          v-for="org in filteredOrgs"
                          :key="org.name"
                          type="button"
                          class="settings-check-chip select-card-chip-compact"
                          :class="{ 'settings-check-chip-selected': isSelected(org.name) }"
                          @click="toggleName(org.name)"
                        >
                          <span class="settings-check-chip-indicator" />
                          <span class="select-card-chip-label">{{ displayOrgName(org.name) }}</span>
                        </button>
                      </transition-group>
                    </UiScrollArea>
                  </div>
                </template>

                <template #footer>
                  <div v-if="filteredOrgs.length === 0" class="text-xs text-[color:var(--color-muted-foreground)]">
                    No organizations found
                  </div>
                </template>
              </SelectCard>
            </div>
          </transition>
        </div>
      </transition>
    </teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from "vue";
import UiButton from "@/components/ui/button/Button.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import UiScrollArea from "@/components/ui/scroll-area/ScrollArea.vue";
import UiSeparator from "@/components/ui/separator/Separator.vue";
import SelectCard from "@/components/setting/SelectCard.vue";
import { formatOrgDisplayName } from "@/utils/functions";
import { mdiChevronDown, mdiClose, mdiDomain } from "@mdi/js";
import { useOrgsStore } from "@/stores/orgs";
import { useAppStore } from "@/stores/app";

defineOptions({ name: "HomeOrgMultiSelect" });

const props = withDefaults(defineProps<{
  hideTrigger?: boolean;
  buttonVariant?: string;
  buttonClass?: string;
  iconOnly?: boolean;
  emptySelectionLabel?: string;
  clearSelectionLabel?: string;
  fallbackSelection?: string[];
  selectedNamesOverride?: string[] | null;
  manualApply?: boolean;
  inline?: boolean;
}>(), {
  hideTrigger: false,
  buttonVariant: "secondary",
  buttonClass: "h-10 min-w-[12rem] px-3",
  iconOnly: false,
  emptySelectionLabel: "All Vtubers",
  clearSelectionLabel: "All Vtubers",
  fallbackSelection: () => [],
  selectedNamesOverride: null,
  manualApply: false,
  inline: false,
});

const emit = defineEmits<{
  (e: "apply", value: string[]): void;
}>();

const root = ref<HTMLElement | null>(null);
const allSelectionKey = "__all_selection__";
const isOpen = ref(false);
const search = ref("");
const draftSelectedNames = ref<string[]>([]);
const bodyScrollLocked = ref(false);
const previousHtmlOverflow = ref("");
const previousBodyOverflow = ref("");
const previousBodyPaddingRight = ref("");

const orgs = computed(() =>
  (useOrgsStore().orgs || []).filter((org) => org.name !== "All Vtubers"),
);

const selectedNames = computed(() =>
  props.selectedNamesOverride || useAppStore().selectedHomeOrgs || [],
);

const workingSelectedNames = computed(() =>
  isOpen.value ? draftSelectedNames.value : selectedNames.value,
);

const quickSelectOrgNames = computed(() => {
  const preferred = ["Hololive", "Nijisanji", "VSpo", "Neo-Porte", "774inc", "RK Music", "Riot Music"];
  const available = new Set(orgs.value.map((org) => org.name));
  return preferred.filter((name) => available.has(name));
});

const quickSelectOptions = computed(() => {
  const options = quickSelectOrgNames.value.map((name) => ({
    key: name,
    type: "org",
    value: name,
    label: getOrgLabel(name),
  }));
  if (props.fallbackSelection.length === 0) {
    return [{
      key: allSelectionKey,
      type: "all",
      value: null as string | null,
      label: props.clearSelectionLabel,
    }, ...options];
  }
  return options;
});

const quickSelectAllOption = computed(() =>
  quickSelectOptions.value.find((option) => option.type === "all") || null,
);

const quickSelectOrgOptions = computed(() =>
  quickSelectOptions.value.filter((option) => option.type === "org"),
);

const filteredOrgs = computed(() => {
  const query = search.value.trim().toLowerCase();
  if (!query) return orgs.value;
  return orgs.value.filter((org) =>
    [org.name, org.short, org.name_jp]
      .filter(Boolean)
      .some((value) => (value as string).toLowerCase().includes(query)),
  );
});

const triggerLabel = computed(() => {
  if (selectedNames.value.length === 0) return props.emptySelectionLabel;
  if (selectedNames.value.length === 1) return displayOrgName(selectedNames.value[0]);
  if (selectedNames.value.length === 2) {
    return selectedNames.value.map((name) => displayOrgName(name)).join(" + ");
  }
  return `${selectedNames.value.length} Orgs`;
});

const resolvedButtonClass = computed(() => [
  "home-org-trigger rounded-xl",
  props.iconOnly ? "justify-center" : "justify-between",
  isOpen.value ? "home-org-trigger-open" : "",
  props.buttonClass,
].join(" "));

function handleTriggerClick() {
  if (props.inline && isOpen.value) {
    closeDialog();
    return;
  }
  openDialog();
}

function lockPageScroll() {
  if (bodyScrollLocked.value || typeof window === "undefined" || !document?.body) return;
  const html = document.documentElement;
  const body = document.body;
  previousHtmlOverflow.value = html.style.overflow;
  previousBodyOverflow.value = body.style.overflow;
  previousBodyPaddingRight.value = body.style.paddingRight;
  const scrollbarWidth = Math.max(0, window.innerWidth - html.clientWidth);
  html.style.overflow = "hidden";
  body.style.overflow = "hidden";
  if (scrollbarWidth > 0) body.style.paddingRight = `${scrollbarWidth}px`;
  bodyScrollLocked.value = true;
}

function unlockPageScroll() {
  if (!bodyScrollLocked.value || !document?.body) return;
  const html = document.documentElement;
  const body = document.body;
  html.style.overflow = previousHtmlOverflow.value;
  body.style.overflow = previousBodyOverflow.value;
  body.style.paddingRight = previousBodyPaddingRight.value;
  bodyScrollLocked.value = false;
}

function handleWindowKeydown(event: KeyboardEvent) {
  if (!isOpen.value) return;
  if (event.key === "Escape") closeDialog();
}

function handleWindowPointerDown(event: PointerEvent) {
  if (!props.inline || !isOpen.value) return;
  if (root.value && !root.value.contains(event.target as Node)) closeDialog();
}

async function openDialog() {
  if (!orgs.value.length) await useOrgsStore().fetchOrgs();
  draftSelectedNames.value = selectedNames.value.length
    ? [...selectedNames.value]
    : [...props.fallbackSelection];
  isOpen.value = true;
  if (!props.inline) lockPageScroll();
}

function closeDialog() {
  applySelection();
  isOpen.value = false;
  search.value = "";
  if (!props.inline) unlockPageScroll();
}

function isSelected(name: string) {
  return workingSelectedNames.value.includes(name);
}

function isQuickSelected(option: { type: string; value: string | null }) {
  if (option.type === "all") return workingSelectedNames.value.length === 0;
  return isSelected(option.value as string);
}

function getOrgLabel(name: string) {
  const org = orgs.value.find((item) => item.name === name);
  return displayOrgName(org?.name || name);
}

function displayOrgName(name: string) {
  return formatOrgDisplayName(name);
}

function toggleQuickSelect(option: { type: string; value: string | null }) {
  if (option.type === "all") {
    clearSelection();
    return;
  }
  toggleName(option.value as string);
}

function toggleName(name: string) {
  if (draftSelectedNames.value.includes(name)) {
    draftSelectedNames.value = draftSelectedNames.value.filter((v) => v !== name);
    if (props.inline) applySelection();
    return;
  }
  draftSelectedNames.value = [...draftSelectedNames.value, name];
  if (props.inline) applySelection();
}

function clearSelection() {
  draftSelectedNames.value = [...props.fallbackSelection];
  if (props.inline) applySelection();
}

function applySelection() {
  const nextSelection = [...new Set(draftSelectedNames.value)];
  const prevSelection = [...selectedNames.value];
  const changed = nextSelection.length !== prevSelection.length
    || nextSelection.some((name, index) => name !== prevSelection[index]);
  if (!changed) return;
  if (props.manualApply) {
    emit("apply", nextSelection);
    return;
  }
  useAppStore().setSelectedHomeOrgs(nextSelection);
}

onMounted(() => {
  window.addEventListener("keydown", handleWindowKeydown);
  window.addEventListener("pointerdown", handleWindowPointerDown);
});

onBeforeUnmount(() => {
  window.removeEventListener("keydown", handleWindowKeydown);
  window.removeEventListener("pointerdown", handleWindowPointerDown);
  unlockPageScroll();
});
</script>

<style scoped>
.home-org-trigger {
  border-color: var(--color-light) !important;
  background: var(--color-card) !important;
  color: var(--color-muted-foreground) !important;
  cursor: pointer;
  -webkit-backdrop-filter: blur(14px);
  backdrop-filter: blur(14px);
  transition: border-color 180ms ease, background-color 180ms ease, color 180ms ease, box-shadow 180ms ease;
}

.home-org-trigger:hover {
  border-color: var(--color-bold) !important;
  background: var(--color-base) !important;
  color: var(--color-foreground) !important;
}

.home-org-trigger-open {
  border-color: var(--color-bold) !important;
  box-shadow: 0 0 0 2px color-mix(in srgb, var(--color-bold) 22%, transparent);
}

.home-org-trigger-icon {
  color: var(--color-primary);
  opacity: 0.95;
}

.home-org-trigger-chevron {
  color: var(--color-muted-foreground);
  transition: transform 180ms ease, color 180ms ease;
}

.home-org-trigger-chevron-open {
  transform: rotate(180deg);
  color: var(--color-foreground);
}

.home-org-select-card {
  border: none !important;
  background: transparent !important;
  -webkit-backdrop-filter: none;
  backdrop-filter: none;
  box-shadow: none;
}

.home-org-inline-panel {
  background: var(--surface-nav-solid);
  border: 1px solid var(--color-border);
  box-shadow: 0 20px 56px rgb(2 6 23 / 0.34);
}

.home-org-select-card :deep(.select-card) {
  border: none !important;
  background: transparent !important;
}

.home-org-select-card :deep(.select-card-search-input) {
  background: color-mix(in srgb, var(--surface-nav) 78%, transparent) !important;
}

.home-org-quick-select {
  position: relative;
  background: transparent;
}

.home-org-quick-select-divider {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  height: 1px;
  background: color-mix(in srgb, var(--color-border) 72%, transparent 28%);
  pointer-events: none;
}

.home-org-quick-separator {
  height: 1.25rem;
  align-self: center;
  opacity: 0.9;
}

.home-org-select-scroll :deep(.scroll-area-viewport) {
  overscroll-behavior: contain;
}

.home-org-backdrop-enter-active,
.home-org-backdrop-leave-active {
  transition: opacity 180ms ease;
}

.home-org-backdrop-enter-from,
.home-org-backdrop-leave-to {
  opacity: 0;
}

.home-org-inline-enter-active,
.home-org-inline-leave-active {
  transition: opacity 160ms ease;
}

.home-org-inline-enter-from,
.home-org-inline-leave-to {
  opacity: 0;
}

.home-org-panel-enter-active,
.home-org-panel-leave-active {
  transition: transform 220ms cubic-bezier(0.16, 1, 0.3, 1), opacity 180ms ease;
}

.home-org-panel-enter-from,
.home-org-panel-leave-to {
  opacity: 0;
  transform: translateY(8px) scale(0.985);
}

.home-org-chip-enter-active,
.home-org-chip-leave-active {
  transition: transform 170ms ease, opacity 170ms ease;
}

.home-org-chip-enter-from,
.home-org-chip-leave-to {
  opacity: 0;
  transform: translateY(4px) scale(0.96);
}

.home-org-option-enter-active,
.home-org-option-leave-active {
  transition: transform 150ms ease, opacity 150ms ease;
}

.home-org-option-enter-from,
.home-org-option-leave-to {
  opacity: 0;
  transform: translateY(4px);
}
</style>
