// src/components/player/TwitchPlayer.tsx
"use client";

import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from "react";
let pid = 0;

function loadScript(src: string): Promise<void> {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) { resolve(); return; }
    const s = document.createElement("script");
    s.src = src;
    s.onload = () => resolve();
    s.onerror = (e) => reject(e);
    document.head.appendChild(s);
  });
}

export type TwitchPlayerHandle = {
  play: () => void;
  pause: () => void;
  getCurrentTime: () => number;
  getPlaybackRate: () => number;
  getVolume: () => number;
  isMuted: () => boolean;
  setMute: (value: boolean) => void;
  setPlaying: (playing: boolean) => void;
  setVolume: (volume: number) => void;
  seekTo?: (time: number) => void;
  updateListeners: () => void;
};

export const TwitchPlayer = forwardRef<TwitchPlayerHandle, {
  height?: number | string;
  width?: number | string;
  mute?: boolean;
  refreshRate?: number;
  manualUpdate?: boolean;
  quality?: string;
  playsInline?: boolean;
  channel?: string;
  video?: string;
  className?: string;
  onReady?: (player: TwitchPlayerHandle) => void;
  onError?: (error: unknown) => void;
  onCurrentTime?: (value: number) => void;
  onPlaybackRate?: (value: number) => void;
  onMute?: (value: boolean) => void;
  onVolume?: (value: number) => void;
  onEnded?: () => void;
  onPaused?: () => void;
  onPlaying?: () => void;
}>(function TwitchPlayer({
  height = 720,
  width = 1280,
  mute = false,
  refreshRate = 500,
  manualUpdate = false,
  quality = "medium",
  playsInline = false,
  channel = "",
  video = "",
  className = "",
  onReady,
  onError,
  onCurrentTime,
  onPlaybackRate,
  onMute,
  onVolume,
  onEnded,
  onPaused,
  onPlaying,
}, ref) {
  const [elementId] = useState(() => {
    pid += 1;
    return `twitch-player-${pid}`;
  });
  const twitchPlayer = useRef<any>(null);
  const readyRef = useRef(false);

  const handle: TwitchPlayerHandle = useMemo(() => ({
    play: () => { twitchPlayer.current?.play?.(); },
    pause: () => { twitchPlayer.current?.pause?.(); },
    getCurrentTime: () => twitchPlayer.current?.getCurrentTime?.() ?? 0,
    getPlaybackRate: () => 1,
    getVolume: () => (twitchPlayer.current?.getVolume?.() ?? 0) * 100,
    isMuted: () => twitchPlayer.current?.getMuted?.() ?? false,
    setMute: (value: boolean) => { twitchPlayer.current?.setMuted?.(value); },
    setPlaying: (playing: boolean) => { if (playing) twitchPlayer.current?.play?.(); else twitchPlayer.current?.pause?.(); },
    setVolume: (volume: number) => { twitchPlayer.current?.setVolume?.(volume / 100); },
    seekTo: (time: number) => { twitchPlayer.current?.seek?.(time); },
    updateListeners: () => {
      onMute?.(twitchPlayer.current?.getMuted?.() ?? false);
      onPlaybackRate?.(1);
      onCurrentTime?.(twitchPlayer.current?.getCurrentTime?.() ?? 0);
      onVolume?.((twitchPlayer.current?.getVolume?.() ?? 0) * 100);
    },
  }), [onCurrentTime, onMute, onPlaybackRate, onVolume]);

  useImperativeHandle(ref, () => handle, [handle]);

  useEffect(() => {
    let cancelled = false;
    loadScript("https://player.twitch.tv/js/embed/v1.js")
      .then(() => {
        if (cancelled) return;
        const options: Record<string, any> = { width, height, parent: [window.location.hostname], autoplay: false };
        if (playsInline) options.playsinline = true;
        if (channel) options.channel = channel;
        else if (video) options.video = video;
        else { onError?.("no source specified"); return; }
        const tp = new (window as any).Twitch.Player(elementId, options);
        twitchPlayer.current = tp;
        tp.addEventListener("ended", () => onEnded?.());
        tp.addEventListener("pause", () => onPaused?.());
        tp.addEventListener("play", () => onPlaying?.());
        tp.addEventListener("ready", () => {
          readyRef.current = true;
          tp.setQuality(quality);
          tp.setMuted(mute);
          onReady?.(handle);
        });
      })
      .catch((e) => onError?.(e));
    return () => {
      cancelled = true;
      readyRef.current = false;
      onPaused?.();
      twitchPlayer.current = null;
    };
  }, [elementId]);

  useEffect(() => { if (readyRef.current && channel) twitchPlayer.current?.setChannel?.(channel); }, [channel]);
  useEffect(() => { if (readyRef.current && video) twitchPlayer.current?.setVideo?.(video); }, [video]);
  useEffect(() => { if (readyRef.current) twitchPlayer.current?.setMuted?.(mute); }, [mute]);
  useEffect(() => {
    if (manualUpdate || !(onCurrentTime || onPlaybackRate || onMute || onVolume)) return;
    const timer = setInterval(() => handle.updateListeners(), refreshRate);
    return () => clearInterval(timer);
  }, [manualUpdate, onCurrentTime, onPlaybackRate, onMute, onVolume, refreshRate, handle]);

  return <div id={elementId} className={className || undefined} />;
});

// src/components/player/TwitchPlayer.vue
<template>
  <div :id="elementId" />
</template>

<script setup lang="ts">
import { ref, watch, onBeforeUnmount, onMounted, useAttrs } from "vue";
import { usePlayer } from "@/composables/usePlayer";

defineOptions({ name: "TwitchPlayer" });

function loadScript(src: string): Promise<void> {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) { resolve(); return; }
    const s = document.createElement("script");
    s.src = src;
    s.onload = () => resolve();
    s.onerror = (e) => reject(e);
    document.head.appendChild(s);
  });
}

let pid = 0;

const props = withDefaults(defineProps<{
  height?: number | string;
  width?: number | string;
  mute?: boolean;
  refreshRate?: number;
  manualUpdate?: boolean;
  quality?: string;
  playsInline?: boolean;
  channel?: string;
  video?: string;
}>(), {
  height: 720,
  width: 1280,
  mute: false,
  refreshRate: 500,
  quality: "medium",
  playsInline: false,
  channel: "",
  video: "",
});

const emit = defineEmits<{
  (e: "ready", player: unknown): void;
  (e: "error", error: unknown): void;
  (e: "currentTime", value: number): void;
  (e: "playbackRate", value: number): void;
  (e: "mute", value: boolean): void;
  (e: "volume", value: number): void;
  (e: "ended"): void;
  (e: "paused"): void;
  (e: "playing"): void;
}>();

const attrs = useAttrs();
const activeListeners = new Set(
  Object.keys(attrs)
    .filter((k) => k.startsWith("on"))
    .map((k) => k[2].toLowerCase() + k.slice(3)),
);

const { playerReady, playerError, setMethods } = usePlayer(props, emit, activeListeners);

pid += 1;
const elementId = ref(`twitch-player-${pid}`);
const twitchPlayer = ref<any>(null);

watch(() => props.channel, (newChannel) => {
  twitchPlayer.value?.setChannel(newChannel);
});

watch(() => props.video, (newVideo) => {
  twitchPlayer.value?.setVideo(newVideo);
});

watch(() => props.mute, (value) => {
  twitchPlayer.value?.setMuted(value);
});

onBeforeUnmount(() => {
  if (twitchPlayer.value !== null) {
    emit("paused");
    twitchPlayer.value = null;
  }
});

onMounted(() => {
  loadScript("https://player.twitch.tv/js/embed/v1.js")
    .then(() => {
      const options: Record<string, any> = {
        width: props.width,
        height: props.height,
        parent: [window.location.hostname],
        autoplay: false,
      };
      if (props.playsInline) {
        options.playsinline = true;
      }
      if (props.channel) {
        options.channel = props.channel;
      } else if (props.video) {
        options.video = props.video;
      } else {
        emit("error", "no source specified");
      }
      const tp = new (window as any).Twitch.Player(elementId.value, options);
      twitchPlayer.value = tp;
      tp.addEventListener("ended", () => emit("ended"));
      tp.addEventListener("pause", () => emit("paused"));
      tp.addEventListener("play", () => emit("playing"));
      tp.addEventListener("ready", () => {
        tp.setQuality(props.quality);
        setMethods({
          getCurrentTime: () => tp.getCurrentTime(),
          getVolume: () => tp.getVolume() * 100,
          isMuted: () => tp.getMuted(),
          setMute: (value: boolean) => tp.setMuted(value),
          setPlaying: (playing: boolean) => {
            if (!tp) return;
            if (!playing) { tp.pause(); } else { tp.play(); }
          },
        });
        playerReady(tp);
      });
    })
    .catch((e) => playerError(e));
});

function play() {
  twitchPlayer.value?.play();
}

function pause() {
  twitchPlayer.value?.pause();
}

function getCurrentTime() {
  return twitchPlayer.value?.getCurrentTime();
}

function getVolume() {
  return (twitchPlayer.value?.getVolume() ?? 0) * 100;
}

function isMuted() {
  return twitchPlayer.value?.getMuted();
}

function setMute(value: boolean) {
  twitchPlayer.value?.setMuted(value);
}

function setPlaying(playing: boolean) {
  if (!twitchPlayer.value) return;
  if (!playing) { twitchPlayer.value.pause(); } else { twitchPlayer.value.play(); }
}

defineExpose({ play, pause, getCurrentTime, getVolume, isMuted, setMute, setPlaying });
</script>
