// src/components/tl/ImportMchad.tsx
"use client";

import { useState } from "react";
import { api } from "@/lib/api";
import { useAppState } from "@/lib/store";
import { useTranslations } from "next-intl";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
export function ImportMchad({ onClose }: { onClose?: (payload: { upload?: boolean }) => void }) {
  const t = useTranslations();
  const app = useAppState();
  const [room, setRoom] = useState("");
  const [pass, setPass] = useState("");
  const [loginText, setLoginText] = useState("");
  const [archiveData, setArchiveData] = useState<any[]>([]);
  const [working, setWorking] = useState(false);
  const [claimErrorMsg, setClaimErrorMsg] = useState("");
  const [claimSuccess, setClaimSuccess] = useState(false);
  function resetData() { setRoom(""); setPass(""); setLoginText(""); setArchiveData([]); setWorking(false); setClaimSuccess(false); setClaimErrorMsg(""); }
  async function checkAvailable() { try { setWorking(true); if (!(room && pass)) throw new Error(t("views.tlManager.importMchad.missingCredentials")); const { data } = await api.checkMchadMigrate(room, pass); setArchiveData(data.archives); setLoginText(t("views.tlManager.importMchad.foundId", { id: data.mchad_user_id })); } catch (e: any) { setClaimErrorMsg(e.message); } setWorking(false); }
  async function claimAll() { try { setWorking(true); const res = await api.claimMchadMigrate(app.userdata.jwt!, room, pass); if (res.status === 200) setClaimSuccess(true); } catch (error: any) { setClaimErrorMsg(error.response?.data?.message || error.message); } setWorking(false); }
  return (
    <div className="space-y-5 p-6">
      <h2 className="text-lg font-semibold text-white">{t("views.tlManager.importFromMchad")}</h2>
      {claimSuccess ? (
        <Alert>
          <AlertDescription>{t("views.tlManager.importMchad.claimSuccess")}</AlertDescription>
        </Alert>
      ) : null}
      {claimErrorMsg ? (
        <Alert variant="destructive">
          <AlertDescription>{claimErrorMsg}</AlertDescription>
        </Alert>
      ) : null}
      <FieldGroup>
        <div className="grid gap-3 md:grid-cols-2">
          <Field>
            <FieldLabel>{t("views.tlManager.importMchad.roomName")}</FieldLabel>
            <Input value={room} onChange={(e) => setRoom(e.target.value)} />
          </Field>
          <Field>
            <FieldLabel>{t("views.tlManager.importMchad.password")}</FieldLabel>
            <Input value={pass} onChange={(e) => setPass(e.target.value)} type="password" />
          </Field>
        </div>
        <Button variant="secondary" className="w-full" onClick={checkAvailable}>{t("views.tlManager.importMchad.login")}</Button>
        <p className="text-sm text-muted-foreground">{loginText}</p>
      </FieldGroup>
      <div className="max-h-[40vh] overflow-auto rounded-[calc(var(--radius)+6px)] border">
        <Table>
          <TableHeader className="sticky top-0 bg-background">
            <TableRow>
              <TableHead>#</TableHead>
              <TableHead>{t("views.tlManager.headerID")}</TableHead>
              <TableHead>{t("views.tlManager.importMchad.entryLength")}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {archiveData.map((dt, index) => (
              <TableRow key={index}>
                <TableCell>{index + 1}</TableCell>
                <TableCell>{dt.video_id}</TableCell>
                <TableCell>{dt.count}</TableCell>
              </TableRow>
            ))}
            {archiveData.length === 0 ? (
              <TableRow>
                <TableCell colSpan={3} className="py-8 text-center text-muted-foreground">{t("views.tlManager.importMchad.noArchives")}</TableCell>
              </TableRow>
            ) : null}
          </TableBody>
        </Table>
      </div>
      <div className="flex items-center gap-3">
        <Button variant="ghost" onClick={() => { onClose?.({ upload: false }); resetData(); }}>{t("views.watch.uploadPanel.cancelBtn")}</Button>
        <Button variant="destructive" className="ml-auto" disabled={archiveData.length === 0 || working} onClick={claimAll}>
          {working ? (
            <>
              <Spinner />
              {t("component.common.processing")}
            </>
          ) : (
            t("views.tlManager.importMchad.claimAllArchives")
          )}
        </Button>
      </div>
    </div>
  );
}

// src/components/tlscriptmanager/ImportMchad.vue
<template>
  <div class="space-y-5 p-6">
    <h2 class="text-lg font-semibold text-white">
      Import From Mchad
    </h2>

    <div
      v-if="claimSuccess"
      class="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-100"
    >
      Successfully claimed all imported archives from Mchad
    </div>
    <div
      v-if="claimErrorMsg"
      class="rounded-2xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-100"
    >
      {{ claimErrorMsg }}
    </div>

    <div class="space-y-4 rounded-[calc(var(--radius)+6px)] border border-white/10 bg-white/4 p-4">
      <div class="grid gap-3 md:grid-cols-2">
        <label class="space-y-2">
          <span class="block text-sm font-medium text-slate-300">Room name</span>
          <UiInput v-model="room" />
        </label>
        <label class="space-y-2">
          <span class="block text-sm font-medium text-slate-300">Password</span>
          <UiInput v-model="pass" type="password" />
        </label>
      </div>
      <UiButton variant="secondary" class-name="w-full" @click="checkAvailable">
        {{ $t("component.mainNav.login") }} to Mchad
      </UiButton>
      <p class="text-sm text-slate-400">
        {{ loginText }}
      </p>
    </div>

    <div class="overflow-hidden rounded-[calc(var(--radius)+6px)] border border-white/10">
      <div class="max-h-[40vh] overflow-auto">
        <table class="min-w-full text-sm">
          <thead class="sticky top-0 bg-slate-950/95 backdrop-blur">
            <tr class="border-b border-white/10 text-left text-slate-300">
              <th class="px-4 py-3 font-medium">
                #
              </th>
              <th class="px-4 py-3 font-medium">
                Video Id
              </th>
              <th class="px-4 py-3 font-medium">
                Entry Length
              </th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="(dt, index) in archiveData"
              :key="index"
              class="border-b border-white/8 text-slate-200"
            >
              <td class="px-4 py-3">
                {{ index + 1 }}
              </td>
              <td class="px-4 py-3">
                {{ dt.video_id }}
              </td>
              <td class="px-4 py-3">
                {{ dt.count }}
              </td>
            </tr>
            <tr v-if="archiveData.length === 0">
              <td colspan="3" class="px-4 py-8 text-center text-slate-500">
                No archives loaded yet.
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="flex items-center gap-3">
      <UiButton variant="ghost" @click="$emit('close', {upload: false}); resetData()">
        {{ $t("views.watch.uploadPanel.cancelBtn") }}
      </UiButton>
      <UiButton
        variant="destructive"
        class-name="ml-auto"
        :disabled="(archiveData.length === 0) || (working)"
        @click="claimAll"
      >
        {{ working ? "Processing" : "Claim All Archives" }}
      </UiButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import UiButton from "@/components/ui/button/Button.vue";
import UiInput from "@/components/ui/input/Input.vue";
import { useAppStore } from "@/stores/app";
import backendApi from "@/utils/backend-api";

defineEmits<{
  (e: "close"): void;
}>();

const appStore = useAppStore();
const userdata = computed(() => appStore.userdata);

const room = ref("");
const pass = ref("");
const loginText = ref("");
const archiveData = ref<any[]>([]);
const working = ref(false);
const claimErrorMsg = ref("");
const claimSuccess = ref(false);

function resetData() {
  room.value = "";
  pass.value = "";
  loginText.value = "";
  archiveData.value = [];
  working.value = false;
  claimSuccess.value = false;
  claimErrorMsg.value = "";
}

async function checkAvailable() {
  try {
    working.value = true;
    if (!(room.value && pass.value)) throw new Error("Missing room or pass");
    const { data } = await backendApi.checkMchadMigrate(room.value, pass.value);
    archiveData.value = data.archives;
    loginText.value = `Found Mchad Id: ${data.mchad_user_id}`;
  } catch (e: any) {
    claimErrorMsg.value = e.message;
  }
  working.value = false;
}

async function claimAll() {
  try {
    working.value = true;
    const res = await backendApi.claimMchadMigrate(userdata.value?.jwt, room.value, pass.value);
    if (res.status === 200) {
      claimSuccess.value = true;
    }
  } catch (error: any) {
    claimErrorMsg.value = error.response?.data?.message || error.message;
  }
  working.value = false;
}
</script>
