// src/components/watch/WatchPlaylist.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Icon } from "@/components/ui/Icon";
import { VirtualVideoCardList } from "@/components/video/VirtualVideoCardList";
import { api } from "@/lib/api";
import { useAppState } from "@/lib/store";
import * as icons from "@/lib/icons";

export function WatchPlaylist({ value = 0, video, onInput, onPlayNext }: { value?: number; currentTime?: number; video: any; onInput?: (index: number) => void; onPlayNext?: (payload: { video: any }) => void }) {
  const searchParams = useSearchParams();
  const app = useAppState();
  const [hasError, setHasError] = useState(false);
  const [playlist, setPlaylist] = useState<any>(undefined);
  const videos = useMemo(() => (playlist && playlist.videos) || [], [playlist]);
  const playlistId = searchParams.get("playlist");
  const activePlaylist = useMemo(() => ({ ...(app.playlistActive || {}), id: app.playlistActive?.id || "local", name: app.playlistActive?.name || "Playlist", videos: app.playlist }), [app.playlistActive, app.playlist]);

  function updateCurrentIndex(nextPlaylist = playlist) {
    const currentId = video?.id;
    const newIndex = (nextPlaylist?.videos || []).findIndex(({ id }: any) => id === currentId);
    onInput?.(newIndex);
  }

  function nextVideo() {
    if (videos[value + 1]) onInput?.(value + 1);
  }

  function loadPlaylist(id: string) {
    setHasError(false);
    if (id === activePlaylist.id || id === "local") {
      setPlaylist(activePlaylist);
      updateCurrentIndex(activePlaylist);
      return;
    }
    api.getPlaylist(id)
      .then(({ data }: any) => {
        setPlaylist(data);
        updateCurrentIndex(data);
      })
      .catch((e: any) => {
        console.error(e);
        setHasError(true);
      });
  }

  useEffect(() => {
    if (!playlistId) return;
    updateCurrentIndex();
    loadPlaylist(playlistId);
  }, [playlistId, activePlaylist.id, activePlaylist.videos]);

  useEffect(() => { updateCurrentIndex(); }, [video?.id, playlist?.id]);

  useEffect(() => {
    if (!videos.length || videos.length === value || value === -1 || video?.id === videos[value]?.id) return;
    onPlayNext?.({ video: videos[value] });
  }, [value, videos, video?.id, onPlayNext]);

  if (!playlistId) return null;
  return (
    <div className="mb-2">
      <Card className="rounded-none p-0 shadow-none">
        {playlist ? (
          <>
            <div className="flex items-start justify-between gap-3 px-4 py-4">
              <div>
                <div className="text-base font-semibold text-white">{playlist.name}</div>
                <div className="pt-1 text-sm text-slate-400">{value + 1}/{videos.length}</div>
              </div>
              <Button type="button" size="icon" title="Next video" onClick={nextVideo}>
                <Icon icon={icons.mdiArrowLeft} className="rotate-180" />
              </Button>
            </div>
            <div className="border-t border-white/10" />
            <VirtualVideoCardList playlist={playlist} includeChannel horizontal activeIndex={value} height={`${Math.min(videos.length, 6) * 102}px`} />
          </>
        ) : null}
        {hasError ? <div className="px-4 py-4 text-sm text-rose-300">Error loading playlist, does it exist?</div> : null}
      </Card>
    </div>
  );
}

// src/components/watch/WatchPlaylist.vue
<template>
  <div class="mb-2">
    <UiCard class-name="rounded-none p-0 shadow-none">
      <template v-if="playlist">
        <div class="flex items-start justify-between gap-3 px-4 py-4">
          <div>
            <div class="text-base font-semibold text-white">
              {{ playlist.name }}
            </div>
            <div class="pt-1 text-sm text-slate-400">
              {{ value + 1 }}/{{ videos.length }}
            </div>
          </div>
          <UiButton
            type="button"
            size="icon"
            title="Next video"
            @click="nextVideo"
          >
            <UiIcon :icon="icons.mdiArrowLeft" class-name="rotate-180" />
          </UiButton>
        </div>
        <div class="border-t border-white/10" />
        <VirtualVideoCardList
          :videos="videos"
          :playlist="playlist"
          include-channel
          horizontal
          ignore-block
          :active-index="value"
          :style="{ height: Math.min(videos.length, 6) * 102 + 'px' }"
        />
      </template>
      <div v-if="hasError" class="px-4 py-4 text-sm text-rose-300">
        Error loading playlist, does it exist?
      </div>
    </UiCard>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from "vue";
import { useRoute } from "vue-router";
import VirtualVideoCardList from "@/components/video/VirtualVideoCardList.vue";
import UiButton from "@/components/ui/button/Button.vue";
import UiCard from "@/components/ui/card/Card.vue";
import UiIcon from "@/components/ui/icon/Icon.vue";
import { useWatchStore } from "@/stores/watch";
import { usePlaylistStore } from "@/stores/playlist";
import backendApi from "@/utils/backend-api";

defineOptions({ name: "WatchPlaylist" });

const props = withDefaults(defineProps<{
  value?: number;
  currentTime?: number;
}>(), {
  value: 0,
  currentTime: 0,
});

const emit = defineEmits<{
  (e: "input", index: number): void;
  (e: "playNext", payload: { video: any }): void;
}>();

const route = useRoute();
const watchStore = useWatchStore();
const playlistStore = usePlaylistStore();

const isLoading = ref(false);
const hasError = ref(false);
const playlist = ref<any>(undefined);

const video = computed(() => watchStore.video);
const active = computed(() => playlistStore.active);
const videos = computed(() => (playlist.value && playlist.value.videos) || []);

function updateCurrentIndex() {
  const currentId = video.value.id;
  const newIndex = videos.value.findIndex(({ id }: any) => id === currentId);
  emit("input", newIndex);
}

function nextVideo() {
  if (videos.value[props.value + 1]) emit("input", props.value + 1);
}

function loadPlaylist(playlistId: string) {
  if (playlistId === active.value.id || playlistId === "local") {
    playlist.value = active.value;
    updateCurrentIndex();
    return;
  }
  isLoading.value = true;
  backendApi
    .getPlaylist(playlistId)
    .then(({ data }: any) => {
      playlist.value = data;
      updateCurrentIndex();
    })
    .catch((e: any) => {
      console.error(e);
      hasError.value = true;
    })
    .finally(() => {
      isLoading.value = false;
    });
}

watch(() => props.value, (nw) => {
  if (
    !videos.value.length
    || videos.value.length === nw
    || nw === -1
    || route.params.id === videos.value[nw].id
  ) {
    return;
  }
  emit("playNext", { video: videos.value[nw] });
});

watch(video, () => {
  updateCurrentIndex();
});

onMounted(() => {
  if (!route.query.playlist) return;
  updateCurrentIndex();
  loadPlaylist(route.query.playlist as string);
});
</script>
