// src/components/watch/WatchSubtitleOverlay.tsx
"use client";

export function WatchSubtitleOverlay({ messages = [] }: { messages?: any[] }) {
  return (
    <div className="overlay flex justify-center">
      <span className="overlay-text">
        {messages.map((msg: any) => (
          <div key={msg.id || msg.key || `${msg.name}-${msg.timestamp}-${msg.message}`} className="text-center">
            {!msg.is_tl ? <div className={`subtitle-name ${msg.is_owner ? "text-[color:var(--color-primary)]" : "text-slate-400"}`}><span>{msg.name} :</span></div> : null}
            {msg.parsed ? <span className="subtitle-text" dangerouslySetInnerHTML={{ __html: msg.parsed }} /> : <span className="subtitle-text">{msg.message}</span>}
          </div>
        ))}
      </span>
    </div>
  );
}

// src/components/watch/WatchSubtitleOverlay.vue
<template>
  <div class="overlay flex justify-center">
    <span class="overlay-text">
      <div
        v-for="msg in messages"
        :key="msg.id"
        class="text-center"
      >
        <div
          v-if="!msg.is_tl"
          class="subtitle-name"
          :class="msg.is_owner ? 'text-[color:var(--color-primary)]' : 'text-slate-400'"
        >
          <span>{{ msg.name }} :</span>
        </div>
        <span v-if="msg.parsed" class="subtitle-text" v-html="msg.parsed" />
        <span v-else class="subtitle-text">{{ msg.message }}</span>
      </div>
    </span>
  </div>
</template>

<script setup lang="ts">
defineOptions({ name: "WatchVideoOverlay" });

defineProps<{
  messages: any[];
}>();
</script>

<style scoped>
.overlay {
  position: absolute;
  bottom: 48px;
  bottom: min(48px, 10%);
  width: 90%;
  margin-left: 5%;
}

.subtitle-text {
    word-wrap: break-word;
    box-shadow: 10px 0 0 rgba(0,0,0,0.75), -10px 0 0 rgba(0,0,0,0.75);
    background: rgba(0,0,0,0.75);
    white-space: pre-wrap;
    color: rgba(255,255,255,1)
}
.subtitle-name {
  font-size: 16px;
  font-size: max(1vw, 20px);
  margin-bottom: -.3rem;
}

.subtitle-name span {
  background: rgba(0,0,0,0.75);
  padding: 0 8px;
}
</style>
